// This file is auto-generated by oagen. Do not edit.

export interface CreateFlagTargetType {
  /** A unique key used as the `target_type` of a Flag Target, scoped to the project. May contain lowercase letters, numbers, underscores and hyphens. */
  slug: string;
}

export interface CreateFlagTargetTypeResponse {
  slug: string;
}
