// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type {
  PortalLinkResponse,
  PortalLinkResponseWire,
} from './interfaces/portal-link-response.interface';
import type { GenerateLink } from './interfaces/generate-link.interface';
import { deserializePortalLinkResponse } from './serializers/portal-link-response.serializer';
import { serializeGenerateLink } from './serializers/generate-link.serializer';

export class AdminPortal {
  constructor(private readonly workos: WorkOS) {}

  /**
   * Generate a Portal Link
   *
   * Generate a Portal Link scoped to an Organization.
   * @param payload - Object containing organization.
   * @returns {PortalLinkResponse}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async generatePortalLink(payload: GenerateLink): Promise<PortalLinkResponse> {
    const { data } = await this.workos.post<PortalLinkResponseWire>(
      '/portal/generate_link',
      serializeGenerateLink(payload),
    );
    return deserializePortalLinkResponse(data);
  }
}
