// This file is auto-generated by oagen. Do not edit.

import {
  deserializeSSOIntentOptions,
  serializeSSOIntentOptions,
} from './serializers/sso-intent-options.serializer';
import {
  deserializeIntentOptions,
  serializeIntentOptions,
} from './serializers/intent-options.serializer';
import {
  deserializeGenerateLink,
  serializeGenerateLink,
} from './serializers/generate-link.serializer';
import {
  deserializePortalLinkResponse,
  serializePortalLinkResponse,
} from './serializers/portal-link-response.serializer';
import type { SSOIntentOptionsResponse } from './interfaces/sso-intent-options.interface';
import type { IntentOptionsResponse } from './interfaces/intent-options.interface';
import type { GenerateLinkResponse } from './interfaces/generate-link.interface';
import type { PortalLinkResponseWire } from './interfaces/portal-link-response.interface';
import ssoIntentOptionsFixture from './fixtures/sso-intent-options.json';
import intentOptionsFixture from './fixtures/intent-options.json';
import generateLinkFixture from './fixtures/generate-link.json';
import portalLinkResponseFixture from './fixtures/portal-link-response.json';

describe('SSOIntentOptionsSerializer', () => {
  it('round-trips through serialize/deserialize', () => {
    const fixture = ssoIntentOptionsFixture as SSOIntentOptionsResponse;
    const deserialized = deserializeSSOIntentOptions(fixture);
    const reserialized = serializeSSOIntentOptions(deserialized);
    expect(reserialized).toEqual(expect.objectContaining(fixture));
  });
});

describe('IntentOptionsSerializer', () => {
  it('round-trips through serialize/deserialize', () => {
    const fixture = intentOptionsFixture as IntentOptionsResponse;
    const deserialized = deserializeIntentOptions(fixture);
    const reserialized = serializeIntentOptions(deserialized);
    expect(reserialized).toEqual(expect.objectContaining(fixture));
  });
});

describe('GenerateLinkSerializer', () => {
  it('round-trips through serialize/deserialize', () => {
    const fixture = generateLinkFixture as GenerateLinkResponse;
    const deserialized = deserializeGenerateLink(fixture);
    const reserialized = serializeGenerateLink(deserialized);
    expect(reserialized).toEqual(expect.objectContaining(fixture));
  });
});

describe('PortalLinkResponseSerializer', () => {
  it('round-trips through serialize/deserialize', () => {
    const fixture = portalLinkResponseFixture as PortalLinkResponseWire;
    const deserialized = deserializePortalLinkResponse(fixture);
    const reserialized = serializePortalLinkResponse(deserialized);
    expect(reserialized).toEqual(expect.objectContaining(fixture));
  });
});
