// This file is auto-generated by oagen. Do not edit.

/** The user or API key that performed an action. */
export interface Actor {
  /** Unique identifier of the actor. */
  id: string;
  /** Display name of the actor. */
  name: string;
}

export interface ActorResponse {
  id: string;
  name: string;
}
