// This file is auto-generated by oagen. Do not edit.

export interface CreateRekeyOptions {
  /** Map of values used to determine the new encryption key. */
  context: Record<string, string>;
  /** Base64-encoded encrypted data key blob to re-encrypt. */
  encryptedKeys: string;
}
