// This file is auto-generated by oagen. Do not edit.

export interface AddRolePermission {
  /** The slug of the permission to add to the role. */
  slug: string;
}

export interface AddRolePermissionResponse {
  slug: string;
}
