// This file is auto-generated by oagen. Do not edit.

import type { AuthorizationOrganizationRolesType } from '../../common/interfaces/authorization-organization-roles-type.interface';

export interface AuthorizationOrganizationRolesListItem {
  /** A unique slug for the role. */
  slug: string;
  /** Distinguishes the role object. */
  object: 'role';
  /** Unique identifier of the role. */
  id: string;
  /** A descriptive name for the role. */
  name: string;
  /** An optional description of the role. */
  description: string | null;
  /** Whether the role is scoped to the environment or an organization. */
  type: AuthorizationOrganizationRolesType;
  /** The slug of the resource type the role is scoped to. */
  resourceTypeSlug: string;
  /** The permission slugs assigned to the role. */
  permissions: string[];
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
}

export interface AuthorizationOrganizationRolesListItemResponse {
  slug: string;
  object: 'role';
  id: string;
  name: string;
  description: string | null;
  type: AuthorizationOrganizationRolesType;
  resource_type_slug: string;
  permissions: string[];
  created_at: string;
  updated_at: string;
}
