// This file is auto-generated by oagen. Do not edit.

export interface CheckOptions {
  /** The ID of the organization membership to check. */
  organizationMembershipId: string;
  /** The slug of the permission to check. */
  permissionSlug: string;
  /** The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`. */
  resourceId?: string;
  /** The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`. */
  resourceExternalId?: string;
  /** The slug of the resource type. Required with `resource_external_id`. Mutually exclusive with `resource_id`. */
  resourceTypeSlug?: string;
}
