// This file is auto-generated by oagen. Do not edit.

export interface CreateOrganizationRoleOptions {
  /** The ID of the organization. */
  organizationId: string;
  /** A unique identifier for the role within the organization. When provided, must begin with 'org-' and contain only lowercase letters, numbers, hyphens, and underscores. When omitted, a slug is auto-generated from the role name and a random suffix. */
  slug?: string;
  /** A descriptive name for the role. */
  name: string;
  /** An optional description of the role's purpose. */
  description?: string | null;
  /** The slug of the resource type the role is scoped to. */
  resourceTypeSlug?: string;
}
