// This file is auto-generated by oagen. Do not edit.

export interface GetOrganizationRoleOptions {
  /** The ID of the organization. */
  organizationId: string;
  /** The slug of the role. */
  slug: string;
}
