// This file is auto-generated by oagen. Do not edit.

import type { ListData, ListDataResponse } from './list-data.interface';

export interface List {
  object: 'list';
  /** The list of records for the current page. */
  data: ListData[];
}

export interface ListResponse {
  object: 'list';
  data: ListDataResponse[];
}
