// This file is auto-generated by oagen. Do not edit.

import type { PaginationOptions } from '../../common/interfaces/pagination-options.interface';

export interface ListResourcesForMembershipOptions extends PaginationOptions {
  /** The ID of the organization membership. */
  organizationMembershipId: string;
  /** The permission slug to filter by. Only child resources where the organization membership has this permission are returned. */
  permissionSlug: string;
  /** The WorkOS ID of the parent resource. Provide this or both `parent_resource_external_id` and `parent_resource_type_slug`, but not both. Mutually exclusive with `parent_resource_type_slug` and `parent_resource_external_id`. */
  parentResourceId?: string;
  /** The slug of the parent resource type. Must be provided together with `parent_resource_external_id`. Required with `parent_resource_external_id`. Mutually exclusive with `parent_resource_id`. */
  parentResourceTypeSlug?: string;
  /** The application-specific external identifier of the parent resource. Must be provided together with `parent_resource_type_slug`. Required with `parent_resource_type_slug`. Mutually exclusive with `parent_resource_id`. */
  parentResourceExternalId?: string;
}
