// This file is auto-generated by oagen. Do not edit.

export const PaginationOrder = {
  Normal: 'normal',
  Desc: 'desc',
  Asc: 'asc',
} as const;

export type PaginationOrder =
  (typeof PaginationOrder)[keyof typeof PaginationOrder];
