// This file is auto-generated by oagen. Do not edit.

export interface UpdateEnvironmentRoleOptions {
  /** The slug of the environment role. */
  slug: string;
  /** A descriptive name for the role. */
  name?: string;
  /** An optional description of the role. */
  description?: string | null;
}
