// This file is auto-generated by oagen. Do not edit.

import type {
  UpdateOrganizationRole,
  UpdateOrganizationRoleResponse,
} from './update-organization-role.interface';

export type UpdateRole = UpdateOrganizationRole;
export type UpdateRoleResponse = UpdateOrganizationRoleResponse;
