// This file is auto-generated by oagen. Do not edit.

export interface UpdateOrganizationRole {
  /** A descriptive name for the role. */
  name?: string;
  /** An optional description of the role's purpose. */
  description?: string | null;
}

export interface UpdateOrganizationRoleResponse {
  name?: string;
  description?: string | null;
}
