// This file is auto-generated by oagen. Do not edit.

/** The resource the role is assigned on. */
export interface UserRoleAssignmentResource {
  /** The unique ID of the Resource. */
  id: string;
  /** An identifier you provide to reference the resource in your system. */
  externalId: string;
  /** The slug of the resource type this resource belongs to. */
  resourceTypeSlug: string;
}

export interface UserRoleAssignmentResourceResponse {
  id: string;
  external_id: string;
  resource_type_slug: string;
}
