// This file is auto-generated by oagen. Do not edit.

import type {
  DirectoryUserWithGroupsEmail,
  DirectoryUserWithGroupsEmailResponse,
} from '../interfaces/directory-user-with-groups-email.interface';

export const deserializeDirectoryUserWithGroupsEmail = (
  response: DirectoryUserWithGroupsEmailResponse,
): DirectoryUserWithGroupsEmail => ({
  primary: response.primary,
  type: response.type,
  value: response.value ?? null,
});

export const serializeDirectoryUserWithGroupsEmail = (
  model: DirectoryUserWithGroupsEmail,
): DirectoryUserWithGroupsEmailResponse => ({
  primary: model.primary,
  type: model.type,
  value: model.value ?? null,
});

export {
  deserializeDsyncGroupUserAddedDataUserEmail as deserializeDirectoryUserWithGroupsEmail,
  serializeDsyncGroupUserAddedDataUserEmail as serializeDirectoryUserWithGroupsEmail,
} from '../../common/serializers/dsync-group-user-added-data-user-email.serializer';
