// This file is auto-generated by oagen. Do not edit.

import type {
  Directory,
  DirectoryResponse,
} from '../interfaces/directory.interface';
import { deserializeDirectoryMetadata } from './directory-metadata.serializer';
import type { DirectoryState } from '../interfaces/directory-state.interface';

const deserializeDirectoryState = (value: string): DirectoryState => {
  if (value === 'linked') {
    return 'active';
  }
  if (value === 'unlinked') {
    return 'inactive';
  }
  return value as DirectoryState;
};

export const deserializeDirectory = (
  response: DirectoryResponse,
): Directory => ({
  object: response.object,
  id: response.id,
  organizationId: response.organization_id,
  externalKey: response.external_key,
  type: response.type,
  state: deserializeDirectoryState(response.state),
  name: response.name,
  domain: response.domain,
  metadata:
    response.metadata != null
      ? deserializeDirectoryMetadata(response.metadata)
      : undefined,
  createdAt: new Date(response.created_at),
  updatedAt: new Date(response.updated_at),
});
