// This file is auto-generated by oagen. Do not edit.

import type {
  SlimRole,
  SlimRoleResponse,
} from '../interfaces/slim-role.interface';

export const deserializeSlimRole = (response: SlimRoleResponse): SlimRole => ({
  slug: response.slug,
});

export const serializeSlimRole = (model: SlimRole): SlimRoleResponse => ({
  slug: model.slug,
});
