// This file is auto-generated by oagen. Do not edit.

export interface AuthorizationPermission {
  /** Distinguishes the Permission object. */
  object: 'permission';
  /** Unique identifier of the Permission. */
  id: string;
  /** A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks. */
  slug: string;
  /** A descriptive name for the Permission. */
  name: string;
  /** An optional description of the Permission. */
  description: string | null;
  /** Whether the permission is a system permission. System permissions are managed by WorkOS and cannot be deleted. */
  system: boolean;
  /** The slug of the resource type associated with the permission. */
  resourceTypeSlug: string;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
}

export interface AuthorizationPermissionResponse {
  object: 'permission';
  id: string;
  slug: string;
  name: string;
  description: string | null;
  system: boolean;
  resource_type_slug: string;
  created_at: string;
  updated_at: string;
}
