// This file is auto-generated by oagen. Do not edit.

export * from './authorization-permission.interface';
export * from './create-authorization-permission.interface';
export * from './update-authorization-permission.interface';
