// This file is auto-generated by oagen. Do not edit.

import type {
  UpdateOrganizationRole,
  UpdateOrganizationRoleResponse,
} from '../../authorization/interfaces/update-organization-role.interface';

export type UpdateAuthorizationPermission = UpdateOrganizationRole;
export type UpdateAuthorizationPermissionResponse =
  UpdateOrganizationRoleResponse;
