// This file is auto-generated by oagen. Do not edit.

import type {
  SSOLogoutAuthorizeResponse,
  SSOLogoutAuthorizeResponseWire,
} from '../interfaces/sso-logout-authorize-response.interface';

export const deserializeSSOLogoutAuthorizeResponse = (
  response: SSOLogoutAuthorizeResponseWire,
): SSOLogoutAuthorizeResponse => ({
  logoutUrl: response.logout_url,
  logoutToken: response.logout_token,
});

export const serializeSSOLogoutAuthorizeResponse = (
  model: SSOLogoutAuthorizeResponse,
): SSOLogoutAuthorizeResponseWire => ({
  logout_url: model.logoutUrl,
  logout_token: model.logoutToken,
});
