// This file is auto-generated by oagen. Do not edit.

import type {
  OrganizationDomain,
  OrganizationDomainResponse,
} from '../../organization-domains/interfaces/organization-domain.interface';

export interface Organization {
  /** Distinguishes the Organization object. */
  object: 'organization';
  /** Unique identifier of the Organization. */
  id: string;
  /** A descriptive name for the Organization. This field does not need to be unique. */
  name: string;
  /** List of Organization Domains. */
  domains: OrganizationDomain[];
  /** Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization. */
  metadata?: Record<string, string>;
  /** The external ID of the Organization. */
  externalId?: string | null;
  /** The Stripe customer ID of the Organization. */
  stripeCustomerId?: string;
  /** An ISO 8601 timestamp. */
  createdAt: Date;
  /** An ISO 8601 timestamp. */
  updatedAt: Date;
  /**
   * Whether the Organization allows profiles outside of its managed domains.
   * @deprecated
   */
  allowProfilesOutsideOrganization?: boolean;
}

export interface OrganizationResponse {
  object: 'organization';
  id: string;
  name: string;
  domains: OrganizationDomainResponse[];
  metadata?: Record<string, string>;
  external_id?: string | null;
  stripe_customer_id?: string;
  created_at: string;
  updated_at: string;
  allow_profiles_outside_organization?: boolean;
}
