// This file is auto-generated by oagen. Do not edit.

import type { OrganizationDomainDataState } from './organization-domain-data-state.interface';

export interface OrganizationDomainData {
  /** The domain value. */
  domain: string;
  /** The verification state of the domain. */
  state: OrganizationDomainDataState;
}

export interface OrganizationDomainDataResponse {
  domain: string;
  state: OrganizationDomainDataState;
}
