// This file is auto-generated by oagen. Do not edit.

export const WebhookEndpointStatus = {
  Enabled: 'enabled',
  Disabled: 'disabled',
} as const;

export type WebhookEndpointStatus =
  (typeof WebhookEndpointStatus)[keyof typeof WebhookEndpointStatus];
