// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import { AutoPaginatable } from '../common/utils/pagination';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import type { CheckOptions } from './interfaces/check-options.interface';
import type { ListResourcesForMembershipOptions } from './interfaces/list-resources-for-membership-options.interface';
import type { ListEffectivePermissionsOptions } from './interfaces/list-effective-permissions-options.interface';
import type { ListEffectivePermissionsByExternalIdOptions } from './interfaces/list-effective-permissions-by-external-id-options.interface';
import type { ListRoleAssignmentsOptions } from './interfaces/list-role-assignments-options.interface';
import type { AssignRoleOptions } from './interfaces/assign-role-options.interface';
import type { RemoveRoleOptions } from './interfaces/remove-role-options.interface';
import type { RemoveRoleAssignmentOptions } from './interfaces/remove-role-assignment-options.interface';
import type { ListOrganizationRolesOptions } from './interfaces/list-organization-roles-options.interface';
import type { CreateOrganizationRoleOptions } from './interfaces/create-organization-role-options.interface';
import type { GetOrganizationRoleOptions } from './interfaces/get-organization-role-options.interface';
import type { UpdateOrganizationRoleOptions } from './interfaces/update-organization-role-options.interface';
import type { DeleteOrganizationRoleOptions } from './interfaces/delete-organization-role-options.interface';
import type { AddOrganizationRolePermissionOptions } from './interfaces/add-organization-role-permission-options.interface';
import type { SetOrganizationRolePermissionsOptions } from './interfaces/set-organization-role-permissions-options.interface';
import type { RemoveOrganizationRolePermissionOptions } from './interfaces/remove-organization-role-permission-options.interface';
import type { GetAuthorizationResourceByExternalIdOptions } from './interfaces/get-authorization-resource-by-external-id-options.interface';
import type { UpdateAuthorizationResourceByExternalIdOptions } from './interfaces/update-authorization-resource-by-external-id-options.interface';
import type { DeleteAuthorizationResourceByExternalIdOptions } from './interfaces/delete-authorization-resource-by-external-id-options.interface';
import type { ListMembershipsForResourceByExternalIdOptions } from './interfaces/list-memberships-for-resource-by-external-id-options.interface';
import type { ListRoleAssignmentsForResourceByExternalIdOptions } from './interfaces/list-role-assignments-for-resource-by-external-id-options.interface';
import type { ListAuthorizationResourcesOptions } from './interfaces/list-authorization-resources-options.interface';
import type { CreateResourceOptions } from './interfaces/create-resource-options.interface';
import type { GetResourceOptions } from './interfaces/get-resource-options.interface';
import type { UpdateAuthorizationResourceOptions } from './interfaces/update-authorization-resource-options.interface';
import type { DeleteAuthorizationResourceOptions } from './interfaces/delete-authorization-resource-options.interface';
import type { ListMembershipsForResourceOptions } from './interfaces/list-memberships-for-resource-options.interface';
import type { ListRoleAssignmentsForResourceOptions } from './interfaces/list-role-assignments-for-resource-options.interface';
import type { CreateEnvironmentRoleOptions } from './interfaces/create-environment-role-options.interface';
import type { GetEnvironmentRoleOptions } from './interfaces/get-environment-role-options.interface';
import type { UpdateEnvironmentRoleOptions } from './interfaces/update-environment-role-options.interface';
import type { AddEnvironmentRolePermissionOptions } from './interfaces/add-environment-role-permission-options.interface';
import type { SetEnvironmentRolePermissionsOptions } from './interfaces/set-environment-role-permissions-options.interface';
import type { CreatePermissionOptions } from './interfaces/create-permission-options.interface';
import type { GetPermissionOptions } from './interfaces/get-permission-options.interface';
import type { UpdatePermissionOptions } from './interfaces/update-permission-options.interface';
import type { DeletePermissionOptions } from './interfaces/delete-permission-options.interface';
import type {
  AuthorizationCheck,
  AuthorizationCheckResponse,
} from './interfaces/authorization-check.interface';
import type {
  RoleAssignment,
  RoleAssignmentResponse,
} from './interfaces/role-assignment.interface';
import type {
  RoleList,
  RoleListResponse,
} from '../roles/interfaces/role-list.interface';
import type { OrganizationRole } from './interfaces/organization-role.interface';
import type { OrganizationRoleResponse } from '../roles/interfaces/role.interface';
import type {
  AuthorizationResource,
  AuthorizationResourceResponse,
} from './interfaces/authorization-resource.interface';
import type {
  EnvironmentRole,
  EnvironmentRoleResponse,
} from './interfaces/environment-role.interface';
import type {
  Permission,
  PermissionResponse,
} from './interfaces/permission.interface';
import type {
  AuthorizationPermission,
  AuthorizationPermissionResponse,
} from './interfaces/authorization-permission.interface';
import type { CheckAuthorizationResponse } from './interfaces/check-authorization.interface';
import type { AssignRoleResponse } from './interfaces/assign-role.interface';
import type { RemoveRoleResponse } from './interfaces/remove-role.interface';
import type { CreateOrganizationRoleResponse } from './interfaces/create-organization-role.interface';
import type { UpdateOrganizationRoleResponse } from './interfaces/update-organization-role.interface';
import type { AddRolePermissionResponse } from './interfaces/add-role-permission.interface';
import type { SetRolePermissionsResponse } from './interfaces/set-role-permissions.interface';
import type { UpdateAuthorizationResourceResponse } from './interfaces/update-authorization-resource.interface';
import type { CreateAuthorizationResourceResponse } from './interfaces/create-authorization-resource.interface';
import type { CreateRoleResponse } from './interfaces/create-role.interface';
import type { UpdateRoleResponse } from './interfaces/update-role.interface';
import type { CreateAuthorizationPermissionResponse } from './interfaces/create-authorization-permission.interface';
import type { UpdateAuthorizationPermissionResponse } from './interfaces/update-authorization-permission.interface';
import type {
  AuthorizationOrganizationMembership,
  AuthorizationOrganizationMembershipResponse,
} from '../user-management/interfaces/organization-membership.interface';
import { deserializeAuthorizationCheck } from './serializers/authorization-check.serializer';
import { deserializeRoleAssignment } from './serializers/role-assignment.serializer';
import { deserializeRoleList } from '../roles/serializers/role-list.serializer';
import { deserializeOrganizationRole } from './serializers/organization-role.serializer';
import { deserializeAuthorizationResource } from './serializers/authorization-resource.serializer';
import { deserializeEnvironmentRole } from './serializers/environment-role.serializer';
import { deserializePermission } from './serializers/permission.serializer';
import { deserializeAuthorizationPermission } from './serializers/authorization-permission.serializer';
import { deserializeAuthorizationOrganizationMembership } from '../user-management/serializers/organization-membership.serializer';
import { serializeCheckAuthorization } from './serializers/check-authorization.serializer';
import { serializeAssignRole } from './serializers/assign-role.serializer';
import { serializeRemoveRole } from './serializers/remove-role.serializer';
import { serializeCreateOrganizationRole } from './serializers/create-organization-role.serializer';
import { serializeUpdateOrganizationRole } from './serializers/update-organization-role.serializer';
import { serializeAddRolePermission } from './serializers/add-role-permission.serializer';
import { serializeSetRolePermissions } from './serializers/set-role-permissions.serializer';
import { serializeUpdateAuthorizationResource } from './serializers/update-authorization-resource.serializer';
import { serializeCreateAuthorizationResource } from './serializers/create-authorization-resource.serializer';
import { serializeCreateRole } from './serializers/create-role.serializer';
import { serializeUpdateRole } from './serializers/update-role.serializer';
import { serializeCreateAuthorizationPermission } from './serializers/create-authorization-permission.serializer';
import { serializeUpdateAuthorizationPermission } from './serializers/update-authorization-permission.serializer';

const serializeListResourcesForMembershipOptions = (
  options: ListResourcesForMembershipOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    before: options.before,
    after: options.after,
    order: options.order,
  };
  if (options.permissionSlug !== undefined)
    wire.permission_slug = options.permissionSlug;
  if (options.parentResourceId !== undefined)
    wire.parent_resource_id = options.parentResourceId;
  if (options.parentResourceTypeSlug !== undefined)
    wire.parent_resource_type_slug = options.parentResourceTypeSlug;
  if (options.parentResourceExternalId !== undefined)
    wire.parent_resource_external_id = options.parentResourceExternalId;
  return wire as PaginationOptions;
};

const serializeListRoleAssignmentsOptions = (
  options: ListRoleAssignmentsOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    before: options.before,
    after: options.after,
    order: options.order,
  };
  if (options.resourceId !== undefined) wire.resource_id = options.resourceId;
  if (options.resourceExternalId !== undefined)
    wire.resource_external_id = options.resourceExternalId;
  if (options.resourceTypeSlug !== undefined)
    wire.resource_type_slug = options.resourceTypeSlug;
  return wire as PaginationOptions;
};

const serializeListMembershipsForResourceByExternalIdOptions = (
  options: ListMembershipsForResourceByExternalIdOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    before: options.before,
    after: options.after,
    order: options.order,
  };
  if (options.permissionSlug !== undefined)
    wire.permission_slug = options.permissionSlug;
  if (options.assignment !== undefined) wire.assignment = options.assignment;
  return wire as PaginationOptions;
};

const serializeListRoleAssignmentsForResourceByExternalIdOptions = (
  options: ListRoleAssignmentsForResourceByExternalIdOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    before: options.before,
    after: options.after,
    order: options.order,
  };
  if (options.roleSlug !== undefined) wire.role_slug = options.roleSlug;
  return wire as PaginationOptions;
};

const serializeListAuthorizationResourcesOptions = (
  options: ListAuthorizationResourcesOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    before: options.before,
    after: options.after,
    order: options.order,
  };
  if (options.organizationId !== undefined)
    wire.organization_id = options.organizationId;
  if (options.resourceTypeSlug !== undefined)
    wire.resource_type_slug = options.resourceTypeSlug;
  if (options.resourceExternalId !== undefined)
    wire.resource_external_id = options.resourceExternalId;
  if (options.parentResourceId !== undefined)
    wire.parent_resource_id = options.parentResourceId;
  if (options.parentResourceTypeSlug !== undefined)
    wire.parent_resource_type_slug = options.parentResourceTypeSlug;
  if (options.parentExternalId !== undefined)
    wire.parent_external_id = options.parentExternalId;
  return wire as PaginationOptions;
};

const serializeListMembershipsForResourceOptions = (
  options: ListMembershipsForResourceOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    before: options.before,
    after: options.after,
    order: options.order,
  };
  if (options.permissionSlug !== undefined)
    wire.permission_slug = options.permissionSlug;
  if (options.assignment !== undefined) wire.assignment = options.assignment;
  return wire as PaginationOptions;
};

const serializeListRoleAssignmentsForResourceOptions = (
  options: ListRoleAssignmentsForResourceOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    before: options.before,
    after: options.after,
    order: options.order,
  };
  if (options.roleSlug !== undefined) wire.role_slug = options.roleSlug;
  return wire as PaginationOptions;
};

export class Authorization {
  constructor(private readonly workos: WorkOS) {}

  /**
   * Check authorization
   *
   * Check if an organization membership has a specific permission on a resource. Supports identification by resource_id OR by resource_external_id + resource_type_slug.
   * @param options - Object containing permissionSlug.
   * @param options.organizationMembershipId - The ID of the organization membership to check.
   * @example "om_01HXYZ123456789ABCDEFGHIJ"
   * @param options.permissionSlug - The slug of the permission to check.
   * @example "posts:create"
   * @param options.resourceId - The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`.
   * @example "resource_01HXYZ123456789ABCDEFGHIJ"
   * @param options.resourceExternalId - The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`.
   * @example "my-custom-id"
   * @param options.resourceTypeSlug - The slug of the resource type. Required with `resource_external_id`. Mutually exclusive with `resource_id`.
   * @example "document"
   * @returns {Promise<AuthorizationCheck>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async check(options: CheckOptions): Promise<AuthorizationCheck> {
    const { organizationMembershipId, ...payload } = options;
    const { data } = await this.workos.post<
      AuthorizationCheckResponse,
      CheckAuthorizationResponse
    >(
      `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/check`,
      serializeCheckAuthorization(payload),
    );
    return deserializeAuthorizationCheck(data);
  }

  /**
   * List resources for organization membership
   *
   * Returns all child resources of a parent resource where the organization membership has a specific permission. This is useful for resource discovery—answering "What projects can this user access in this workspace?"
   *
   * You must provide either `parent_resource_id` or both `parent_resource_external_id` and `parent_resource_type_slug` to identify the parent resource.
   * @param options - Pagination and filter options.
   * @param options.organizationMembershipId - The ID of the organization membership.
   * @example "om_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<AutoPaginatable<AuthorizationResource, PaginationOptions>>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listResourcesForMembership(
    options: ListResourcesForMembershipOptions,
  ): Promise<AutoPaginatable<AuthorizationResource, PaginationOptions>> {
    const { organizationMembershipId } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<
        AuthorizationResourceResponse,
        AuthorizationResource
      >(
        this.workos,
        `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/resources`,
        deserializeAuthorizationResource,
        options
          ? serializeListResourcesForMembershipOptions(options)
          : undefined,
      ),
      (params) =>
        fetchAndDeserialize<
          AuthorizationResourceResponse,
          AuthorizationResource
        >(
          this.workos,
          `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/resources`,
          deserializeAuthorizationResource,
          params,
        ),
      options ? serializeListResourcesForMembershipOptions(options) : undefined,
    );
  }

  /**
   * List effective permissions for an organization membership on a resource
   *
   * Returns all permissions the organization membership effectively has on a resource, including permissions inherited through roles assigned to ancestor resources.
   * @param options - Pagination and filter options.
   * @param options.organizationMembershipId - The ID of the organization membership.
   * @example "om_01HXYZ123456789ABCDEFGHIJ"
   * @param options.resourceId - The ID of the authorization resource.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<AutoPaginatable<Permission, PaginationOptions>>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listEffectivePermissions(
    options: ListEffectivePermissionsOptions,
  ): Promise<AutoPaginatable<Permission, PaginationOptions>> {
    const { organizationMembershipId, resourceId, ...paginationOptions } =
      options;
    return new AutoPaginatable(
      await fetchAndDeserialize<PermissionResponse, Permission>(
        this.workos,
        `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/resources/${encodeURIComponent(resourceId)}/permissions`,
        deserializePermission,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<PermissionResponse, Permission>(
          this.workos,
          `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/resources/${encodeURIComponent(resourceId)}/permissions`,
          deserializePermission,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * List effective permissions for an organization membership on a resource by external ID
   *
   * Returns all permissions the organization membership effectively has on a resource identified by its external ID, including permissions inherited through roles assigned to ancestor resources.
   * @param options - Pagination and filter options.
   * @param options.organizationMembershipId - The ID of the organization membership.
   * @example "om_01HXYZ123456789ABCDEFGHIJ"
   * @param options.resourceTypeSlug - The slug of the resource type.
   * @example "document"
   * @param options.externalId - An identifier you provide to reference the resource in your system.
   * @example "doc-456"
   * @returns {Promise<AutoPaginatable<Permission, PaginationOptions>>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listEffectivePermissionsByExternalId(
    options: ListEffectivePermissionsByExternalIdOptions,
  ): Promise<AutoPaginatable<Permission, PaginationOptions>> {
    const {
      organizationMembershipId,
      resourceTypeSlug,
      externalId,
      ...paginationOptions
    } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<PermissionResponse, Permission>(
        this.workos,
        `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}/permissions`,
        deserializePermission,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<PermissionResponse, Permission>(
          this.workos,
          `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}/permissions`,
          deserializePermission,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * List role assignments
   *
   * List all role assignments for an organization membership. This returns all roles that have been assigned to the user on resources, including organization-level and sub-resource roles.
   * @param options - Pagination and filter options.
   * @param options.organizationMembershipId - The ID of the organization membership.
   * @example "om_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<AutoPaginatable<RoleAssignment, PaginationOptions>>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async listRoleAssignments(
    options: ListRoleAssignmentsOptions,
  ): Promise<AutoPaginatable<RoleAssignment, PaginationOptions>> {
    const { organizationMembershipId } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<RoleAssignmentResponse, RoleAssignment>(
        this.workos,
        `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/role_assignments`,
        deserializeRoleAssignment,
        options ? serializeListRoleAssignmentsOptions(options) : undefined,
      ),
      (params) =>
        fetchAndDeserialize<RoleAssignmentResponse, RoleAssignment>(
          this.workos,
          `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/role_assignments`,
          deserializeRoleAssignment,
          params,
        ),
      options ? serializeListRoleAssignmentsOptions(options) : undefined,
    );
  }

  /**
   * Assign a role
   *
   * Assign a role to an organization membership on a specific resource.
   * @param options - Object containing roleSlug.
   * @param options.organizationMembershipId - The ID of the organization membership.
   * @example "om_01HXYZ123456789ABCDEFGHIJ"
   * @param options.roleSlug - The slug of the role to assign.
   * @example "editor"
   * @param options.resourceId - The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`.
   * @example "authz_resource_01HXYZ123456789ABCDEFGH"
   * @param options.resourceExternalId - The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`.
   * @example "project-ext-456"
   * @param options.resourceTypeSlug - The resource type slug. Required with `resource_external_id`. Mutually exclusive with `resource_id`.
   * @example "project"
   * @returns {Promise<RoleAssignment>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async assignRole(options: AssignRoleOptions): Promise<RoleAssignment> {
    const { organizationMembershipId, ...payload } = options;
    const { data } = await this.workos.post<
      RoleAssignmentResponse,
      AssignRoleResponse
    >(
      `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/role_assignments`,
      serializeAssignRole(payload),
    );
    return deserializeRoleAssignment(data);
  }

  /**
   * Remove a role assignment
   *
   * Remove a role assignment by role slug and resource.
   * @param options - Object containing roleSlug.
   * @param options.organizationMembershipId - The ID of the organization membership.
   * @example "om_01HXYZ123456789ABCDEFGHIJ"
   * @param options.roleSlug - The slug of the role to remove.
   * @example "editor"
   * @param options.resourceId - The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`.
   * @example "authz_resource_01HXYZ123456789ABCDEFGH"
   * @param options.resourceExternalId - The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`.
   * @example "external_01HXYZ123456789ABCDEFGH"
   * @param options.resourceTypeSlug - The resource type slug. Required with `resource_external_id`. Mutually exclusive with `resource_id`.
   * @example "project"
   * @returns {Promise<void>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async removeRole(options: RemoveRoleOptions): Promise<void> {
    const { organizationMembershipId, ...payload } = options;
    await this.workos.deleteWithBody<RemoveRoleResponse>(
      `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/role_assignments`,
      serializeRemoveRole(payload),
    );
  }

  /**
   * Remove a role assignment by ID
   *
   * Remove a role assignment using its ID.
   * @param options - The request options.
   * @param options.organizationMembershipId - The ID of the organization membership.
   * @example "om_01HXYZ123456789ABCDEFGHIJ"
   * @param options.roleAssignmentId - The ID of the role assignment to remove.
   * @example "role_assignment_01HXYZ123456789ABCDEFGH"
   * @returns {Promise<void>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async removeRoleAssignment(
    options: RemoveRoleAssignmentOptions,
  ): Promise<void> {
    const { organizationMembershipId, roleAssignmentId } = options;
    await this.workos.delete(
      `/authorization/organization_memberships/${encodeURIComponent(organizationMembershipId)}/role_assignments/${encodeURIComponent(roleAssignmentId)}`,
    );
  }

  /**
   * List custom roles
   *
   * Get a list of all roles that apply to an organization. This includes both environment roles and custom roles, returned in priority order.
   * @param options - The request options.
   * @param options.organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @returns {Promise<RoleList>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async listOrganizationRoles(
    options: ListOrganizationRolesOptions,
  ): Promise<RoleList> {
    const { organizationId } = options;
    const { data } = await this.workos.get<RoleListResponse>(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/roles`,
    );
    return deserializeRoleList(data);
  }

  /**
   * Create a custom role
   *
   * Create a new custom role for this organization.
   * @param options - Object containing name.
   * @param options.organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - A unique identifier for the role within the organization. When provided, must begin with 'org-' and contain only lowercase letters, numbers, hyphens, and underscores. When omitted, a slug is auto-generated from the role name and a random suffix.
   * @example "org-billing-admin"
   * @param options.name - A descriptive name for the role.
   * @example "Billing Administrator"
   * @param options.description - An optional description of the role's purpose.
   * @example "Can manage billing and invoices"
   * @param options.resourceTypeSlug - The slug of the resource type the role is scoped to.
   * @example "organization"
   * @returns {Promise<OrganizationRole>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async createOrganizationRole(
    options: CreateOrganizationRoleOptions,
  ): Promise<OrganizationRole> {
    const { organizationId, ...payload } = options;
    const { data } = await this.workos.post<
      OrganizationRoleResponse,
      CreateOrganizationRoleResponse
    >(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/roles`,
      serializeCreateOrganizationRole(payload),
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * Get a custom role
   *
   * Retrieve a role that applies to an organization by its slug. This can return either an environment role or a custom role.
   * @param options - The request options.
   * @param options.organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug of the role.
   * @example "org-billing-admin"
   * @returns {Promise<OrganizationRole>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async getOrganizationRole(
    options: GetOrganizationRoleOptions,
  ): Promise<OrganizationRole> {
    const { organizationId, slug } = options;
    const { data } = await this.workos.get<OrganizationRoleResponse>(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/roles/${encodeURIComponent(slug)}`,
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * Update a custom role
   *
   * Update an existing custom role. Only the fields provided in the request body will be updated.
   * @param options - The request body.
   * @param options.organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug of the role.
   * @example "org-billing-admin"
   * @param options.name - A descriptive name for the role.
   * @example "Finance Administrator"
   * @param options.description - An optional description of the role's purpose.
   * @example "Can manage all financial operations"
   * @returns {Promise<OrganizationRole>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updateOrganizationRole(
    options: UpdateOrganizationRoleOptions,
  ): Promise<OrganizationRole> {
    const { organizationId, slug, ...payload } = options;
    const { data } = await this.workos.patch<
      OrganizationRoleResponse,
      UpdateOrganizationRoleResponse
    >(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/roles/${encodeURIComponent(slug)}`,
      serializeUpdateOrganizationRole(payload),
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * Delete a custom role
   *
   * Delete an existing custom role.
   * @param options - The request options.
   * @param options.organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug of the role.
   * @example "org-admin"
   * @returns {Promise<void>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   */
  async deleteOrganizationRole(
    options: DeleteOrganizationRoleOptions,
  ): Promise<void> {
    const { organizationId, slug } = options;
    await this.workos.delete(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/roles/${encodeURIComponent(slug)}`,
    );
  }

  /**
   * Add a permission to a custom role
   *
   * Add a single permission to a custom role. If the permission is already assigned to the role, this operation has no effect.
   * @param options - Object containing slug.
   * @param options.organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug of the role.
   * @example "org-admin"
   * @param options.slug - The slug of the permission to add to the role.
   * @example "reports:export"
   * @returns {Promise<OrganizationRole>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async addOrganizationRolePermission(
    options: AddOrganizationRolePermissionOptions,
  ): Promise<OrganizationRole> {
    const { organizationId, roleSlug, ...payload } = options;
    const { data } = await this.workos.post<
      OrganizationRoleResponse,
      AddRolePermissionResponse
    >(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/roles/${encodeURIComponent(roleSlug)}/permissions`,
      serializeAddRolePermission(payload),
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * Set permissions for a custom role
   *
   * Replace all permissions on a custom role with the provided list.
   * @param options - Object containing permissions.
   * @param options.organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug of the role.
   * @example "org-admin"
   * @param options.permissions - The permission slugs to assign to the role.
   * @example ["billing:read","billing:write","invoices:manage","reports:view"]
   * @returns {Promise<OrganizationRole>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async setOrganizationRolePermissions(
    options: SetOrganizationRolePermissionsOptions,
  ): Promise<OrganizationRole> {
    const { organizationId, slug, ...payload } = options;
    const { data } = await this.workos.put<
      OrganizationRoleResponse,
      SetRolePermissionsResponse
    >(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/roles/${encodeURIComponent(slug)}/permissions`,
      serializeSetRolePermissions(payload),
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * Remove a permission from a custom role
   *
   * Remove a single permission from a custom role by its slug.
   * @param options - The request options.
   * @param options.organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug of the role.
   * @example "org-admin"
   * @param options.permissionSlug - The slug of the permission to remove.
   * @example "documents:read"
   * @returns {Promise<OrganizationRole>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async removeOrganizationRolePermission(
    options: RemoveOrganizationRolePermissionOptions,
  ): Promise<void> {
    const { organizationId, slug, permissionSlug } = options;
    await this.workos.delete(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/roles/${encodeURIComponent(slug)}/permissions/${encodeURIComponent(permissionSlug)}`,
    );
  }

  /**
   * Get a resource by external ID
   *
   * Retrieve the details of an authorization resource by its external ID, organization, and resource type. This is useful when you only have the external ID from your system and need to fetch the full resource details.
   * @param options - The request options.
   * @param options.organizationId - The ID of the organization that owns the resource.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.resourceTypeSlug - The slug of the resource type.
   * @example "project"
   * @param options.externalId - An identifier you provide to reference the resource in your system.
   * @example "proj-456"
   * @returns {Promise<AuthorizationResource>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async getResourceByExternalId(
    options: GetAuthorizationResourceByExternalIdOptions,
  ): Promise<AuthorizationResource> {
    const { organizationId, resourceTypeSlug, externalId } = options;
    const { data } = await this.workos.get<AuthorizationResourceResponse>(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}`,
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Update a resource by external ID
   *
   * Update an existing authorization resource using its external ID.
   * @param options - The request body.
   * @param options.organizationId - The ID of the organization that owns the resource.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.resourceTypeSlug - The slug of the resource type.
   * @example "project"
   * @param options.externalId - An identifier you provide to reference the resource in your system.
   * @example "proj-456"
   * @param options.name - A display name for the resource.
   * @example "Updated Name"
   * @param options.description - An optional description of the resource.
   * @example "Updated description"
   * @param options.parentResourceId - The ID of the parent resource. Mutually exclusive with `parent_resource_external_id` and `parent_resource_type_slug`.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @param options.parentResourceExternalId - The external ID of the parent resource. Required with `parent_resource_type_slug`. Mutually exclusive with `parent_resource_id`.
   * @example "parent-workspace-01"
   * @param options.parentResourceTypeSlug - The resource type slug of the parent resource. Required with `parent_resource_external_id`. Mutually exclusive with `parent_resource_id`.
   * @example "workspace"
   * @returns {Promise<AuthorizationResource>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async updateResourceByExternalId(
    options: UpdateAuthorizationResourceByExternalIdOptions,
  ): Promise<AuthorizationResource> {
    const { organizationId, resourceTypeSlug, externalId, ...payload } =
      options;
    const { data } = await this.workos.patch<
      AuthorizationResourceResponse,
      UpdateAuthorizationResourceResponse
    >(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}`,
      serializeUpdateAuthorizationResource(payload),
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Delete an authorization resource by external ID
   *
   * Delete an authorization resource by organization, resource type, and external ID. This also deletes all descendant resources.
   * @param options - Additional query options.
   * @param options.organizationId - The ID of the organization that owns the resource.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.resourceTypeSlug - The slug of the resource type.
   * @example "project"
   * @param options.externalId - An identifier you provide to reference the resource in your system.
   * @example "proj-456"
   * @param options.cascadeDelete - If true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.
   * @default false
   * @example false
   * @returns {Promise<void>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   */
  async deleteResourceByExternalId(
    options: DeleteAuthorizationResourceByExternalIdOptions,
  ): Promise<void> {
    const { organizationId, resourceTypeSlug, externalId } = options;
    await this.workos.delete(
      `/authorization/organizations/${encodeURIComponent(organizationId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}`,
      {
        query: {
          ...(options.cascadeDelete !== undefined && {
            cascade_delete: options.cascadeDelete,
          }),
        },
      },
    );
  }

  /**
   * List memberships for a resource by external ID
   *
   * Returns all organization memberships that have a specific permission on a resource, using the resource's external ID. This is useful for answering "Who can access this resource?" when you only have the external ID.
   * @param options - Pagination and filter options.
   * @param options.organizationId - The ID of the organization that owns the resource.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.resourceTypeSlug - The slug of the resource type this resource belongs to.
   * @example "project"
   * @param options.externalId - An identifier you provide to reference the resource in your system.
   * @example "proj-456"
   * @returns {Promise<AutoPaginatable<AuthorizationOrganizationMembership, PaginationOptions>>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listMembershipsForResourceByExternalId(
    options: ListMembershipsForResourceByExternalIdOptions,
  ): Promise<
    AutoPaginatable<AuthorizationOrganizationMembership, PaginationOptions>
  > {
    const { organizationId, resourceTypeSlug, externalId } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<
        AuthorizationOrganizationMembershipResponse,
        AuthorizationOrganizationMembership
      >(
        this.workos,
        `/authorization/organizations/${encodeURIComponent(organizationId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}/organization_memberships`,
        deserializeAuthorizationOrganizationMembership,
        options
          ? serializeListMembershipsForResourceByExternalIdOptions(options)
          : undefined,
      ),
      (params) =>
        fetchAndDeserialize<
          AuthorizationOrganizationMembershipResponse,
          AuthorizationOrganizationMembership
        >(
          this.workos,
          `/authorization/organizations/${encodeURIComponent(organizationId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}/organization_memberships`,
          deserializeAuthorizationOrganizationMembership,
          params,
        ),
      options
        ? serializeListMembershipsForResourceByExternalIdOptions(options)
        : undefined,
    );
  }

  /**
   * List role assignments for a resource by external ID
   *
   * List all role assignments granted on a resource, identified by its external ID. Each assignment includes the organization membership it was granted to.
   * @param options - Pagination and filter options.
   * @param options.organizationId - The ID of the organization that owns the resource.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.resourceTypeSlug - The slug of the resource type.
   * @example "project"
   * @param options.externalId - An identifier you provide to reference the resource in your system.
   * @example "proj-456"
   * @returns {Promise<AutoPaginatable<RoleAssignment, PaginationOptions>>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async listResourceRoleAssignments(
    options: ListRoleAssignmentsForResourceByExternalIdOptions,
  ): Promise<AutoPaginatable<RoleAssignment, PaginationOptions>> {
    const { organizationId, resourceTypeSlug, externalId } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<RoleAssignmentResponse, RoleAssignment>(
        this.workos,
        `/authorization/organizations/${encodeURIComponent(organizationId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}/role_assignments`,
        deserializeRoleAssignment,
        options
          ? serializeListRoleAssignmentsForResourceByExternalIdOptions(options)
          : undefined,
      ),
      (params) =>
        fetchAndDeserialize<RoleAssignmentResponse, RoleAssignment>(
          this.workos,
          `/authorization/organizations/${encodeURIComponent(organizationId)}/resources/${encodeURIComponent(resourceTypeSlug)}/${encodeURIComponent(externalId)}/role_assignments`,
          deserializeRoleAssignment,
          params,
        ),
      options
        ? serializeListRoleAssignmentsForResourceByExternalIdOptions(options)
        : undefined,
    );
  }

  /**
   * List resources
   *
   * Get a paginated list of authorization resources.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<AuthorizationResource, PaginationOptions>>}
   * @throws {AuthorizationException} 403
   * @throws {UnprocessableEntityException} 422
   */
  async listResources(
    options?: ListAuthorizationResourcesOptions,
  ): Promise<AutoPaginatable<AuthorizationResource, PaginationOptions>> {
    return new AutoPaginatable(
      await fetchAndDeserialize<
        AuthorizationResourceResponse,
        AuthorizationResource
      >(
        this.workos,
        '/authorization/resources',
        deserializeAuthorizationResource,
        options
          ? serializeListAuthorizationResourcesOptions(options)
          : undefined,
      ),
      (params) =>
        fetchAndDeserialize<
          AuthorizationResourceResponse,
          AuthorizationResource
        >(
          this.workos,
          '/authorization/resources',
          deserializeAuthorizationResource,
          params,
        ),
      options ? serializeListAuthorizationResourcesOptions(options) : undefined,
    );
  }

  /**
   * Create an authorization resource
   *
   * Create a new authorization resource.
   * @param options - Object containing externalId, name, resourceTypeSlug, organizationId.
   * @param options.externalId - An external identifier for the resource.
   * @example "my-workspace-01"
   * @param options.name - A display name for the resource.
   * @example "Acme Workspace"
   * @param options.description - An optional description of the resource.
   * @example "Primary workspace for the Acme team"
   * @param options.resourceTypeSlug - The slug of the resource type.
   * @example "workspace"
   * @param options.organizationId - The ID of the organization this resource belongs to.
   * @example "org_01EHQMYV6MBK39QC5PZXHY59C3"
   * @param options.parentResourceId - The ID of the parent resource. Mutually exclusive with `parent_resource_external_id` and `parent_resource_type_slug`.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @param options.parentResourceExternalId - The external ID of the parent resource. Required with `parent_resource_type_slug`. Mutually exclusive with `parent_resource_id`.
   * @example "parent-workspace-01"
   * @param options.parentResourceTypeSlug - The resource type slug of the parent resource. Required with `parent_resource_external_id`. Mutually exclusive with `parent_resource_id`.
   * @example "workspace"
   * @returns {Promise<AuthorizationResource>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async createResource(
    options: CreateResourceOptions,
  ): Promise<AuthorizationResource> {
    const payload = options;
    const { data } = await this.workos.post<
      AuthorizationResourceResponse,
      CreateAuthorizationResourceResponse
    >(
      '/authorization/resources',
      serializeCreateAuthorizationResource(payload),
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Get a resource
   *
   * Retrieve the details of an authorization resource by its ID.
   * @param options - The request options.
   * @param options.resourceId - The ID of the authorization resource.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<AuthorizationResource>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async getResource(
    options: GetResourceOptions,
  ): Promise<AuthorizationResource> {
    const { resourceId } = options;
    const { data } = await this.workos.get<AuthorizationResourceResponse>(
      `/authorization/resources/${encodeURIComponent(resourceId)}`,
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Update a resource
   *
   * Update an existing authorization resource.
   * @param options - The request body.
   * @param options.resourceId - The ID of the authorization resource.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @param options.name - A display name for the resource.
   * @example "Updated Name"
   * @param options.description - An optional description of the resource.
   * @example "Updated description"
   * @param options.parentResourceId - The ID of the parent resource. Mutually exclusive with `parent_resource_external_id` and `parent_resource_type_slug`.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @param options.parentResourceExternalId - The external ID of the parent resource. Required with `parent_resource_type_slug`. Mutually exclusive with `parent_resource_id`.
   * @example "parent-workspace-01"
   * @param options.parentResourceTypeSlug - The resource type slug of the parent resource. Required with `parent_resource_external_id`. Mutually exclusive with `parent_resource_id`.
   * @example "workspace"
   * @returns {Promise<AuthorizationResource>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async updateResource(
    options: UpdateAuthorizationResourceOptions,
  ): Promise<AuthorizationResource> {
    const { resourceId, ...payload } = options;
    const { data } = await this.workos.patch<
      AuthorizationResourceResponse,
      UpdateAuthorizationResourceResponse
    >(
      `/authorization/resources/${encodeURIComponent(resourceId)}`,
      serializeUpdateAuthorizationResource(payload),
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Delete an authorization resource
   *
   * Delete an authorization resource and all its descendants.
   * @param options - Additional query options.
   * @param options.resourceId - The ID of the authorization resource.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @param options.cascadeDelete - If true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.
   * @default false
   * @example false
   * @returns {Promise<void>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   */
  async deleteResource(
    options: DeleteAuthorizationResourceOptions,
  ): Promise<void> {
    const { resourceId } = options;
    await this.workos.delete(
      `/authorization/resources/${encodeURIComponent(resourceId)}`,
      {
        query: {
          ...(options.cascadeDelete !== undefined && {
            cascade_delete: options.cascadeDelete,
          }),
        },
      },
    );
  }

  /**
   * List organization memberships for resource
   *
   * Returns all organization memberships that have a specific permission on a resource instance. This is useful for answering "Who can access this resource?".
   * @param options - Pagination and filter options.
   * @param options.resourceId - The ID of the authorization resource.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<AutoPaginatable<AuthorizationOrganizationMembership, PaginationOptions>>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listMembershipsForResource(
    options: ListMembershipsForResourceOptions,
  ): Promise<
    AutoPaginatable<AuthorizationOrganizationMembership, PaginationOptions>
  > {
    const { resourceId } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<
        AuthorizationOrganizationMembershipResponse,
        AuthorizationOrganizationMembership
      >(
        this.workos,
        `/authorization/resources/${encodeURIComponent(resourceId)}/organization_memberships`,
        deserializeAuthorizationOrganizationMembership,
        options
          ? serializeListMembershipsForResourceOptions(options)
          : undefined,
      ),
      (params) =>
        fetchAndDeserialize<
          AuthorizationOrganizationMembershipResponse,
          AuthorizationOrganizationMembership
        >(
          this.workos,
          `/authorization/resources/${encodeURIComponent(resourceId)}/organization_memberships`,
          deserializeAuthorizationOrganizationMembership,
          params,
        ),
      options ? serializeListMembershipsForResourceOptions(options) : undefined,
    );
  }

  /**
   * List role assignments for a resource
   *
   * List all role assignments granted on a specific resource instance. Each assignment includes the organization membership it was granted to.
   * @param options - Pagination and filter options.
   * @param options.resourceId - The ID of the authorization resource.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<AutoPaginatable<RoleAssignment, PaginationOptions>>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async listRoleAssignmentsForResource(
    options: ListRoleAssignmentsForResourceOptions,
  ): Promise<AutoPaginatable<RoleAssignment, PaginationOptions>> {
    const { resourceId } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<RoleAssignmentResponse, RoleAssignment>(
        this.workos,
        `/authorization/resources/${encodeURIComponent(resourceId)}/role_assignments`,
        deserializeRoleAssignment,
        options
          ? serializeListRoleAssignmentsForResourceOptions(options)
          : undefined,
      ),
      (params) =>
        fetchAndDeserialize<RoleAssignmentResponse, RoleAssignment>(
          this.workos,
          `/authorization/resources/${encodeURIComponent(resourceId)}/role_assignments`,
          deserializeRoleAssignment,
          params,
        ),
      options
        ? serializeListRoleAssignmentsForResourceOptions(options)
        : undefined,
    );
  }

  /**
   * List environment roles
   *
   * List all environment roles in priority order.
   * @returns {Promise<RoleList>}
   * @throws {AuthorizationException} 403
   */
  async listEnvironmentRoles(): Promise<RoleList> {
    const { data } = await this.workos.get<RoleListResponse>(
      '/authorization/roles',
    );
    return deserializeRoleList(data);
  }

  /**
   * Create an environment role
   *
   * Create a new environment role.
   * @param options - Object containing slug, name.
   * @param options.slug - A unique slug for the role.
   * @example "editor"
   * @param options.name - A descriptive name for the role.
   * @example "Editor"
   * @param options.description - An optional description of the role.
   * @example "Can edit resources"
   * @param options.resourceTypeSlug - The slug of the resource type the role is scoped to.
   * @example "organization"
   * @returns {Promise<EnvironmentRole>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async createEnvironmentRole(
    options: CreateEnvironmentRoleOptions,
  ): Promise<EnvironmentRole> {
    const payload = options;
    const { data } = await this.workos.post<
      EnvironmentRoleResponse,
      CreateRoleResponse
    >('/authorization/roles', serializeCreateRole(payload));
    return deserializeEnvironmentRole(data);
  }

  /**
   * Get an environment role
   *
   * Get an environment role by its slug.
   * @param options - The request options.
   * @param options.slug - The slug of the environment role.
   * @example "admin"
   * @returns {Promise<EnvironmentRole>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async getEnvironmentRole(
    options: GetEnvironmentRoleOptions,
  ): Promise<EnvironmentRole> {
    const { slug } = options;
    const { data } = await this.workos.get<EnvironmentRoleResponse>(
      `/authorization/roles/${encodeURIComponent(slug)}`,
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * Update an environment role
   *
   * Update an existing environment role.
   * @param options - The request body.
   * @param options.slug - The slug of the environment role.
   * @example "admin"
   * @param options.name - A descriptive name for the role.
   * @example "Super Administrator"
   * @param options.description - An optional description of the role.
   * @example "Full administrative access to all resources"
   * @returns {Promise<EnvironmentRole>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updateEnvironmentRole(
    options: UpdateEnvironmentRoleOptions,
  ): Promise<EnvironmentRole> {
    const { slug, ...payload } = options;
    const { data } = await this.workos.patch<
      EnvironmentRoleResponse,
      UpdateRoleResponse
    >(
      `/authorization/roles/${encodeURIComponent(slug)}`,
      serializeUpdateRole(payload),
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * Add a permission to an environment role
   *
   * Add a single permission to an environment role. If the permission is already assigned to the role, this operation has no effect.
   * @param options - Object containing slug.
   * @param options.slug - The slug of the environment role.
   * @example "admin"
   * @param options.slug - The slug of the permission to add to the role.
   * @example "reports:export"
   * @returns {Promise<EnvironmentRole>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async addEnvironmentRolePermission(
    options: AddEnvironmentRolePermissionOptions,
  ): Promise<EnvironmentRole> {
    const { roleSlug, ...payload } = options;
    const { data } = await this.workos.post<
      EnvironmentRoleResponse,
      AddRolePermissionResponse
    >(
      `/authorization/roles/${encodeURIComponent(roleSlug)}/permissions`,
      serializeAddRolePermission(payload),
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * Set permissions for an environment role
   *
   * Replace all permissions on an environment role with the provided list.
   * @param options - Object containing permissions.
   * @param options.slug - The slug of the environment role.
   * @example "admin"
   * @param options.permissions - The permission slugs to assign to the role.
   * @example ["billing:read","billing:write","invoices:manage","reports:view"]
   * @returns {Promise<EnvironmentRole>}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async setEnvironmentRolePermissions(
    options: SetEnvironmentRolePermissionsOptions,
  ): Promise<EnvironmentRole> {
    const { slug, ...payload } = options;
    const { data } = await this.workos.put<
      EnvironmentRoleResponse,
      SetRolePermissionsResponse
    >(
      `/authorization/roles/${encodeURIComponent(slug)}/permissions`,
      serializeSetRolePermissions(payload),
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * List permissions
   *
   * Get a list of all permissions in your WorkOS environment.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<Permission, PaginationOptions>>}
   * @throws {NotFoundException} 404
   */
  async listPermissions(
    options?: PaginationOptions,
  ): Promise<AutoPaginatable<Permission, PaginationOptions>> {
    const paginationOptions = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<PermissionResponse, Permission>(
        this.workos,
        '/authorization/permissions',
        deserializePermission,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<PermissionResponse, Permission>(
          this.workos,
          '/authorization/permissions',
          deserializePermission,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * Create a permission
   *
   * Create a new permission in your WorkOS environment. The permission can then be assigned to environment roles and custom roles.
   * @param options - Object containing slug, name.
   * @param options.slug - A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
   * @example "documents:read"
   * @param options.name - A descriptive name for the Permission.
   * @example "View Documents"
   * @param options.description - An optional description of the Permission.
   * @example "Allows viewing document contents"
   * @param options.resourceTypeSlug - The slug of the resource type this permission is scoped to.
   * @example "document"
   * @returns {Promise<Permission>}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async createPermission(
    options: CreatePermissionOptions,
  ): Promise<Permission> {
    const payload = options;
    const { data } = await this.workos.post<
      PermissionResponse,
      CreateAuthorizationPermissionResponse
    >(
      '/authorization/permissions',
      serializeCreateAuthorizationPermission(payload),
    );
    return deserializePermission(data);
  }

  /**
   * Get a permission
   *
   * Retrieve a permission by its unique slug.
   * @param options - The request options.
   * @param options.slug - A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
   * @example "documents:read"
   * @returns {Promise<AuthorizationPermission>}
   * @throws {NotFoundException} 404
   */
  async getPermission(
    options: GetPermissionOptions,
  ): Promise<AuthorizationPermission> {
    const { slug } = options;
    const { data } = await this.workos.get<AuthorizationPermissionResponse>(
      `/authorization/permissions/${encodeURIComponent(slug)}`,
    );
    return deserializeAuthorizationPermission(data);
  }

  /**
   * Update a permission
   *
   * Update an existing permission. Only the fields provided in the request body will be updated.
   * @param options - The request body.
   * @param options.slug - A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
   * @example "documents:read"
   * @param options.name - A descriptive name for the Permission.
   * @example "View Documents"
   * @param options.description - An optional description of the Permission.
   * @example "Allows viewing document contents"
   * @returns {Promise<AuthorizationPermission>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updatePermission(
    options: UpdatePermissionOptions,
  ): Promise<AuthorizationPermission> {
    const { slug, ...payload } = options;
    const { data } = await this.workos.patch<
      AuthorizationPermissionResponse,
      UpdateAuthorizationPermissionResponse
    >(
      `/authorization/permissions/${encodeURIComponent(slug)}`,
      serializeUpdateAuthorizationPermission(payload),
    );
    return deserializeAuthorizationPermission(data);
  }

  /**
   * Delete a permission
   *
   * Delete an existing permission. System permissions cannot be deleted.
   * @param options - The request options.
   * @param options.slug - A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
   * @example "documents:read"
   * @returns {Promise<void>}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async deletePermission(options: DeletePermissionOptions): Promise<void> {
    const { slug } = options;
    await this.workos.delete(
      `/authorization/permissions/${encodeURIComponent(slug)}`,
    );
  }
}
