// This file is auto-generated by oagen. Do not edit.

import { WorkOS } from '../workos';
import {
  Role,
  RoleList,
  OrganizationRoleResponse,
  ListOrganizationRolesResponse,
} from '../roles/interfaces';
import {
  EnvironmentRole,
  EnvironmentRoleResponse,
  EnvironmentRoleList,
  EnvironmentRoleListResponse,
  CreateEnvironmentRoleOptions,
  UpdateEnvironmentRoleOptions,
  SetEnvironmentRolePermissionsOptions,
  AddEnvironmentRolePermissionOptions,
  OrganizationRole,
  CreateOrganizationRoleOptions,
  UpdateOrganizationRoleOptions,
  SetOrganizationRolePermissionsOptions,
  AddOrganizationRolePermissionOptions,
  RemoveOrganizationRolePermissionOptions,
  Permission,
  PermissionResponse,
  PermissionList,
  PermissionListResponse,
  CreatePermissionOptions,
  UpdatePermissionOptions,
  ListPermissionsOptions,
  AuthorizationResource,
  AuthorizationResourceResponse,
  AuthorizationResourceList,
  AuthorizationResourceListResponse,
  ListAuthorizationResourcesOptions,
  GetAuthorizationResourceByExternalIdOptions,
  UpdateAuthorizationResourceByExternalIdOptions,
  DeleteAuthorizationResourceByExternalIdOptions,
  DeleteAuthorizationResourceOptions,
  CreateAuthorizationResourceOptions,
  UpdateAuthorizationResourceOptions,
  AuthorizationCheckOptions,
  AuthorizationCheckResult,
  AssignRoleOptions,
  ListRoleAssignmentsOptions,
  RemoveRoleAssignmentOptions,
  RemoveRoleOptions,
  RoleAssignment,
  RoleAssignmentList,
  RoleAssignmentListResponse,
  RoleAssignmentResponse,
  ListMembershipsForResourceByExternalIdOptions,
  ListMembershipsForResourceOptions,
  ListResourcesForMembershipOptions,
} from './interfaces';
import {
  deserializeEnvironmentRole,
  serializeCreateEnvironmentRoleOptions,
  serializeUpdateEnvironmentRoleOptions,
  deserializeRole,
  deserializeOrganizationRole,
  serializeCreateOrganizationRoleOptions,
  serializeUpdateOrganizationRoleOptions,
  deserializePermission,
  serializeCreatePermissionOptions,
  serializeUpdatePermissionOptions,
  deserializeAuthorizationResource,
  serializeCreateResourceOptions,
  serializeUpdateResourceOptions,
  serializeUpdateResourceByExternalIdOptions,
  serializeListAuthorizationResourcesOptions,
  serializeAuthorizationCheckOptions,
  deserializeRoleAssignment,
  serializeAssignRoleOptions,
  serializeRemoveRoleOptions,
  serializeListMembershipsForResourceOptions,
  serializeListResourcesForMembershipOptions,
} from './serializers';
import {
  AuthorizationOrganizationMembershipList,
  AuthorizationOrganizationMembershipListResponse,
} from '../user-management/interfaces/organization-membership.interface';
import { deserializeAuthorizationOrganizationMembership } from '../user-management/serializers/organization-membership.serializer';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';

export class Authorization {
  constructor(private readonly workos: WorkOS) {}

  /**
   * List environment roles
   *
   * List all environment roles in priority order.
   * @returns {RoleList}
   */
  async createEnvironmentRole(
    options: CreateEnvironmentRoleOptions,
  ): Promise<EnvironmentRole> {
    const { data } = await this.workos.post<EnvironmentRoleResponse>(
      '/authorization/roles',
      serializeCreateEnvironmentRoleOptions(options),
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * Create an environment role
   *
   * Create a new environment role.
   * @param payload - Object containing slug, name.
   * @returns {Role}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async listEnvironmentRoles(): Promise<EnvironmentRoleList> {
    const { data } = await this.workos.get<EnvironmentRoleListResponse>(
      '/authorization/roles',
    );
    return {
      object: 'list',
      data: data.data.map(deserializeEnvironmentRole),
    };
  }

  /**
   * Get an environment role
   *
   * Get an environment role by its slug.
   * @param slug - The slug of the environment role.
   * @example "admin"
   * @returns {Role}
   * @throws {NotFoundException} 404
   */
  async getEnvironmentRole(slug: string): Promise<EnvironmentRole> {
    const { data } = await this.workos.get<EnvironmentRoleResponse>(
      `/authorization/roles/${slug}`,
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * Update an environment role
   *
   * Update an existing environment role.
   * @param slug - The slug of the environment role.
   * @example "admin"
   * @param payload - The request body.
   * @returns {Role}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updateEnvironmentRole(
    slug: string,
    options: UpdateEnvironmentRoleOptions,
  ): Promise<EnvironmentRole> {
    const { data } = await this.workos.patch<EnvironmentRoleResponse>(
      `/authorization/roles/${slug}`,
      serializeUpdateEnvironmentRoleOptions(options),
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * Add a permission to an environment role
   *
   * Add a single permission to an environment role. If the permission is already assigned to the role, this operation has no effect.
   * @param slug - The slug of the environment role.
   * @example "admin"
   * @param payload - Object containing slug.
   * @returns {Role}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async setEnvironmentRolePermissions(
    slug: string,
    options: SetEnvironmentRolePermissionsOptions,
  ): Promise<EnvironmentRole> {
    const { data } = await this.workos.put<EnvironmentRoleResponse>(
      `/authorization/roles/${slug}/permissions`,
      { permissions: options.permissions },
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * Set permissions for an environment role
   *
   * Replace all permissions on an environment role with the provided list.
   * @param slug - The slug of the environment role.
   * @example "admin"
   * @param payload - Object containing permissions.
   * @returns {Role}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async addEnvironmentRolePermission(
    slug: string,
    options: AddEnvironmentRolePermissionOptions,
  ): Promise<EnvironmentRole> {
    const { data } = await this.workos.post<EnvironmentRoleResponse>(
      `/authorization/roles/${slug}/permissions`,
      { slug: options.permissionSlug },
    );
    return deserializeEnvironmentRole(data);
  }

  /**
   * Create a custom organization role
   *
   * Create a new custom organization role.
   * @param organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param payload - Object containing slug, name.
   * @returns {Role}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async createOrganizationRole(
    organizationId: string,
    options: CreateOrganizationRoleOptions,
  ): Promise<OrganizationRole> {
    const { data } = await this.workos.post<OrganizationRoleResponse>(
      `/authorization/organizations/${organizationId}/roles`,
      serializeCreateOrganizationRoleOptions(options),
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * List organization roles
   *
   * Get a list of all roles that apply to an organization. This includes both environment roles and organization-specific roles, returned in priority order.
   * @param organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<AuthorizationOrganizationRolesListItem>}
   * @throws {NotFoundException} 404
   */
  async listOrganizationRoles(organizationId: string): Promise<RoleList> {
    const { data } = await this.workos.get<ListOrganizationRolesResponse>(
      `/authorization/organizations/${organizationId}/roles`,
    );
    return {
      object: 'list',
      data: data.data.map(deserializeRole),
    };
  }

  /**
   * Get an organization role
   *
   * Retrieve a role that applies to an organization by its slug. This can return either an environment role or an organization-specific role.
   * @param organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param slug - The slug of the role.
   * @example "org-billing-admin"
   * @returns {Role}
   * @throws {NotFoundException} 404
   */
  async getOrganizationRole(
    organizationId: string,
    slug: string,
  ): Promise<Role> {
    const { data } = await this.workos.get<OrganizationRoleResponse>(
      `/authorization/organizations/${organizationId}/roles/${slug}`,
    );
    return deserializeRole(data);
  }

  /**
   * Update an organization role
   *
   * Update an existing custom organization role. Only the fields provided in the request body will be updated.
   * @param organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param slug - The slug of the role.
   * @example "org-billing-admin"
   * @param payload - The request body.
   * @returns {Role}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updateOrganizationRole(
    organizationId: string,
    slug: string,
    options: UpdateOrganizationRoleOptions,
  ): Promise<OrganizationRole> {
    const { data } = await this.workos.patch<OrganizationRoleResponse>(
      `/authorization/organizations/${organizationId}/roles/${slug}`,
      serializeUpdateOrganizationRoleOptions(options),
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * Delete a custom organization role
   *
   * Delete an existing custom organization role.
   * @param organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param slug - The slug of the role.
   * @example "org-admin"
   * @returns {void}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   */
  async deleteOrganizationRole(
    organizationId: string,
    slug: string,
  ): Promise<void> {
    await this.workos.delete(
      `/authorization/organizations/${organizationId}/roles/${slug}`,
    );
  }

  /**
   * Set permissions for a role
   *
   * Replace all permissions on a role with the provided list.
   * @param organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param slug - The slug of the role.
   * @example "org-admin"
   * @param payload - Object containing permissions.
   * @returns {Role}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async setOrganizationRolePermissions(
    organizationId: string,
    slug: string,
    options: SetOrganizationRolePermissionsOptions,
  ): Promise<OrganizationRole> {
    const { data } = await this.workos.put<OrganizationRoleResponse>(
      `/authorization/organizations/${organizationId}/roles/${slug}/permissions`,
      { permissions: options.permissions },
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * Add a permission to an organization role
   *
   * Add a single permission to an organization role. If the permission is already assigned to the role, this operation has no effect.
   * @param organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param slug - The slug of the role.
   * @example "org-admin"
   * @param payload - Object containing slug.
   * @returns {Role}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async addOrganizationRolePermission(
    organizationId: string,
    slug: string,
    options: AddOrganizationRolePermissionOptions,
  ): Promise<OrganizationRole> {
    const { data } = await this.workos.post<OrganizationRoleResponse>(
      `/authorization/organizations/${organizationId}/roles/${slug}/permissions`,
      { slug: options.permissionSlug },
    );
    return deserializeOrganizationRole(data);
  }

  /**
   * Remove a permission from an organization role
   *
   * Remove a single permission from an organization role by its slug.
   * @param organizationId - The ID of the organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param slug - The slug of the role.
   * @example "org-admin"
   * @returns {void}
   * @throws {NotFoundException} 404
   */
  async removeOrganizationRolePermission(
    organizationId: string,
    slug: string,
    options: RemoveOrganizationRolePermissionOptions,
  ): Promise<void> {
    await this.workos.delete(
      `/authorization/organizations/${organizationId}/roles/${slug}/permissions/${options.permissionSlug}`,
    );
  }

  /** @deprecated Use `workos.permissions.create()` instead. */
  async createPermission(
    options: CreatePermissionOptions,
  ): Promise<Permission> {
    const { data } = await this.workos.post<PermissionResponse>(
      '/authorization/permissions',
      serializeCreatePermissionOptions(options),
    );
    return deserializePermission(data);
  }

  /** @deprecated Use `workos.permissions.list()` instead. */
  async listPermissions(
    options?: ListPermissionsOptions,
  ): Promise<PermissionList> {
    const { data } = await this.workos.get<PermissionListResponse>(
      '/authorization/permissions',
      { query: options },
    );
    return {
      object: 'list',
      data: data.data.map(deserializePermission),
      listMetadata: {
        before: data.list_metadata.before,
        after: data.list_metadata.after,
      },
    };
  }

  /** @deprecated Use `workos.permissions.find()` instead. */
  async getPermission(slug: string): Promise<Permission> {
    const { data } = await this.workos.get<PermissionResponse>(
      `/authorization/permissions/${slug}`,
    );
    return deserializePermission(data);
  }

  /** @deprecated Use `workos.permissions.update()` instead. */
  async updatePermission(
    slug: string,
    options: UpdatePermissionOptions,
  ): Promise<Permission> {
    const { data } = await this.workos.patch<PermissionResponse>(
      `/authorization/permissions/${slug}`,
      serializeUpdatePermissionOptions(options),
    );
    return deserializePermission(data);
  }

  /** @deprecated Use `workos.permissions.delete()` instead. */
  async deletePermission(slug: string): Promise<void> {
    await this.workos.delete(`/authorization/permissions/${slug}`);
  }

  /**
   * Get a resource
   *
   * Retrieve the details of an authorization resource by its ID.
   * @param resourceId - The ID of the authorization resource.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @returns {AuthorizationResource}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async getResource(resourceId: string): Promise<AuthorizationResource> {
    const { data } = await this.workos.get<AuthorizationResourceResponse>(
      `/authorization/resources/${resourceId}`,
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Create an authorization resource
   *
   * Create a new authorization resource.
   * @param payload - Object containing externalId, name, resourceTypeSlug, organizationId.
   * @returns {AuthorizationResource}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async createResource(
    options: CreateAuthorizationResourceOptions,
  ): Promise<AuthorizationResource> {
    const { data } = await this.workos.post<AuthorizationResourceResponse>(
      '/authorization/resources',
      serializeCreateResourceOptions(options),
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Update a resource
   *
   * Update an existing authorization resource.
   * @param payload - The request body.
   * @returns {AuthorizationResource}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async updateResource(
    options: UpdateAuthorizationResourceOptions,
  ): Promise<AuthorizationResource> {
    const { data } = await this.workos.patch<AuthorizationResourceResponse>(
      `/authorization/resources/${options.resourceId}`,
      serializeUpdateResourceOptions(options),
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Delete an authorization resource
   *
   * Delete an authorization resource and all its descendants.
   * @param options.cascadeDelete - If true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.
   * @default false
   * @example false
   * @param options - Additional query options.
   * @returns {void}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   */
  async deleteResource(
    options: DeleteAuthorizationResourceOptions,
  ): Promise<void> {
    const { resourceId, cascadeDelete } = options;

    const query =
      cascadeDelete !== undefined
        ? { cascade_delete: cascadeDelete.toString() }
        : undefined;

    await this.workos.delete(`/authorization/resources/${resourceId}`, query);
  }

  /**
   * List resources
   *
   * Get a paginated list of authorization resources.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<AuthorizationResource>}
   * @throws {UnprocessableEntityException} 422
   */
  async listResources(
    options: ListAuthorizationResourcesOptions = {},
  ): Promise<AuthorizationResourceList> {
    const { data } = await this.workos.get<AuthorizationResourceListResponse>(
      '/authorization/resources',
      { query: serializeListAuthorizationResourcesOptions(options) },
    );
    return {
      object: 'list',
      data: data.data.map(deserializeAuthorizationResource),
      listMetadata: {
        before: data.list_metadata.before,
        after: data.list_metadata.after,
      },
    };
  }

  /**
   * Get a resource by external ID
   *
   * Retrieve the details of an authorization resource by its external ID, organization, and resource type. This is useful when you only have the external ID from your system and need to fetch the full resource details.
   * @returns {AuthorizationResource}
   * @throws {NotFoundException} 404
   */
  async getResourceByExternalId(
    options: GetAuthorizationResourceByExternalIdOptions,
  ): Promise<AuthorizationResource> {
    const { organizationId, resourceTypeSlug, externalId } = options;
    const { data } = await this.workos.get<AuthorizationResourceResponse>(
      `/authorization/organizations/${organizationId}/resources/${resourceTypeSlug}/${externalId}`,
    );
    return deserializeAuthorizationResource(data);
  }

  /**
   * Update a resource by external ID
   *
   * Update an existing authorization resource using its external ID.
   * @param payload - The request body.
   * @returns {AuthorizationResource}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async updateResourceByExternalId(
    options: UpdateAuthorizationResourceByExternalIdOptions,
  ): Promise<AuthorizationResource> {
    const { organizationId, resourceTypeSlug, externalId } = options;
    const { data } = await this.workos.patch<AuthorizationResourceResponse>(
      `/authorization/organizations/${organizationId}/resources/${resourceTypeSlug}/${externalId}`,
      serializeUpdateResourceByExternalIdOptions(options),
    );
    return deserializeAuthorizationResource(data);
  }
  /**
   * Delete an authorization resource by external ID
   *
   * Delete an authorization resource by organization, resource type, and external ID. This also deletes all descendant resources.
   * @param options.cascadeDelete - If true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.
   * @default false
   * @example false
   * @param options - Additional query options.
   * @returns {void}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   */
  async deleteResourceByExternalId(
    options: DeleteAuthorizationResourceByExternalIdOptions,
  ): Promise<void> {
    const { organizationId, resourceTypeSlug, externalId, cascadeDelete } =
      options;

    const query =
      cascadeDelete !== undefined
        ? { cascade_delete: cascadeDelete.toString() }
        : undefined;

    await this.workos.delete(
      `/authorization/organizations/${organizationId}/resources/${resourceTypeSlug}/${externalId}`,
      query,
    );
  }

  /**
   * Check authorization
   *
   * Check if an organization membership has a specific permission on a resource. Supports identification by resource_id OR by resource_external_id + resource_type_slug.
   * @param payload - Object containing permissionSlug.
   * @returns {AuthorizationCheck}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async check(
    options: AuthorizationCheckOptions,
  ): Promise<AuthorizationCheckResult> {
    const { data } = await this.workos.post<AuthorizationCheckResult>(
      `/authorization/organization_memberships/${options.organizationMembershipId}/check`,
      serializeAuthorizationCheckOptions(options),
    );
    return data;
  }

  /**
   * List role assignments
   *
   * List all role assignments for an organization membership. This returns all roles that have been assigned to the user on resources, including organization-level and sub-resource roles.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<RoleAssignment>}
   * @throws {NotFoundException} 404
   */
  async listRoleAssignments(
    options: ListRoleAssignmentsOptions,
  ): Promise<RoleAssignmentList> {
    const { organizationMembershipId, ...queryOptions } = options;
    const { data } = await this.workos.get<RoleAssignmentListResponse>(
      `/authorization/organization_memberships/${organizationMembershipId}/role_assignments`,
      { query: queryOptions },
    );
    return {
      object: 'list',
      data: data.data.map(deserializeRoleAssignment),
      listMetadata: {
        before: data.list_metadata.before,
        after: data.list_metadata.after,
      },
    };
  }

  /**
   * Assign a role
   *
   * Assign a role to an organization membership on a specific resource.
   * @param payload - Object containing roleSlug.
   * @returns {RoleAssignment}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async assignRole(options: AssignRoleOptions): Promise<RoleAssignment> {
    const { data } = await this.workos.post<RoleAssignmentResponse>(
      `/authorization/organization_memberships/${options.organizationMembershipId}/role_assignments`,
      serializeAssignRoleOptions(options),
    );
    return deserializeRoleAssignment(data);
  }

  /**
   * Remove a role assignment by ID
   *
   * Remove a role assignment using its ID.
   * @returns {void}
   * @throws {NotFoundException} 404
   */
  async removeRole(options: RemoveRoleOptions): Promise<void> {
    await this.workos.deleteWithBody(
      `/authorization/organization_memberships/${options.organizationMembershipId}/role_assignments`,
      serializeRemoveRoleOptions(options),
    );
  }

  /**
   * Remove a role assignment by ID
   *
   * Remove a role assignment using its ID.
   * @returns {void}
   * @throws {NotFoundException} 404
   */
  async removeRoleAssignment(
    options: RemoveRoleAssignmentOptions,
  ): Promise<void> {
    await this.workos.delete(
      `/authorization/organization_memberships/${options.organizationMembershipId}/role_assignments/${options.roleAssignmentId}`,
    );
  }

  /**
   * List resources for organization membership
   *
   * Returns all child resources of a parent resource where the organization membership has a specific permission. This is useful for resource discovery—answering "What projects can this user access in this workspace?"
   *
   * You must provide either `parent_resource_id` or both `parent_resource_external_id` and `parent_resource_type_slug` to identify the parent resource.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<AuthorizationResource>}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listResourcesForMembership(
    options: ListResourcesForMembershipOptions,
  ): Promise<AuthorizationResourceList> {
    const { organizationMembershipId } = options;
    const { data } = await this.workos.get<AuthorizationResourceListResponse>(
      `/authorization/organization_memberships/${organizationMembershipId}/resources`,
      {
        query: serializeListResourcesForMembershipOptions(options),
      },
    );
    return {
      object: 'list',
      data: data.data.map(deserializeAuthorizationResource),
      listMetadata: {
        before: data.list_metadata.before,
        after: data.list_metadata.after,
      },
    };
  }

  /**
   * List organization memberships for resource
   *
   * Returns all organization memberships that have a specific permission on a resource instance. This is useful for answering "Who can access this resource?".
   * @param resourceId - The ID of the authorization resource.
   * @example "authz_resource_01HXYZ123456789ABCDEFGHIJ"
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<UserOrganizationMembershipBaseListData>}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listMembershipsForResource(
    options: ListMembershipsForResourceOptions,
  ): Promise<AuthorizationOrganizationMembershipList> {
    const { resourceId } = options;
    const { data } =
      await this.workos.get<AuthorizationOrganizationMembershipListResponse>(
        `/authorization/resources/${resourceId}/organization_memberships`,
        {
          query: serializeListMembershipsForResourceOptions(options),
        },
      );
    return {
      object: 'list',
      data: data.data.map(deserializeAuthorizationOrganizationMembership),
      listMetadata: {
        before: data.list_metadata.before,
        after: data.list_metadata.after,
      },
    };
  }

  /**
   * List memberships for a resource by external ID
   *
   * Returns all organization memberships that have a specific permission on a resource, using the resource's external ID. This is useful for answering "Who can access this resource?" when you only have the external ID.
   * @param organizationId - The ID of the organization that owns the resource.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param resourceTypeSlug - The slug of the resource type this resource belongs to.
   * @example "project"
   * @param externalId - An identifier you provide to reference the resource in your system.
   * @example "proj-456"
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<UserOrganizationMembershipBaseListData>}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listMembershipsForResourceByExternalId(
    options: ListMembershipsForResourceByExternalIdOptions,
  ): Promise<AuthorizationOrganizationMembershipList> {
    const { organizationId, resourceTypeSlug, externalId } = options;
    const { data } =
      await this.workos.get<AuthorizationOrganizationMembershipListResponse>(
        `/authorization/organizations/${organizationId}/resources/${resourceTypeSlug}/${externalId}/organization_memberships`,
        {
          query: serializeListMembershipsForResourceOptions(options),
        },
      );
    return {
      object: 'list',
      data: data.data.map(deserializeAuthorizationOrganizationMembership),
      listMetadata: {
        before: data.list_metadata.before,
        after: data.list_metadata.after,
      },
    };
  }
}

export interface ListResourcesOptions extends PaginationOptions {
  /** Filter resources by organization ID. */
  organizationId?: string;
  /** Filter resources by resource type slug. */
  resourceTypeSlug?: string;
  /** Filter resources by parent resource ID. */
  parentResourceId?: string;
  /** Filter resources by parent resource type slug. */
  parentResourceTypeSlug?: string;
  /** Filter resources by parent external ID. */
  parentExternalId?: string;
  /** Search resources by name. */
  search?: string;
}

export interface ListOrganizationMembershipsForResourceByExternalIdOptions extends PaginationOptions {
  /** The permission slug to filter by. Only users with this permission on the resource are returned. */
  permissionSlug: string;
  /** Filter by assignment type. Use "direct" for direct assignments only, or "indirect" to include inherited assignments. */
  assignment?: 'direct' | 'indirect';
}

export interface ListOrganizationMembershipsForResourceOptions extends PaginationOptions {
  /** The permission slug to filter by. Only users with this permission on the resource are returned. */
  permissionSlug: string;
  /** Filter by assignment type. Use `direct` for direct assignments only, or `indirect` to include inherited assignments. */
  assignment?: 'direct' | 'indirect';
}
