// This file is auto-generated by oagen. Do not edit.

/** Counts of active and inactive directory users. */
export interface DirectoryMetadataUser {
  /** Count of active directory users. */
  active: number;
  /** Count of inactive directory users. */
  inactive: number;
}

export interface DirectoryMetadataUserResponse {
  active: number;
  inactive: number;
}
