// This file is auto-generated by oagen. Do not edit.

import type {
  IntentOptions,
  IntentOptionsResponse,
} from './intent-options.interface';
import type { GenerateLinkIntent } from '../../common/interfaces/generate-link-intent.interface';

export interface GenerateLink {
  /** The URL to go to when an admin clicks on your logo in the Admin Portal. If not specified, the return URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used. */
  returnUrl?: string;
  /** The URL to redirect the admin to when they finish setup. If not specified, the success URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used. */
  successUrl?: string;
  /** An [Organization](https://workos.com/docs/reference/organization) identifier. */
  organization: string;
  /**
   *
   *       The intent of the Admin Portal.
   *         - `sso` - Launch Admin Portal for creating SSO connections
   *         - `dsync` - Launch Admin Portal for creating Directory Sync connections
   *         - `audit_logs` - Launch Admin Portal for viewing Audit Logs
   *         - `log_streams` - Launch Admin Portal for creating Log Streams
   *         - `domain_verification` - Launch Admin Portal for Domain Verification
   *         - `certificate_renewal` - Launch Admin Portal for renewing SAML Certificates
   *         - `bring_your_own_key` - Launch Admin Portal for configuring Bring Your Own Key
   */
  intent?: GenerateLinkIntent;
  /** Options to configure the Admin Portal based on the intent. */
  intentOptions?: IntentOptions;
  /** The email addresses of the IT admins to grant access to the Admin Portal for the given organization. Accepts up to 20 emails. */
  adminEmails?: string[];
}

export interface GenerateLinkResponse {
  return_url?: string;
  success_url?: string;
  organization: string;
  intent?: GenerateLinkIntent;
  intent_options?: IntentOptionsResponse;
  admin_emails?: string[];
}
