// This file is auto-generated by oagen. Do not edit.

import type {
  SSOIntentOptions,
  SSOIntentOptionsResponse,
} from './sso-intent-options.interface';

export interface IntentOptions {
  /** SSO-specific options for the Admin Portal. */
  sso: SSOIntentOptions;
}

export interface IntentOptionsResponse {
  sso: SSOIntentOptionsResponse;
}
