// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import type { AutoPaginatable } from '../common/utils/pagination';
import { createPaginatedList } from '../common/utils/fetch-and-deserialize';
import type {
  WebhookEndpointJson,
  WebhookEndpointJsonResponse,
} from '../webhooks/interfaces/webhook-endpoint-json.interface';
import type { CreateWebhookEndpoint } from '../webhooks/interfaces/create-webhook-endpoint.interface';
import type { UpdateWebhookEndpoint } from '../webhooks/interfaces/update-webhook-endpoint.interface';
import { deserializeWebhookEndpointJson } from '../webhooks/serializers/webhook-endpoint-json.serializer';
import { serializeCreateWebhookEndpoint } from '../webhooks/serializers/create-webhook-endpoint.serializer';
import { serializeUpdateWebhookEndpoint } from '../webhooks/serializers/update-webhook-endpoint.serializer';

export class WebhooksEndpoints {
  constructor(private readonly workos: WorkOS) {}

  /**
   * List Webhook Endpoints
   *
   * Get a list of all of your existing webhook endpoints.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<WebhookEndpointJson, PaginationOptions>>}
   */
  async listWebhookEndpoints(
    options?: PaginationOptions,
  ): Promise<AutoPaginatable<WebhookEndpointJson, PaginationOptions>> {
    return createPaginatedList<
      WebhookEndpointJsonResponse,
      WebhookEndpointJson,
      PaginationOptions
    >(
      this.workos,
      '/webhook_endpoints',
      deserializeWebhookEndpointJson,
      options,
    );
  }

  /**
   * Create a Webhook Endpoint
   *
   * Create a new webhook endpoint to receive event notifications.
   * @param payload - Object containing endpointUrl, events.
   * @returns {Promise<WebhookEndpointJson>}
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async createWebhookEndpoints(
    payload: CreateWebhookEndpoint,
  ): Promise<WebhookEndpointJson> {
    const { data } = await this.workos.post<WebhookEndpointJsonResponse>(
      '/webhook_endpoints',
      serializeCreateWebhookEndpoint(payload),
    );
    return deserializeWebhookEndpointJson(data);
  }

  /**
   * Update a Webhook Endpoint
   *
   * Update the properties of an existing webhook endpoint.
   * @param id - Unique identifier of the Webhook Endpoint.
   * @example "we_0123456789"
   * @param payload - The request body.
   * @returns {Promise<WebhookEndpointJson>}
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async updateWebhookEndpoint(
    id: string,
    payload: UpdateWebhookEndpoint,
  ): Promise<WebhookEndpointJson> {
    const { data } = await this.workos.patch<WebhookEndpointJsonResponse>(
      `/webhook_endpoints/${id}`,
      serializeUpdateWebhookEndpoint(payload),
    );
    return deserializeWebhookEndpointJson(data);
  }

  /**
   * Delete a Webhook Endpoint
   *
   * Delete an existing webhook endpoint.
   * @param id - Unique identifier of the Webhook Endpoint.
   * @example "we_0123456789"
   * @returns {Promise<void>}
   * @throws {NotFoundException} 404
   */
  async deleteWebhookEndpoint(id: string): Promise<void> {
    await this.workos.delete(`/webhook_endpoints/${id}`);
  }
}
