// This file is auto-generated by oagen. Do not edit.

export interface CreateCorsOrigin {
  /** The origin URL to allow for CORS requests. */
  origin: string;
}

export interface CreateCorsOriginResponse {
  origin: string;
}
