// This file is auto-generated by oagen. Do not edit.

export interface DeviceAuthorizationResponse {
  /** The device verification code. */
  deviceCode: string;
  /** The end-user verification code. */
  userCode: string;
  /** The end-user verification URI. */
  verificationUri: string;
  /** Verification URI that includes the user code. */
  verificationUriComplete?: string;
  /** Lifetime in seconds of the codes. */
  expiresIn: number;
  /** Minimum polling interval in seconds. */
  interval?: number;
}

export interface DeviceAuthorizationResponseWire {
  device_code: string;
  user_code: string;
  verification_uri: string;
  verification_uri_complete?: string;
  expires_in: number;
  interval?: number;
}
