// This file is auto-generated by oagen. Do not edit.

import type { User, UserResponse } from './user.interface';

export type EmailChangeConfirmationUser = User;
export type EmailChangeConfirmationUserResponse = UserResponse;
