// This file is auto-generated by oagen. Do not edit.

import type {
  EmailChangeConfirmationUser,
  EmailChangeConfirmationUserResponse,
} from './email-change-confirmation-user.interface';

export interface EmailChangeConfirmation {
  /** Distinguishes the email change confirmation object. */
  object: 'email_change_confirmation';
  /** The user object. */
  user: EmailChangeConfirmationUser;
}

export interface EmailChangeConfirmationResponse {
  object: 'email_change_confirmation';
  user: EmailChangeConfirmationUserResponse;
}
