// This file is auto-generated by oagen. Do not edit.

export interface EnrollUserAuthenticationFactor {
  /** The type of the factor to enroll. */
  type: 'totp';
  /** Your application or company name displayed in the user's authenticator app. */
  totpIssuer?: string;
  /** The user's account name displayed in their authenticator app. */
  totpUser?: string;
  /** The Base32-encoded shared secret for TOTP factors. This can be provided when creating the auth factor, otherwise it will be generated. The algorithm used to derive TOTP codes is SHA-1, the code length is 6 digits, and the timestep is 30 seconds – the secret must be compatible with these parameters. */
  totpSecret?: string;
}

export interface EnrollUserAuthenticationFactorResponse {
  type: 'totp';
  totp_issuer?: string;
  totp_user?: string;
  totp_secret?: string;
}
