// This file is auto-generated by oagen. Do not edit.

import type {
  JwksResponseKeys,
  JwksResponseKeysResponse,
} from './jwks-response-keys.interface';

export interface JwksResponse {
  /** The public keys used for verifying access tokens. */
  keys: JwksResponseKeys[];
}

export interface JwksResponseWire {
  keys: JwksResponseKeysResponse[];
}
