// This file is auto-generated by oagen. Do not edit.

export interface JWTTemplateResponse {
  /** The object type. */
  object: 'jwt_template';
  /** The JWT template content as a Liquid template string. */
  content: string;
  /** The timestamp when the JWT template was created. */
  createdAt: string;
  /** The timestamp when the JWT template was last updated. */
  updatedAt: string;
}

export interface JWTTemplateResponseWire {
  object: 'jwt_template';
  content: string;
  created_at: string;
  updated_at: string;
}
