// This file is auto-generated by oagen. Do not edit.

import type { UserInviteState } from '../../common/interfaces/user-invite-state.interface';

export interface UserInvite {
  /** Distinguishes the invitation object. */
  object: 'invitation';
  /** The unique ID of the invitation. */
  id: string;
  /** The email address of the recipient. */
  email: string;
  /** The state of the invitation. */
  state: UserInviteState;
  /** The timestamp when the invitation was accepted, or null if not yet accepted. */
  acceptedAt: string | null;
  /** The timestamp when the invitation was revoked, or null if not revoked. */
  revokedAt: string | null;
  /** The timestamp when the invitation expires. */
  expiresAt: string;
  /** The ID of the [organization](https://workos.com/docs/reference/organization) that the recipient will join. */
  organizationId: string | null;
  /** The ID of the user who invited the recipient, if provided. */
  inviterUserId: string | null;
  /** The ID of the user who accepted the invitation, once accepted. */
  acceptedUserId: string | null;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
  /** The token used to accept the invitation. */
  token: string;
  /** The URL where the recipient can accept the invitation. */
  acceptInvitationUrl: string;
}

export interface UserInviteResponse {
  object: 'invitation';
  id: string;
  email: string;
  state: UserInviteState;
  accepted_at: string | null;
  revoked_at: string | null;
  expires_at: string;
  organization_id: string | null;
  inviter_user_id: string | null;
  accepted_user_id: string | null;
  created_at: string;
  updated_at: string;
  token: string;
  accept_invitation_url: string;
}
