// This file is auto-generated by oagen. Do not edit.

import type {
  OrganizationDomainStandAlone,
  OrganizationDomainStandAloneResponse,
} from '../interfaces/organization-domain-stand-alone.interface';

export const deserializeOrganizationDomainStandAlone = (
  response: OrganizationDomainStandAloneResponse,
): OrganizationDomainStandAlone => ({
  object: response.object,
  id: response.id,
  organizationId: response.organization_id,
  domain: response.domain,
  state: response.state,
  verificationPrefix: response.verification_prefix,
  verificationToken: response.verification_token,
  verificationStrategy: response.verification_strategy,
  createdAt: response.created_at,
  updatedAt: response.updated_at,
});

export const serializeOrganizationDomainStandAlone = (
  model: OrganizationDomainStandAlone,
): OrganizationDomainStandAloneResponse => ({
  object: model.object,
  id: model.id,
  organization_id: model.organizationId,
  domain: model.domain,
  state: model.state,
  verification_prefix: model.verificationPrefix,
  verification_token: model.verificationToken,
  verification_strategy: model.verificationStrategy,
  created_at: model.createdAt,
  updated_at: model.updatedAt,
});
