// This file is auto-generated by oagen. Do not edit.

import type {
  CreateApplicationSecret,
  CreateApplicationSecretResponse,
} from '../interfaces/create-application-secret.interface';

export const serializeCreateApplicationSecret = (
  _model: CreateApplicationSecret,
): CreateApplicationSecretResponse => ({});
