// This file is auto-generated by oagen. Do not edit.

import type {
  UserConsentOption,
  UserConsentOptionResponse,
} from '../interfaces/user-consent-option.interface';
import { serializeUserConsentOptionChoice } from './user-consent-option-choice.serializer';

export const serializeUserConsentOption = (
  model: UserConsentOption,
): UserConsentOptionResponse => ({
  claim: model.claim,
  type: model.type,
  label: model.label,
  choices: model.choices.map(serializeUserConsentOptionChoice),
});
