// This file is auto-generated by oagen. Do not edit.

import fetch from 'jest-fetch-mock';
import {
  fetchOnce,
  fetchURL,
  fetchMethod,
  fetchBody,
} from '../common/utils/test-utils';
import { WorkOS } from '../workos';

import organizationDomainFixture from './fixtures/organization-domain.json';
import organizationDomainStandAloneFixture from './fixtures/organization-domain-stand-alone.json';

const workos = new WorkOS('sk_test_Sz3IQjepeSWaI4cMS4ms4sMuU');

function expectOrganizationDomainStandAlone(result: any) {
  expect(result.object).toBe('organization_domain');
  expect(result.id).toBe('org_domain_01EHZNVPK2QXHMVWCEDQEKY69A');
  expect(result.organizationId).toBe('org_01HE8GSH8FQPASKSY27THRKRBP');
  expect(result.domain).toBe('foo-corp.com');
  expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
  expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
}

describe('OrganizationDomains', () => {
  beforeEach(() => fetch.resetMocks());

  describe('createOrganizationDomain', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(organizationDomainFixture);

      const result = await workos.organizationDomains.createOrganizationDomain({
        domain: 'test_domain',
        organizationId: 'organization_id_01234',
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organization_domains',
      );
      expect(fetchBody()).toEqual(
        expect.objectContaining({
          domain: 'test_domain',
          organization_id: 'organization_id_01234',
        }),
      );
      expect(result.object).toBe('organization_domain');
      expect(result.id).toBe('org_domain_01EHZNVPK2QXHMVWCEDQEKY69A');
      expect(result.organizationId).toBe('org_01HE8GSH8FQPASKSY27THRKRBP');
      expect(result.domain).toBe('foo-corp.com');
      expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
      expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
    });
  });

  describe('getOrganizationDomain', () => {
    it('returns the expected result', async () => {
      fetchOnce(organizationDomainStandAloneFixture);

      const result = await workos.organizationDomains.getOrganizationDomain({
        id: 'test_id',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organization_domains/test_id',
      );
      expectOrganizationDomainStandAlone(result);
    });
  });

  describe('deleteOrganizationDomain', () => {
    it('sends a DELETE request', async () => {
      fetchOnce({}, { status: 204 });

      await workos.organizationDomains.deleteOrganizationDomain({
        id: 'test_id',
      });

      expect(fetchMethod()).toBe('DELETE');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organization_domains/test_id',
      );
    });
  });

  describe('verifyOrganizationDomain', () => {
    it('returns the expected result', async () => {
      fetchOnce(organizationDomainStandAloneFixture);

      const result = await workos.organizationDomains.verifyOrganizationDomain({
        id: 'test_id',
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organization_domains/test_id/verify',
      );
      expectOrganizationDomainStandAlone(result);
    });
  });
});
