// This file is auto-generated by oagen. Do not edit.

import { serializeCreateOrganizationDomain } from './serializers/create-organization-domain.serializer';
import { deserializeOrganizationDomain } from './serializers/organization-domain.serializer';
import type { CreateOrganizationDomainResponse } from './interfaces/create-organization-domain.interface';
import type { OrganizationDomainResponse } from './interfaces/organization-domain.interface';
import createOrganizationDomainFixture from './fixtures/create-organization-domain.json';
import organizationDomainFixture from './fixtures/organization-domain.json';

describe('CreateOrganizationDomainSerializer', () => {
  it('serializes correctly', () => {
    const fixture =
      createOrganizationDomainFixture as CreateOrganizationDomainResponse;
    const serialized = serializeCreateOrganizationDomain(fixture as any);
    expect(serialized).toBeDefined();
  });
});

describe('OrganizationDomainSerializer', () => {
  it('deserializes correctly', () => {
    const fixture = organizationDomainFixture as OrganizationDomainResponse;
    const deserialized = deserializeOrganizationDomain(fixture);
    expect(deserialized).toBeDefined();
  });
});
