// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogExportJson,
  AuditLogExportJsonResponse,
} from '../interfaces/audit-log-export-json.interface';

export const deserializeAuditLogExportJson = (
  response: AuditLogExportJsonResponse,
): AuditLogExportJson => ({
  object: response.object,
  id: response.id,
  state: response.state,
  url: response.url ?? null,
  createdAt: response.created_at,
  updatedAt: response.updated_at,
});

export const serializeAuditLogExportJson = (
  model: AuditLogExportJson,
): AuditLogExportJsonResponse => ({
  object: model.object,
  id: model.id,
  state: model.state,
  url: model.url ?? null,
  created_at: model.createdAt,
  updated_at: model.updatedAt,
});
