// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogSchemaActor,
  AuditLogSchemaActorResponse,
} from '../interfaces/audit-log-schema-actor.interface';

export const deserializeAuditLogSchemaActor = (
  response: AuditLogSchemaActorResponse,
): AuditLogSchemaActor => ({
  metadata: response.metadata,
});

export const serializeAuditLogSchemaActor = (
  model: AuditLogSchemaActor,
): AuditLogSchemaActorResponse => ({
  metadata: model.metadata,
});
