// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogSchemaActorInput,
  AuditLogSchemaActorInputResponse,
} from '../interfaces/audit-log-schema-actor-input.interface';

export const serializeAuditLogSchemaActorInput = (
  model: AuditLogSchemaActorInput,
): AuditLogSchemaActorInputResponse => ({
  metadata: model.metadata,
});
