// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogSchema,
  AuditLogSchemaResponse,
} from '../interfaces/audit-log-schema.interface';
import { deserializeAuditLogSchemaActor } from './audit-log-schema-actor.serializer';
import { deserializeAuditLogSchemaTarget } from './audit-log-schema-target.serializer';

export const deserializeAuditLogSchema = (
  response: AuditLogSchemaResponse,
): AuditLogSchema => ({
  object: response.object,
  version: response.version,
  actor:
    response.actor != null
      ? deserializeAuditLogSchemaActor(response.actor)
      : undefined,
  targets: response.targets.map(deserializeAuditLogSchemaTarget),
  metadata: response.metadata,
  createdAt: new Date(response.created_at),
});
