// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogEvent,
  AuditLogEventResponse,
} from '../interfaces/audit-log-event.interface';
import { serializeAuditLogEventActor } from './audit-log-event-actor.serializer';
import { serializeAuditLogEventTarget } from './audit-log-event-target.serializer';
import { serializeAuditLogEventContext } from './audit-log-event-context.serializer';

export const serializeAuditLogEvent = (
  model: AuditLogEvent,
): AuditLogEventResponse => ({
  action: model.action,
  occurred_at: model.occurredAt.toISOString(),
  actor: serializeAuditLogEventActor(model.actor),
  targets: model.targets.map(serializeAuditLogEventTarget),
  context: serializeAuditLogEventContext(model.context),
  metadata: model.metadata,
  version: model.version,
});
