// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogExportCreation,
  AuditLogExportCreationResponse,
} from '../interfaces/audit-log-export-creation.interface';

export const deserializeAuditLogExportCreation = (
  response: AuditLogExportCreationResponse,
): AuditLogExportCreation => ({
  organizationId: response.organization_id,
  rangeStart: response.range_start,
  rangeEnd: response.range_end,
  actions: response.actions,
  actors: response.actors,
  actorNames: response.actor_names,
  actorIds: response.actor_ids,
  targets: response.targets,
});

export const serializeAuditLogExportCreation = (
  model: AuditLogExportCreation,
): AuditLogExportCreationResponse => ({
  organization_id: model.organizationId,
  range_start: model.rangeStart,
  range_end: model.rangeEnd,
  actions: model.actions,
  actors: model.actors,
  actor_names: model.actorNames,
  actor_ids: model.actorIds,
  targets: model.targets,
});
