// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogExport,
  AuditLogExportResponse,
} from '../interfaces/audit-log-export.interface';

export const deserializeAuditLogExport = (
  response: AuditLogExportResponse,
): AuditLogExport => ({
  object: response.object,
  id: response.id,
  state: response.state,
  url: response.url ?? undefined,
  createdAt: new Date(response.created_at),
  updatedAt: new Date(response.updated_at),
});
