// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import type { AutoPaginatable } from '../common/utils/pagination';
import { createPaginatedList } from '../common/utils/fetch-and-deserialize';
import type {
  AuthenticationChallengeVerifyResponse,
  AuthenticationChallengeVerifyResponseWire,
} from './interfaces/authentication-challenge-verify-response.interface';
import type {
  AuthenticationFactorEnrolled,
  AuthenticationFactorEnrolledResponse,
} from './interfaces/authentication-factor-enrolled.interface';
import type {
  AuthenticationFactor,
  AuthenticationFactorResponse,
} from './interfaces/authentication-factor.interface';
import type {
  AuthenticationChallenge,
  AuthenticationChallengeResponse,
} from './interfaces/authentication-challenge.interface';
import type {
  UserAuthenticationFactorEnrollResponse,
  UserAuthenticationFactorEnrollResponseWire,
} from './interfaces/user-authentication-factor-enroll-response.interface';
import type { AuthenticationChallengesVerifyRequest } from './interfaces/authentication-challenges-verify-request.interface';
import type { AuthenticationFactorsCreateRequest } from './interfaces/authentication-factors-create-request.interface';
import type { ChallengeAuthenticationFactor } from './interfaces/challenge-authentication-factor.interface';
import type { EnrollUserAuthenticationFactor } from './interfaces/enroll-user-authentication-factor.interface';
import { deserializeAuthenticationChallengeVerifyResponse } from './serializers/authentication-challenge-verify-response.serializer';
import { deserializeAuthenticationFactorEnrolled } from './serializers/authentication-factor-enrolled.serializer';
import { deserializeAuthenticationFactor } from './serializers/authentication-factor.serializer';
import { deserializeAuthenticationChallenge } from './serializers/authentication-challenge.serializer';
import { deserializeUserAuthenticationFactorEnrollResponse } from './serializers/user-authentication-factor-enroll-response.serializer';
import { serializeAuthenticationChallengesVerifyRequest } from './serializers/authentication-challenges-verify-request.serializer';
import { serializeAuthenticationFactorsCreateRequest } from './serializers/authentication-factors-create-request.serializer';
import { serializeChallengeAuthenticationFactor } from './serializers/challenge-authentication-factor.serializer';
import { serializeEnrollUserAuthenticationFactor } from './serializers/enroll-user-authentication-factor.serializer';

export class MultiFactorAuth {
  constructor(private readonly workos: WorkOS) {}

  /**
   * Verify Challenge
   *
   * Verifies an Authentication Challenge.
   * @param id - The unique ID of the Authentication Challenge.
   * @example "auth_challenge_01FVYZ5QM8N98T9ME5BCB2BBMJ"
   * @param payload - Object containing code.
   * @returns {AuthenticationChallengeVerifyResponse}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async verifyChallenge(
    id: string,
    payload: AuthenticationChallengesVerifyRequest,
  ): Promise<AuthenticationChallengeVerifyResponse> {
    const { data } =
      await this.workos.post<AuthenticationChallengeVerifyResponseWire>(
        `/auth/challenges/${id}/verify`,
        serializeAuthenticationChallengesVerifyRequest(payload),
      );
    return deserializeAuthenticationChallengeVerifyResponse(data);
  }

  /**
   * Enroll Factor
   *
   * Enrolls an Authentication Factor to be used as an additional factor of authentication. The returned ID should be used to create an authentication Challenge.
   * @param payload - Object containing type.
   * @returns {AuthenticationFactorEnrolled}
   * @throws {UnprocessableEntityException} 422
   */
  async enrollFactor(
    payload: AuthenticationFactorsCreateRequest,
  ): Promise<AuthenticationFactorEnrolled> {
    const { data } =
      await this.workos.post<AuthenticationFactorEnrolledResponse>(
        '/auth/factors/enroll',
        serializeAuthenticationFactorsCreateRequest(payload),
      );
    return deserializeAuthenticationFactorEnrolled(data);
  }

  /**
   * Get Factor
   *
   * Gets an Authentication Factor.
   * @param id - The unique ID of the Factor.
   * @example "auth_factor_01FVYZ5QM8N98T9ME5BCB2BBMJ"
   * @returns {AuthenticationFactor}
   * @throws {NotFoundException} 404
   */
  async getFactor(id: string): Promise<AuthenticationFactor> {
    const { data } = await this.workos.get<AuthenticationFactorResponse>(
      `/auth/factors/${id}`,
    );
    return deserializeAuthenticationFactor(data);
  }

  /**
   * Delete Factor
   *
   * Permanently deletes an Authentication Factor. It cannot be undone.
   * @param id - The unique ID of the Factor.
   * @example "auth_factor_01FVYZ5QM8N98T9ME5BCB2BBMJ"
   * @returns {void}
   * @throws {NotFoundException} 404
   */
  async deleteFactor(id: string): Promise<void> {
    await this.workos.delete(`/auth/factors/${id}`);
  }

  /**
   * Challenge Factor
   *
   * Creates a Challenge for an Authentication Factor.
   * @param id - The unique ID of the Authentication Factor to be challenged.
   * @example "auth_factor_01FVYZ5QM8N98T9ME5BCB2BBMJ"
   * @param payload - The request body.
   * @returns {AuthenticationChallenge}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async challengeFactor(
    id: string,
    payload: ChallengeAuthenticationFactor,
  ): Promise<AuthenticationChallenge> {
    const { data } = await this.workos.post<AuthenticationChallengeResponse>(
      `/auth/factors/${id}/challenge`,
      serializeChallengeAuthenticationFactor(payload),
    );
    return deserializeAuthenticationChallenge(data);
  }

  /**
   * List authentication factors
   *
   * Lists the [authentication factors](https://workos.com/docs/reference/authkit/mfa/authentication-factor) for a user.
   * @param userlandUserId - The ID of the [user](https://workos.com/docs/reference/authkit/user).
   * @example "user_01E4ZCR3C56J083X43JQXF3JK5"
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<AuthenticationFactor>}
   * @throws {UnprocessableEntityException} 422
   */
  async listUserAuthFactors(
    userlandUserId: string,
    options?: PaginationOptions,
  ): Promise<AutoPaginatable<AuthenticationFactor, PaginationOptions>> {
    return createPaginatedList<
      AuthenticationFactorResponse,
      AuthenticationFactor,
      PaginationOptions
    >(
      this.workos,
      `/user_management/users/${userlandUserId}/auth_factors`,
      deserializeAuthenticationFactor,
      options,
    );
  }

  /**
   * Enroll an authentication factor
   *
   * Enrolls a user in a new [authentication factor](https://workos.com/docs/reference/authkit/mfa/authentication-factor).
   * @param userlandUserId - The ID of the [user](https://workos.com/docs/reference/authkit/user).
   * @example "user_01E4ZCR3C56J083X43JQXF3JK5"
   * @param payload - Object containing type.
   * @returns {UserAuthenticationFactorEnrollResponse}
   * @throws {UnprocessableEntityException} 422
   */
  async createUserAuthFactors(
    userlandUserId: string,
    payload: EnrollUserAuthenticationFactor,
  ): Promise<UserAuthenticationFactorEnrollResponse> {
    const { data } =
      await this.workos.post<UserAuthenticationFactorEnrollResponseWire>(
        `/user_management/users/${userlandUserId}/auth_factors`,
        serializeEnrollUserAuthenticationFactor(payload),
      );
    return deserializeUserAuthenticationFactorEnrollResponse(data);
  }
}
