// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import type { AutoPaginatable } from '../common/utils/pagination';
import { createPaginatedList } from '../common/utils/fetch-and-deserialize';
import type {
  ExternalAuthCompleteResponse,
  ExternalAuthCompleteResponseWire,
} from './interfaces/external-auth-complete-response.interface';
import type {
  ConnectApplication,
  ConnectApplicationResponse,
} from './interfaces/connect-application.interface';
import type {
  ApplicationCredentialsListItem,
  ApplicationCredentialsListItemResponse,
} from './interfaces/application-credentials-list-item.interface';
import type {
  NewConnectApplicationSecret,
  NewConnectApplicationSecretResponse,
} from './interfaces/new-connect-application-secret.interface';
import type { UserManagementLoginRequest } from './interfaces/user-management-login-request.interface';
import type { CreateOAuthApplication } from './interfaces/create-oauth-application.interface';
import type { CreateM2MApplication } from './interfaces/create-m2m-application.interface';
import type { UpdateOAuthApplication } from './interfaces/update-oauth-application.interface';
import type { CreateApplicationSecret } from './interfaces/create-application-secret.interface';
import { deserializeExternalAuthCompleteResponse } from './serializers/external-auth-complete-response.serializer';
import { deserializeConnectApplication } from './serializers/connect-application.serializer';
import { deserializeApplicationCredentialsListItem } from './serializers/application-credentials-list-item.serializer';
import { deserializeNewConnectApplicationSecret } from './serializers/new-connect-application-secret.serializer';
import { serializeUserManagementLoginRequest } from './serializers/user-management-login-request.serializer';
import { serializeCreateOAuthApplication } from './serializers/create-oauth-application.serializer';
import { serializeCreateM2MApplication } from './serializers/create-m2m-application.serializer';
import { serializeUpdateOAuthApplication } from './serializers/update-oauth-application.serializer';
import { serializeCreateApplicationSecret } from './serializers/create-application-secret.serializer';

export interface ListApplicationsOptions extends PaginationOptions {
  /** Filter Connect Applications by organization ID. */
  organizationId?: string;
}

const serializeListApplicationsOptions = (
  options: ListApplicationsOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    before: options.before,
    after: options.after,
    order: options.order,
  };
  if (options.organizationId !== undefined)
    wire.organization_id = options.organizationId;
  return wire as PaginationOptions;
};

export class Connect {
  constructor(private readonly workos: WorkOS) {}

  /**
   * Complete external authentication
   *
   * Completes an external authentication flow and returns control to AuthKit. This endpoint is used with [Standalone Connect](https://workos.com/docs/authkit/connect/standalone) to bridge your existing authentication system with the Connect OAuth API infrastructure.
   *
   * After successfully authenticating a user in your application, calling this endpoint will:
   *
   * - Create or update the user in AuthKit, using the given `id` as its `external_id`.
   * - Return a `redirect_uri` your application should redirect to in order for AuthKit to complete the flow
   *
   * Users are automatically created or updated based on the `id` and `email` provided. If a user with the same `id` exists, their information is updated. Otherwise, a new user is created.
   *
   * If you provide a new `id` with an `email` that already belongs to an existing user, the request will fail with an error as email addresses are unique to a user.
   * @param payload - Object containing externalAuthId, user.
   * @returns {Promise<ExternalAuthCompleteResponse>}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async completeLogin(
    payload: UserManagementLoginRequest,
  ): Promise<ExternalAuthCompleteResponse> {
    const { data } = await this.workos.post<ExternalAuthCompleteResponseWire>(
      '/authkit/oauth2/complete',
      serializeUserManagementLoginRequest(payload),
    );
    return deserializeExternalAuthCompleteResponse(data);
  }

  /**
   * List Connect Applications
   *
   * List all Connect Applications in the current environment with optional filtering.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<ConnectApplication>>}
   * @throws {UnprocessableEntityException} 422
   */
  async listApplications(
    options?: ListApplicationsOptions,
  ): Promise<AutoPaginatable<ConnectApplication, ListApplicationsOptions>> {
    return createPaginatedList<
      ConnectApplicationResponse,
      ConnectApplication,
      ListApplicationsOptions
    >(
      this.workos,
      '/connect/applications',
      deserializeConnectApplication,
      options,
      serializeListApplicationsOptions,
    );
  }

  /**
   * Create a Connect Application
   *
   * Create a new Connect Application. Supports both OAuth and Machine-to-Machine (M2M) application types.
   * @param payload - The request body.
   * @returns {Promise<ConnectApplication>}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async createApplication(
    payload: CreateOAuthApplication | CreateM2MApplication,
  ): Promise<ConnectApplication> {
    const { data } = await this.workos.post<ConnectApplicationResponse>(
      '/connect/applications',
      (() => {
        switch (payload.applicationType) {
          case 'oauth':
            return serializeCreateOAuthApplication(payload);
          case 'm2m':
            return serializeCreateM2MApplication(payload);
          default: {
            const _unknown: never = payload;
            throw new Error(
              `Unknown applicationType: ${(_unknown as { applicationType?: unknown }).applicationType}`,
            );
          }
        }
      })(),
    );
    return deserializeConnectApplication(data);
  }

  /**
   * Get a Connect Application
   *
   * Retrieve details for a specific Connect Application by ID or client ID.
   * @param id - The application ID or client ID of the Connect Application.
   * @example "conn_app_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<ConnectApplication>}
   * @throws {NotFoundException} 404
   */
  async getApplication(id: string): Promise<ConnectApplication> {
    const { data } = await this.workos.get<ConnectApplicationResponse>(
      `/connect/applications/${id}`,
    );
    return deserializeConnectApplication(data);
  }

  /**
   * Update a Connect Application
   *
   * Update an existing Connect Application. For OAuth applications, you can update redirect URIs. For all applications, you can update the name, description, and scopes.
   * @param id - The application ID or client ID of the Connect Application.
   * @example "conn_app_01HXYZ123456789ABCDEFGHIJ"
   * @param payload - The request body.
   * @returns {Promise<ConnectApplication>}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updateApplication(
    id: string,
    payload: UpdateOAuthApplication,
  ): Promise<ConnectApplication> {
    const { data } = await this.workos.put<ConnectApplicationResponse>(
      `/connect/applications/${id}`,
      serializeUpdateOAuthApplication(payload),
    );
    return deserializeConnectApplication(data);
  }

  /**
   * Delete a Connect Application
   *
   * Delete an existing Connect Application.
   * @param id - The application ID or client ID of the Connect Application.
   * @example "conn_app_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<void>}
   * @throws {NotFoundException} 404
   */
  async deleteApplication(id: string): Promise<void> {
    await this.workos.delete(`/connect/applications/${id}`);
  }

  /**
   * List Client Secrets for a Connect Application
   *
   * List all client secrets associated with a Connect Application.
   * @param id - The application ID or client ID of the Connect Application.
   * @example "conn_app_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<ApplicationCredentialsListItem[]>}
   * @throws {NotFoundException} 404
   */
  async listApplicationClientSecrets(
    id: string,
  ): Promise<ApplicationCredentialsListItem[]> {
    const { data } = await this.workos.get<
      ApplicationCredentialsListItemResponse[]
    >(`/connect/applications/${id}/client_secrets`);
    return data.map(deserializeApplicationCredentialsListItem);
  }

  /**
   * Create a new client secret for a Connect Application
   *
   * Create new secrets for a Connect Application.
   * @param id - The application ID or client ID of the Connect Application.
   * @example "conn_app_01HXYZ123456789ABCDEFGHIJ"
   * @param payload - The request body.
   * @returns {Promise<NewConnectApplicationSecret>}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async createApplicationClientSecret(
    id: string,
    payload: CreateApplicationSecret,
  ): Promise<NewConnectApplicationSecret> {
    const { data } =
      await this.workos.post<NewConnectApplicationSecretResponse>(
        `/connect/applications/${id}/client_secrets`,
        serializeCreateApplicationSecret(payload),
      );
    return deserializeNewConnectApplicationSecret(data);
  }

  /**
   * Delete a Client Secret
   *
   * Delete (revoke) an existing client secret.
   * @param id - The unique ID of the client secret.
   * @example "secret_01J9Q2Z3X4Y5W6V7U8T9S0R1Q"
   * @returns {Promise<void>}
   * @throws {NotFoundException} 404
   */
  async deleteClientSecret(id: string): Promise<void> {
    await this.workos.delete(`/connect/client_secrets/${id}`);
  }
}
