// This file is auto-generated by oagen. Do not edit.

import type {
  CreateOAuthApplication,
  CreateOAuthApplicationResponse,
} from '../interfaces/create-oauth-application.interface';
import {
  deserializeRedirectUri,
  serializeRedirectUri,
} from './redirect-uri.serializer';

export const deserializeCreateOAuthApplication = (
  response: CreateOAuthApplicationResponse,
): CreateOAuthApplication => ({
  name: response.name,
  applicationType: response.application_type,
  description: response.description ?? null,
  scopes: response.scopes ?? null,
  redirectUris:
    response.redirect_uris != null
      ? response.redirect_uris.map(deserializeRedirectUri)
      : null,
  usesPkce: response.uses_pkce ?? null,
  isFirstParty: response.is_first_party,
  organizationId: response.organization_id ?? null,
});

export const serializeCreateOAuthApplication = (
  model: CreateOAuthApplication,
): CreateOAuthApplicationResponse => ({
  name: model.name,
  application_type: model.applicationType,
  description: model.description ?? null,
  scopes: model.scopes ?? null,
  redirect_uris:
    model.redirectUris != null
      ? model.redirectUris.map(serializeRedirectUri)
      : null,
  uses_pkce: model.usesPkce ?? null,
  is_first_party: model.isFirstParty,
  organization_id: model.organizationId ?? null,
});
