// This file is auto-generated by oagen. Do not edit.

import type {
  UserManagementLoginRequest,
  UserManagementLoginRequestResponse,
} from '../interfaces/user-management-login-request.interface';
import {
  deserializeUserObject,
  serializeUserObject,
} from './user-object.serializer';
import {
  deserializeUserConsentOption,
  serializeUserConsentOption,
} from './user-consent-option.serializer';

export const deserializeUserManagementLoginRequest = (
  response: UserManagementLoginRequestResponse,
): UserManagementLoginRequest => ({
  externalAuthId: response.external_auth_id,
  user: deserializeUserObject(response.user),
  userConsentOptions:
    response.user_consent_options != null
      ? response.user_consent_options.map(deserializeUserConsentOption)
      : undefined,
});

export const serializeUserManagementLoginRequest = (
  model: UserManagementLoginRequest,
): UserManagementLoginRequestResponse => ({
  external_auth_id: model.externalAuthId,
  user: serializeUserObject(model.user),
  user_consent_options:
    model.userConsentOptions != null
      ? model.userConsentOptions.map(serializeUserConsentOption)
      : undefined,
});
