// This file is auto-generated by oagen. Do not edit.

export {
  deserializeVerifyEmailAddress as deserializeConfirmEmailChange,
  serializeVerifyEmailAddress as serializeConfirmEmailChange,
} from './verify-email-address.serializer';
