// This file is auto-generated by oagen. Do not edit.

import type {
  CreateCorsOrigin,
  CreateCorsOriginResponse,
} from '../interfaces/create-cors-origin.interface';

export const deserializeCreateCorsOrigin = (
  response: CreateCorsOriginResponse,
): CreateCorsOrigin => ({
  origin: response.origin,
});

export const serializeCreateCorsOrigin = (
  model: CreateCorsOrigin,
): CreateCorsOriginResponse => ({
  origin: model.origin,
});
