// This file is auto-generated by oagen. Do not edit.

import type {
  RefreshTokenSessionAuthenticateRequest,
  RefreshTokenSessionAuthenticateRequestResponse,
} from '../interfaces/refresh-token-session-authenticate-request.interface';

export const deserializeRefreshTokenSessionAuthenticateRequest = (
  response: RefreshTokenSessionAuthenticateRequestResponse,
): RefreshTokenSessionAuthenticateRequest => ({
  clientId: response.client_id,
  clientSecret: response.client_secret,
  grantType: response.grant_type,
  refreshToken: response.refresh_token,
  organizationId: response.organization_id,
  ipAddress: response.ip_address,
  deviceId: response.device_id,
  userAgent: response.user_agent,
});

export const serializeRefreshTokenSessionAuthenticateRequest = (
  model: RefreshTokenSessionAuthenticateRequest,
): RefreshTokenSessionAuthenticateRequestResponse => ({
  client_id: model.clientId,
  client_secret: model.clientSecret,
  grant_type: model.grantType,
  refresh_token: model.refreshToken,
  organization_id: model.organizationId,
  ip_address: model.ipAddress,
  device_id: model.deviceId,
  user_agent: model.userAgent,
});
