// This file is auto-generated by oagen. Do not edit.

import type {
  RevokeSession,
  RevokeSessionResponse,
} from '../interfaces/revoke-session.interface';

export const deserializeRevokeSession = (
  response: RevokeSessionResponse,
): RevokeSession => ({
  sessionId: response.session_id,
  returnTo: response.return_to,
});

export const serializeRevokeSession = (
  model: RevokeSession,
): RevokeSessionResponse => ({
  session_id: model.sessionId,
  return_to: model.returnTo,
});
