// This file is auto-generated by oagen. Do not edit.

import type {
  SendEmailChange,
  SendEmailChangeResponse,
} from '../interfaces/send-email-change.interface';

export const deserializeSendEmailChange = (
  response: SendEmailChangeResponse,
): SendEmailChange => ({
  newEmail: response.new_email,
});

export const serializeSendEmailChange = (
  model: SendEmailChange,
): SendEmailChangeResponse => ({
  new_email: model.newEmail,
});
