// This file is auto-generated by oagen. Do not edit.

import type {
  SSODeviceAuthorizationRequest,
  SSODeviceAuthorizationRequestResponse,
} from '../interfaces/sso-device-authorization-request.interface';

export const deserializeSSODeviceAuthorizationRequest = (
  response: SSODeviceAuthorizationRequestResponse,
): SSODeviceAuthorizationRequest => ({
  clientId: response.client_id,
});

export const serializeSSODeviceAuthorizationRequest = (
  model: SSODeviceAuthorizationRequest,
): SSODeviceAuthorizationRequestResponse => ({
  client_id: model.clientId,
});
