// This file is auto-generated by oagen. Do not edit.

import type {
  UpdateJWTTemplate,
  UpdateJWTTemplateResponse,
} from '../interfaces/update-jwt-template.interface';

export const deserializeUpdateJWTTemplate = (
  response: UpdateJWTTemplateResponse,
): UpdateJWTTemplate => ({
  content: response.content,
});

export const serializeUpdateJWTTemplate = (
  model: UpdateJWTTemplate,
): UpdateJWTTemplateResponse => ({
  content: model.content,
});
