// This file is auto-generated by oagen. Do not edit.

import type {
  UrnWorkosOAuthGrantTypeOrganizationSelectionSessionAuthenticateRequest,
  UrnWorkosOAuthGrantTypeOrganizationSelectionSessionAuthenticateRequestResponse,
} from '../interfaces/urn-workos-oauth-grant-type-organization-selection-session-authenticate-request.interface';

export const deserializeUrnWorkosOAuthGrantTypeOrganizationSelectionSessionAuthenticateRequest =
  (
    response: UrnWorkosOAuthGrantTypeOrganizationSelectionSessionAuthenticateRequestResponse,
  ): UrnWorkosOAuthGrantTypeOrganizationSelectionSessionAuthenticateRequest => ({
    clientId: response.client_id,
    clientSecret: response.client_secret,
    grantType: response.grant_type,
    pendingAuthenticationToken: response.pending_authentication_token,
    organizationId: response.organization_id,
    ipAddress: response.ip_address,
    deviceId: response.device_id,
    userAgent: response.user_agent,
  });

export const serializeUrnWorkosOAuthGrantTypeOrganizationSelectionSessionAuthenticateRequest =
  (
    model: UrnWorkosOAuthGrantTypeOrganizationSelectionSessionAuthenticateRequest,
  ): UrnWorkosOAuthGrantTypeOrganizationSelectionSessionAuthenticateRequestResponse => ({
    client_id: model.clientId,
    client_secret: model.clientSecret,
    grant_type: model.grantType,
    pending_authentication_token: model.pendingAuthenticationToken,
    organization_id: model.organizationId,
    ip_address: model.ipAddress,
    device_id: model.deviceId,
    user_agent: model.userAgent,
  });
