// This file is auto-generated by oagen. Do not edit.

import type {
  UrnWorkosOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequest,
  UrnWorkosOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequestResponse,
} from '../interfaces/urn-workos-oauth-grant-type-magic-auth-code-session-authenticate-request.interface';

export const deserializeUrnWorkosOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequest =
  (
    response: UrnWorkosOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequestResponse,
  ): UrnWorkosOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequest => ({
    clientId: response.client_id,
    clientSecret: response.client_secret,
    grantType: response.grant_type,
    code: response.code,
    email: response.email,
    invitationToken: response.invitation_token,
    ipAddress: response.ip_address,
    deviceId: response.device_id,
    userAgent: response.user_agent,
  });

export const serializeUrnWorkosOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequest =
  (
    model: UrnWorkosOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequest,
  ): UrnWorkosOAuthGrantTypeMagicAuthCodeSessionAuthenticateRequestResponse => ({
    client_id: model.clientId,
    client_secret: model.clientSecret,
    grant_type: model.grantType,
    code: model.code,
    email: model.email,
    invitation_token: model.invitationToken,
    ip_address: model.ipAddress,
    device_id: model.deviceId,
    user_agent: model.userAgent,
  });
