// This file is auto-generated by oagen. Do not edit.

import type {
  UserSessionsListItem,
  UserSessionsListItemResponse,
} from '../interfaces/user-sessions-list-item.interface';
import {
  deserializeUserSessionsImpersonator,
  serializeUserSessionsImpersonator,
} from './user-sessions-impersonator.serializer';

export const deserializeUserSessionsListItem = (
  response: UserSessionsListItemResponse,
): UserSessionsListItem => ({
  object: response.object,
  id: response.id,
  impersonator:
    response.impersonator != null
      ? deserializeUserSessionsImpersonator(response.impersonator)
      : undefined,
  ipAddress: response.ip_address ?? null,
  organizationId: response.organization_id,
  userAgent: response.user_agent ?? null,
  userId: response.user_id,
  authMethod: response.auth_method,
  status: response.status,
  expiresAt: response.expires_at,
  endedAt: response.ended_at,
  createdAt: response.created_at,
  updatedAt: response.updated_at,
});

export const serializeUserSessionsListItem = (
  model: UserSessionsListItem,
): UserSessionsListItemResponse => ({
  object: model.object,
  id: model.id,
  impersonator:
    model.impersonator != null
      ? serializeUserSessionsImpersonator(model.impersonator)
      : undefined,
  ip_address: model.ipAddress,
  organization_id: model.organizationId,
  user_agent: model.userAgent,
  user_id: model.userId,
  auth_method: model.authMethod,
  status: model.status,
  expires_at: model.expiresAt,
  ended_at: model.endedAt,
  created_at: model.createdAt,
  updated_at: model.updatedAt,
});
