// This file is auto-generated by oagen. Do not edit.

import { User, UserResponse } from '../interfaces';

export const deserializeUser = (user: UserResponse): User => ({
  object: user.object,
  id: user.id,
  email: user.email,
  emailVerified: user.email_verified,
  firstName: user.first_name,
  profilePictureUrl: user.profile_picture_url,
  lastName: user.last_name,
  lastSignInAt: user.last_sign_in_at,
  locale: user.locale,
  createdAt: user.created_at,
  updatedAt: user.updated_at,
  externalId: user.external_id ?? null,
  metadata: user.metadata ?? {},
});

export const serializeUser = (model: User): UserResponse => ({
  object: model.object,
  id: model.id,
  first_name: model.firstName,
  last_name: model.lastName,
  profile_picture_url: model.profilePictureUrl,
  email: model.email,
  email_verified: model.emailVerified,
  external_id: model.externalId ?? null,
  metadata: model.metadata,
  last_sign_in_at: model.lastSignInAt,
  locale: model.locale ?? null,
  created_at: model.createdAt,
  updated_at: model.updatedAt,
});
