// This file is auto-generated by oagen. Do not edit.

export {
  deserializeAuthenticateResponseImpersonator as deserializeUserSessionsImpersonator,
  serializeAuthenticateResponseImpersonator as serializeUserSessionsImpersonator,
} from './authenticate-response-impersonator.serializer';
