// This file is auto-generated by oagen. Do not edit.

import type {
  UserOrganizationMembership,
  UserOrganizationMembershipResponse,
} from '../interfaces/user-organization-membership.interface';
import {
  deserializeSlimRole,
  serializeSlimRole,
} from '../../authorization/serializers/slim-role.serializer';

export const deserializeUserOrganizationMembership = (
  response: UserOrganizationMembershipResponse,
): UserOrganizationMembership => ({
  object: response.object,
  id: response.id,
  userId: response.user_id,
  organizationId: response.organization_id,
  status: response.status,
  directoryManaged: response.directory_managed,
  organizationName: response.organization_name,
  customAttributes: response.custom_attributes,
  createdAt: response.created_at,
  updatedAt: response.updated_at,
  role: deserializeSlimRole(response.role),
});

export const serializeUserOrganizationMembership = (
  model: UserOrganizationMembership,
): UserOrganizationMembershipResponse => ({
  object: model.object,
  id: model.id,
  user_id: model.userId,
  organization_id: model.organizationId,
  status: model.status,
  directory_managed: model.directoryManaged,
  organization_name: model.organizationName,
  custom_attributes: model.customAttributes,
  created_at: model.createdAt,
  updated_at: model.updatedAt,
  role: serializeSlimRole(model.role),
});
