// This file is auto-generated by oagen. Do not edit.

import type {
  ConnectedAccount,
  ConnectedAccountResponse,
} from '../interfaces/connected-account.interface';

export const deserializeConnectedAccount = (
  response: ConnectedAccountResponse,
): ConnectedAccount => ({
  object: response.object,
  id: response.id,
  connectionRole: response.connection_role,
  accountIdentifier: response.account_identifier ?? null,
  accountDisplayName: response.account_display_name ?? null,
  userId: response.user_id ?? null,
  organizationId: response.organization_id ?? null,
  scopes: response.scopes,
  authMethod: response.auth_method,
  apiKeyLast4: response.api_key_last_4 ?? null,
  clientId: response.client_id ?? null,
  clientSecretLast4: response.client_secret_last_4 ?? null,
  config: response.config,
  state: response.state,
  createdAt: response.created_at,
  updatedAt: response.updated_at,
});
