// This file is auto-generated by oagen. Do not edit.

import type {
  DataIntegrationsListResponse,
  DataIntegrationsListResponseWire,
} from '../interfaces/data-integrations-list-response.interface';
import { deserializeDataIntegrationsListResponseData } from './data-integrations-list-response-data.serializer';

export const deserializeDataIntegrationsListResponse = (
  response: DataIntegrationsListResponseWire,
): DataIntegrationsListResponse => ({
  object: response.object,
  data: response.data.map(deserializeDataIntegrationsListResponseData),
});
