// This file is auto-generated by oagen. Do not edit.

import type {
  DataIntegration,
  DataIntegrationResponse,
} from '../interfaces/data-integration.interface';
import { deserializeDataIntegrationCredential } from './data-integration-credential.serializer';
import { deserializeDataIntegrationCustomProvider } from './data-integration-custom-provider.serializer';

export const deserializeDataIntegration = (
  response: DataIntegrationResponse,
): DataIntegration => ({
  object: response.object,
  id: response.id,
  slug: response.slug,
  integrationType: response.integration_type,
  description: response.description ?? null,
  enabled: response.enabled,
  state: response.state,
  scopes: response.scopes ?? null,
  redirectUri: response.redirect_uri,
  credentials: deserializeDataIntegrationCredential(response.credentials),
  customProvider:
    response.custom_provider != null
      ? deserializeDataIntegrationCustomProvider(response.custom_provider)
      : null,
  createdAt: new Date(response.created_at),
  updatedAt: new Date(response.updated_at),
});
