// This file is auto-generated by oagen. Do not edit.

import type {
  DataIntegrationCredentialsResponse,
  DataIntegrationCredentialsResponseWire,
} from '../interfaces/data-integration-credentials-response.interface';
import { deserializeDataIntegrationCredentialsResponseCredential } from './data-integration-credentials-response-credential.serializer';

export const deserializeDataIntegrationCredentialsResponse = (
  response: DataIntegrationCredentialsResponseWire,
): DataIntegrationCredentialsResponse => ({
  active: response.active,
  credential:
    response.credential != null
      ? deserializeDataIntegrationCredentialsResponseCredential(
          response.credential,
        )
      : undefined,
  error: response.error,
});
