// This file is auto-generated by oagen. Do not edit.

import type {
  DataIntegrationsCreateApiKeyConnectionRequest,
  DataIntegrationsCreateApiKeyConnectionRequestResponse,
} from '../interfaces/data-integrations-create-api-key-connection-request.interface';

export const serializeDataIntegrationsCreateApiKeyConnectionRequest = (
  model: DataIntegrationsCreateApiKeyConnectionRequest,
): DataIntegrationsCreateApiKeyConnectionRequestResponse => ({
  user_id: model.userId,
  organization_id: model.organizationId,
  connection_owner: model.connectionOwner,
  secret: model.secret,
  connection_intent: model.connectionIntent,
});
