// This file is auto-generated by oagen. Do not edit.

import { serializeCreateGroupMembership } from './serializers/create-group-membership.serializer';
import { serializeCreateGroup } from './serializers/create-group.serializer';
import { serializeUpdateGroup } from './serializers/update-group.serializer';
import { deserializeGroup } from './serializers/group.serializer';
import { deserializeUserOrganizationMembershipBaseListData } from './serializers/user-organization-membership-base-list-data.serializer';
import type { CreateGroupMembershipResponse } from './interfaces/create-group-membership.interface';
import type { CreateGroupResponse } from './interfaces/create-group.interface';
import type { UpdateGroupResponse } from './interfaces/update-group.interface';
import type { GroupResponse } from './interfaces/group.interface';
import type { UserOrganizationMembershipBaseListDataResponse } from './interfaces/user-organization-membership-base-list-data.interface';
import createGroupMembershipFixture from './fixtures/create-group-membership.json';
import createGroupFixture from './fixtures/create-group.json';
import updateGroupFixture from './fixtures/update-group.json';
import groupFixture from './fixtures/group.json';
import userOrganizationMembershipBaseListDataFixture from './fixtures/user-organization-membership-base-list-data.json';

describe('CreateGroupMembershipSerializer', () => {
  it('serializes correctly', () => {
    const fixture =
      createGroupMembershipFixture as CreateGroupMembershipResponse;
    const serialized = serializeCreateGroupMembership(fixture as any);
    expect(serialized).toBeDefined();
  });
});

describe('CreateGroupSerializer', () => {
  it('serializes correctly', () => {
    const fixture = createGroupFixture as CreateGroupResponse;
    const serialized = serializeCreateGroup(fixture as any);
    expect(serialized).toBeDefined();
  });
});

describe('UpdateGroupSerializer', () => {
  it('serializes correctly', () => {
    const fixture = updateGroupFixture as UpdateGroupResponse;
    const serialized = serializeUpdateGroup(fixture as any);
    expect(serialized).toBeDefined();
  });
});

describe('GroupSerializer', () => {
  it('deserializes correctly', () => {
    const fixture = groupFixture as GroupResponse;
    const deserialized = deserializeGroup(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('UserOrganizationMembershipBaseListDataSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      userOrganizationMembershipBaseListDataFixture as UserOrganizationMembershipBaseListDataResponse;
    const deserialized =
      deserializeUserOrganizationMembershipBaseListData(fixture);
    expect(deserialized).toBeDefined();
  });
});
