// This file is auto-generated by oagen. Do not edit.

import type {
  RadarStandaloneUpdateRadarAttemptRequest,
  RadarStandaloneUpdateRadarAttemptRequestResponse,
} from '../interfaces/radar-standalone-update-radar-attempt-request.interface';

export const deserializeRadarStandaloneUpdateRadarAttemptRequest = (
  response: RadarStandaloneUpdateRadarAttemptRequestResponse,
): RadarStandaloneUpdateRadarAttemptRequest => ({
  challengeStatus: response.challenge_status,
  attemptStatus: response.attempt_status,
});

export const serializeRadarStandaloneUpdateRadarAttemptRequest = (
  model: RadarStandaloneUpdateRadarAttemptRequest,
): RadarStandaloneUpdateRadarAttemptRequestResponse => ({
  challenge_status: model.challengeStatus,
  attempt_status: model.attemptStatus,
});
