// This file is auto-generated by oagen. Do not edit.

export {
  deserializeApiKeyWithValueOwner as deserializeApiKeyOwner,
  serializeApiKeyWithValueOwner as serializeApiKeyOwner,
} from './api-key-with-value-owner.serializer';

export {
  deserializeApiKeyCreatedDataOwner as deserializeApiKeyOwner,
  serializeApiKeyCreatedDataOwner as serializeApiKeyOwner,
} from '../../common/serializers/api-key-created-data-owner.serializer';
