// This file is auto-generated by oagen. Do not edit.

export interface FlagTarget {
  /** Distinguishes the Flag Target object. */
  object: 'flag_target';
  /** Unique identifier of the Flag Target. */
  id: string;
  /** The ID of the Feature Flag the target belongs to. */
  flagId: string;
  /** The slug of the Feature Flag the target belongs to, which is how the Feature Flag endpoints address it. */
  flagSlug: string;
  /** The ID of the environment the Flag Target belongs to. */
  environmentId: string;
  /** The type of the target: `organization`, `user`, or a custom target type slug. */
  targetType: string;
  /** The ID of the targeted entity. */
  targetId: string;
  /** The type of `value`. Only `boolean` is supported today; additional types are reserved for future multivariate Feature Flags. */
  valueType: 'boolean';
  /** The value the Feature Flag evaluates to for this target. */
  value: boolean;
  /** An ISO 8601 timestamp. */
  createdAt: Date;
  /** An ISO 8601 timestamp. */
  updatedAt: Date;
}

export interface FlagTargetResponse {
  object: 'flag_target';
  id: string;
  flag_id: string;
  flag_slug: string;
  environment_id: string;
  target_type: string;
  target_id: string;
  value_type: 'boolean';
  value: boolean;
  created_at: string;
  updated_at: string;
}
