// This file is auto-generated by oagen. Do not edit.

import type { PaginationOptions } from '../../common/interfaces/pagination-options.interface';

export interface ListFlagTargetsOptions extends PaginationOptions {
  /** Filter Flag Targets by the slug of the Feature Flag they belong to. */
  flagSlug?: string;
  /** Filter Flag Targets by the type of the targeted entity, to find every Feature Flag targeting entities of that type. */
  targetType?: string;
  /** Filter Flag Targets by the ID of the targeted entity, to find every Feature Flag targeting it. */
  targetId?: string;
}
