// This file is auto-generated by oagen. Do not edit.

export const OrganizationDomainStandAloneVerificationStrategy = {
  Dns: 'dns',
  Manual: 'manual',
} as const;

export type OrganizationDomainStandAloneVerificationStrategy =
  (typeof OrganizationDomainStandAloneVerificationStrategy)[keyof typeof OrganizationDomainStandAloneVerificationStrategy];
