// This file is auto-generated by oagen. Do not edit.

import fetch from 'jest-fetch-mock';
import {
  fetchOnce,
  fetchURL,
  fetchMethod,
  fetchBody,
} from '../common/utils/test-utils';
import { WorkOS } from '../workos';

import itContactListFixture from './fixtures/it-contact-list.json';
import itContactFixture from './fixtures/it-contact.json';

const workos = new WorkOS('sk_test_Sz3IQjepeSWaI4cMS4ms4sMuU');

describe('ItContacts', () => {
  beforeEach(() => fetch.resetMocks());

  describe('listItContacts', () => {
    it('returns the expected result', async () => {
      fetchOnce(itContactListFixture);

      const result = await workos.itContacts.listItContacts({
        organizationId: 'test_organizationId',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organizations/test_organizationId/it_contacts',
      );
      expect(result.object).toBe('list');
    });
  });

  describe('createItContact', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(itContactFixture);

      const result = await workos.itContacts.createItContact({
        organizationId: 'test_organizationId',
        email: 'test@example.com',
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organizations/test_organizationId/it_contacts',
      );
      expect(fetchBody()).toEqual(
        expect.objectContaining({ email: 'test@example.com' }),
      );
      expect(result.object).toBe('it_contact');
      expect(result.id).toBe('it_contact_01HXYZ123456789ABCDEFGHIJ');
      expect(result.email).toBe('it-contact@example.com');
      expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
      expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
    });
  });

  describe('deleteItContact', () => {
    it('sends a DELETE request', async () => {
      fetchOnce({}, { status: 204 });

      await workos.itContacts.deleteItContact({
        organizationId: 'test_organizationId',
        contactId: 'test_contactId',
      });

      expect(fetchMethod()).toBe('DELETE');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organizations/test_organizationId/it_contacts/test_contactId',
      );
    });
  });

  describe('inviteItContact', () => {
    it('sends the request', async () => {
      fetchOnce({});

      await workos.itContacts.inviteItContact({
        organizationId: 'test_organizationId',
        contactId: 'test_contactId',
        intents: ['sso'],
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organizations/test_organizationId/it_contacts/test_contactId/invite',
      );
      expect(fetchBody()).toEqual(
        expect.objectContaining({ intents: ['sso'] }),
      );
    });
  });

  describe('revokeItContact', () => {
    it('sends the request', async () => {
      fetchOnce({});

      await workos.itContacts.revokeItContact({
        organizationId: 'test_organizationId',
        contactId: 'test_contactId',
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organizations/test_organizationId/it_contacts/test_contactId/revoke',
      );
    });
  });
});
