// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationFactorEnrolled,
  AuthenticationFactorEnrolledResponse,
} from './authentication-factor-enrolled.interface';
import type {
  AuthenticationChallenge,
  AuthenticationChallengeResponse,
} from './authentication-challenge.interface';

export interface UserAuthenticationFactorEnrollResponse {
  /** The [authentication factor](https://workos.com/docs/reference/authkit/mfa/authentication-factor) object that represents the additional authentication method used on top of the existing authentication strategy. */
  authenticationFactor: AuthenticationFactorEnrolled;
  /** The [authentication challenge](https://workos.com/docs/reference/authkit/mfa/authentication-challenge) object that is used to complete the authentication process. */
  authenticationChallenge: AuthenticationChallenge;
}

export interface UserAuthenticationFactorEnrollResponseWire {
  authentication_factor: AuthenticationFactorEnrolledResponse;
  authentication_challenge: AuthenticationChallengeResponse;
}
