// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type {
  JwksResponse,
  JwksResponseWire,
} from './interfaces/jwks-response.interface';
import { deserializeJwksResponse } from './serializers/jwks-response.serializer';

export class UserManagementSessionTokens {
  constructor(private readonly workos: WorkOS) {}

  /**
   * Get JWKS
   *
   * Returns the JSON Web Key Set (JWKS) containing the public keys used for verifying access tokens.
   * @param clientId - Identifies the application making the request to the WorkOS server. You can obtain your client ID from the [API Keys](https://dashboard.workos.com/api-keys) page in the dashboard.
   * @example "client_01HXYZ123456789ABCDEFGHIJ"
   * @returns {JwksResponse}
   * @throws {NotFoundException} 404
   */
  async jsonWebKeySet(clientId: string): Promise<JwksResponse> {
    const { data } = await this.workos.get<JwksResponseWire>(
      `/sso/jwks/${clientId}`,
    );
    return deserializeJwksResponse(data);
  }
}
