// This file is auto-generated by oagen. Do not edit.

import { sealData, unsealData } from '../common/crypto/seal';
import { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import { AutoPaginatable } from '../common/utils/pagination';
import { getEnv } from '../common/utils/env';
import { toQueryString } from '../common/utils/query-string';
import { Challenge, ChallengeResponse } from '../mfa/interfaces';
import { deserializeChallenge } from '../mfa/serializers';
import {
  FeatureFlag,
  FeatureFlagResponse,
} from '../feature-flags/interfaces/feature-flag.interface';
import { deserializeFeatureFlag } from '../feature-flags/serializers';
import { WorkOS } from '../workos';
import {
  AuthenticateWithCodeAndVerifierOptions,
  AuthenticateWithCodeOptions,
  AuthenticateWithMagicAuthOptions,
  AuthenticateWithPasswordOptions,
  AuthenticateWithRefreshTokenOptions,
  AuthenticateWithSessionOptions,
  AuthenticateWithTotpOptions,
  AuthenticationResponse,
  AuthenticationResponseResponse,
  CreateMagicAuthOptions,
  CreatePasswordResetOptions,
  CreateUserOptions,
  EmailVerification,
  EmailVerificationResponse,
  EnrollAuthFactorOptions,
  ListAuthFactorsOptions,
  ListSessionsOptions,
  ListUsersOptions,
  ListUserFeatureFlagsOptions,
  LogoutURLOptions,
  MagicAuth,
  MagicAuthResponse,
  PasswordReset,
  PasswordResetResponse,
  ResetPasswordOptions,
  SendVerificationEmailOptions,
  SerializedAuthenticateWithCodeAndVerifierOptions,
  SerializedAuthenticateWithCodeOptions,
  SerializedAuthenticateWithMagicAuthOptions,
  SerializedAuthenticateWithPasswordOptions,
  SerializedAuthenticateWithRefreshTokenOptions,
  SerializedAuthenticateWithRefreshTokenPublicClientOptions,
  SerializedAuthenticateWithTotpOptions,
  SerializedCreateMagicAuthOptions,
  SerializedCreatePasswordResetOptions,
  SerializedCreateUserOptions,
  SerializedListSessionsOptions,
  SerializedListUsersOptions,
  SerializedResetPasswordOptions,
  SerializedVerifyEmailOptions,
  Session,
  SessionResponse,
  UpdateUserOptions,
  User,
  UserResponse,
  VerifyEmailOptions,
} from './interfaces';
import {
  AuthenticateWithEmailVerificationOptions,
  SerializedAuthenticateWithEmailVerificationOptions,
} from './interfaces/authenticate-with-email-verification-options.interface';
import {
  AuthenticateWithOrganizationSelectionOptions,
  SerializedAuthenticateWithOrganizationSelectionOptions,
} from './interfaces/authenticate-with-organization-selection.interface';
import {
  AccessToken,
  AuthenticateWithSessionCookieFailedResponse,
  AuthenticateWithSessionCookieFailureReason,
  AuthenticateWithSessionCookieOptions,
  AuthenticateWithSessionCookieSuccessResponse,
  SessionCookieData,
} from './interfaces/authenticate-with-session-cookie.interface';
import {
  PKCEAuthorizationURLResult,
  UserManagementAuthorizationURLOptions,
} from './interfaces/authorization-url-options.interface';
import {
  CreateOrganizationMembershipOptions,
  SerializedCreateOrganizationMembershipOptions,
} from './interfaces/create-organization-membership-options.interface';
import {
  Factor,
  FactorResponse,
  FactorWithSecrets,
  FactorWithSecretsResponse,
} from './interfaces/factor.interface';
import { Identity, IdentityResponse } from './interfaces/identity.interface';
import {
  Invitation,
  InvitationResponse,
} from './interfaces/invitation.interface';
import {
  ListInvitationsOptions,
  SerializedListInvitationsOptions,
} from './interfaces/list-invitations-options.interface';
import {
  ListOrganizationMembershipsOptions,
  SerializedListOrganizationMembershipsOptions,
} from './interfaces/list-organization-memberships-options.interface';
import {
  OrganizationMembership,
  OrganizationMembershipResponse,
} from './interfaces/organization-membership.interface';
import {
  RevokeSessionOptions,
  SerializedRevokeSessionOptions,
  serializeRevokeSessionOptions,
} from './interfaces/revoke-session-options.interface';
import {
  ResendInvitationOptions,
  SerializedResendInvitationOptions,
} from './interfaces/resend-invitation-options.interface';
import {
  SendInvitationOptions,
  SerializedSendInvitationOptions,
} from './interfaces/send-invitation-options.interface';
import { SessionHandlerOptions } from './interfaces/session-handler-options.interface';
import {
  SerializedUpdateOrganizationMembershipOptions,
  UpdateOrganizationMembershipOptions,
} from './interfaces/update-organization-membership-options.interface';
import {
  deserializeAuthenticationResponse,
  deserializeEmailVerification,
  deserializeFactorWithSecrets,
  deserializeMagicAuth,
  deserializePasswordReset,
  deserializeSession,
  deserializeUser,
  serializeAuthenticateWithCodeAndVerifierOptions,
  serializeAuthenticateWithCodeOptions,
  serializeAuthenticateWithMagicAuthOptions,
  serializeAuthenticateWithPasswordOptions,
  serializeAuthenticateWithRefreshTokenOptions,
  serializeAuthenticateWithRefreshTokenPublicClientOptions,
  serializeAuthenticateWithTotpOptions,
  serializeCreateMagicAuthOptions,
  serializeCreatePasswordResetOptions,
  serializeCreateUserOptions,
  serializeEnrollAuthFactorOptions,
  serializeListSessionsOptions,
  serializeResetPasswordOptions,
  serializeUpdateUserOptions,
} from './serializers';
import { serializeAuthenticateWithEmailVerificationOptions } from './serializers/authenticate-with-email-verification.serializer';
import { serializeAuthenticateWithOrganizationSelectionOptions } from './serializers/authenticate-with-organization-selection-options.serializer';
import { serializeCreateOrganizationMembershipOptions } from './serializers/create-organization-membership-options.serializer';
import { deserializeFactor } from './serializers/factor.serializer';
import { deserializeIdentities } from './serializers/identity.serializer';
import { deserializeInvitation } from './serializers/invitation.serializer';
import { serializeListInvitationsOptions } from './serializers/list-invitations-options.serializer';
import { serializeListOrganizationMembershipsOptions } from './serializers/list-organization-memberships-options.serializer';
import { serializeListUsersOptions } from './serializers/list-users-options.serializer';
import { serializeResendInvitationOptions } from './serializers/resend-invitation-options.serializer';
import { deserializeOrganizationMembership } from './serializers/organization-membership.serializer';
import { serializeSendInvitationOptions } from './serializers/send-invitation-options.serializer';
import { serializeUpdateOrganizationMembershipOptions } from './serializers/update-organization-membership-options.serializer';
import { CookieSession } from './session';
import { getJose } from '../utils/jose';
import type { UserManagementAuthenticationScreenHint } from './interfaces/user-management-authentication-screen-hint.interface';
import type { UserManagementAuthenticationProvider } from './interfaces/user-management-authentication-provider.interface';

export class UserManagement {
  private _jwks:
    | ReturnType<typeof import('jose').createRemoteJWKSet>
    | undefined;
  public clientId: string | undefined;

  constructor(private readonly workos: WorkOS) {
    const { clientId } = workos.options;

    this.clientId = clientId;
  }

  /**
   * Resolve clientId from method options or fall back to constructor-provided value.
   * @throws TypeError if clientId is not available from either source
   */
  private resolveClientId(clientId?: string): string {
    const resolved = clientId ?? this.clientId;
    if (!resolved) {
      throw new TypeError(
        'clientId is required. Provide it in method options or when initializing WorkOS.',
      );
    }
    return resolved;
  }

  async getJWKS(): Promise<
    ReturnType<typeof import('jose').createRemoteJWKSet> | undefined
  > {
    const { createRemoteJWKSet } = await getJose();
    if (!this.clientId) {
      return;
    }

    // Set the JWKS URL. This is used to verify if the JWT is still valid
    this._jwks ??= createRemoteJWKSet(new URL(this.getJwksUrl(this.clientId)), {
      cooldownDuration: 1000 * 60 * 5,
    });

    return this._jwks;
  }

  /**
   * Loads a sealed session using the provided session data and cookie password.
   *
   * @param options - The options for loading the sealed session.
   * @param options.sessionData - The sealed session data.
   * @param options.cookiePassword - The password used to encrypt the session data.
   * @returns The session class.
   */
  loadSealedSession(options: {
    sessionData: string;
    cookiePassword: string;
  }): CookieSession {
    return new CookieSession(this, options.sessionData, options.cookiePassword);
  }

  /**
   * Get a user
   *
   * Get the details of an existing user.
   * @returns {User}
   * @throws {NotFoundException} 404
   */
  async getUser(userId: string): Promise<User> {
    const { data } = await this.workos.get<UserResponse>(
      `/user_management/users/${userId}`,
    );

    return deserializeUser(data);
  }

  /**
   * Get a user by external ID
   *
   * Get the details of an existing user by an [external identifier](https://workos.com/docs/authkit/metadata/external-identifiers).
   * @param externalId - The external ID of the user.
   * @example "f1ffa2b2-c20b-4d39-be5c-212726e11222"
   * @returns {User}
   * @throws {NotFoundException} 404
   */
  async getUserByExternalId(externalId: string): Promise<User> {
    const { data } = await this.workos.get<UserResponse>(
      `/user_management/users/external_id/${externalId}`,
    );

    return deserializeUser(data);
  }

  /**
   * List users
   *
   * Get a list of all of your existing users matching the criteria specified.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<User>}
   * @throws {UnprocessableEntityException} 422
   */
  async listUsers(
    options?: ListUsersOptions,
  ): Promise<AutoPaginatable<User, SerializedListUsersOptions>> {
    return new AutoPaginatable(
      await fetchAndDeserialize<UserResponse, User>(
        this.workos,
        '/user_management/users',
        deserializeUser,
        options ? serializeListUsersOptions(options) : undefined,
      ),
      (params) =>
        fetchAndDeserialize<UserResponse, User>(
          this.workos,
          '/user_management/users',
          deserializeUser,
          params,
        ),
      options ? serializeListUsersOptions(options) : undefined,
    );
  }

  /**
   * List users
   *
   * Get a list of all of your existing users matching the criteria specified.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<User>}
   * @throws {UnprocessableEntityException} 422
   */
  async createUser(payload: CreateUserOptions): Promise<User> {
    const { data } = await this.workos.post<
      UserResponse,
      SerializedCreateUserOptions
    >('/user_management/users', serializeCreateUserOptions(payload));

    return deserializeUser(data);
  }

  /** Authenticate with magic auth. */
  async authenticateWithMagicAuth(
    payload: AuthenticateWithMagicAuthOptions,
  ): Promise<AuthenticationResponse> {
    const { session, clientId, ...remainingPayload } = payload;
    const resolvedClientId = this.resolveClientId(clientId);

    const { data } = await this.workos.post<
      AuthenticationResponseResponse,
      SerializedAuthenticateWithMagicAuthOptions
    >(
      '/user_management/authenticate',
      serializeAuthenticateWithMagicAuthOptions({
        ...remainingPayload,
        clientId: resolvedClientId,
        clientSecret: this.workos.key,
      }),
    );

    return this.prepareAuthenticationResponse({
      authenticationResponse: deserializeAuthenticationResponse(data),
      session,
    });
  }

  /** Authenticate with password. */
  async authenticateWithPassword(
    payload: AuthenticateWithPasswordOptions,
  ): Promise<AuthenticationResponse> {
    const { session, clientId, ...remainingPayload } = payload;
    const resolvedClientId = this.resolveClientId(clientId);

    const { data } = await this.workos.post<
      AuthenticationResponseResponse,
      SerializedAuthenticateWithPasswordOptions
    >(
      '/user_management/authenticate',
      serializeAuthenticateWithPasswordOptions({
        ...remainingPayload,
        clientId: resolvedClientId,
        clientSecret: this.workos.key,
      }),
    );

    return this.prepareAuthenticationResponse({
      authenticationResponse: deserializeAuthenticationResponse(data),
      session,
    });
  }

  /** Authenticate with code. */
  async authenticateWithCode(
    payload: AuthenticateWithCodeOptions,
  ): Promise<AuthenticationResponse> {
    const { session, clientId, codeVerifier, ...remainingPayload } = payload;
    const resolvedClientId = this.resolveClientId(clientId);

    // Validate codeVerifier is not an empty string (common mistake)
    if (codeVerifier !== undefined && codeVerifier.trim() === '') {
      throw new TypeError(
        'codeVerifier cannot be an empty string. ' +
          'Generate a valid PKCE pair using workos.pkce.generate().',
      );
    }

    const hasApiKey = !!this.workos.key;
    const hasPKCE = !!codeVerifier;

    if (!hasPKCE && !hasApiKey) {
      throw new TypeError(
        'authenticateWithCode requires either a codeVerifier (for public clients) ' +
          'or an API key configured on the WorkOS instance (for confidential clients).',
      );
    }

    const { data } = await this.workos.post<
      AuthenticationResponseResponse,
      SerializedAuthenticateWithCodeOptions
    >(
      '/user_management/authenticate',
      serializeAuthenticateWithCodeOptions({
        ...remainingPayload,
        clientId: resolvedClientId,
        codeVerifier,
        clientSecret: hasApiKey ? this.workos.key : undefined,
      }),
      { skipApiKeyCheck: !hasApiKey },
    );

    return this.prepareAuthenticationResponse({
      authenticationResponse: deserializeAuthenticationResponse(data),
      session,
    });
  }

  /**
   * Authenticate
   *
   * Authenticate a user with a specified [authentication method](https://workos.com/docs/reference/authkit/authentication).
   * @param payload - The request body.
   * @returns {AuthenticateResponse}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async authenticateWithCodeAndVerifier(
    payload: AuthenticateWithCodeAndVerifierOptions,
  ): Promise<AuthenticationResponse> {
    const { session, clientId, ...remainingPayload } = payload;
    const resolvedClientId = this.resolveClientId(clientId);

    const { data } = await this.workos.post<
      AuthenticationResponseResponse,
      SerializedAuthenticateWithCodeAndVerifierOptions
    >(
      '/user_management/authenticate',
      serializeAuthenticateWithCodeAndVerifierOptions({
        ...remainingPayload,
        clientId: resolvedClientId,
      }),
      { skipApiKeyCheck: true },
    );

    return this.prepareAuthenticationResponse({
      authenticationResponse: deserializeAuthenticationResponse(data),
      session,
    });
  }

  /** Authenticate with refresh token. */
  async authenticateWithRefreshToken(
    payload: AuthenticateWithRefreshTokenOptions,
  ): Promise<AuthenticationResponse> {
    const { session, clientId, ...remainingPayload } = payload;
    const resolvedClientId = this.resolveClientId(clientId);
    const isPublicClient = !this.workos.key;

    const body = isPublicClient
      ? serializeAuthenticateWithRefreshTokenPublicClientOptions({
          ...remainingPayload,
          clientId: resolvedClientId,
        })
      : serializeAuthenticateWithRefreshTokenOptions({
          ...remainingPayload,
          clientId: resolvedClientId,
          clientSecret: this.workos.key,
        });

    const { data } = await this.workos.post<
      AuthenticationResponseResponse,
      | SerializedAuthenticateWithRefreshTokenOptions
      | SerializedAuthenticateWithRefreshTokenPublicClientOptions
    >('/user_management/authenticate', body, {
      skipApiKeyCheck: isPublicClient,
    });

    return this.prepareAuthenticationResponse({
      authenticationResponse: deserializeAuthenticationResponse(data),
      session,
    });
  }

  /** Authenticate with totp. */
  async authenticateWithTotp(
    payload: AuthenticateWithTotpOptions,
  ): Promise<AuthenticationResponse> {
    const { session, clientId, ...remainingPayload } = payload;
    const resolvedClientId = this.resolveClientId(clientId);

    const { data } = await this.workos.post<
      AuthenticationResponseResponse,
      SerializedAuthenticateWithTotpOptions
    >(
      '/user_management/authenticate',
      serializeAuthenticateWithTotpOptions({
        ...remainingPayload,
        clientId: resolvedClientId,
        clientSecret: this.workos.key,
      }),
    );

    return this.prepareAuthenticationResponse({
      authenticationResponse: deserializeAuthenticationResponse(data),
      session,
    });
  }

  /** Authenticate with email verification. */
  async authenticateWithEmailVerification(
    payload: AuthenticateWithEmailVerificationOptions,
  ): Promise<AuthenticationResponse> {
    const { session, clientId, ...remainingPayload } = payload;
    const resolvedClientId = this.resolveClientId(clientId);

    const { data } = await this.workos.post<
      AuthenticationResponseResponse,
      SerializedAuthenticateWithEmailVerificationOptions
    >(
      '/user_management/authenticate',
      serializeAuthenticateWithEmailVerificationOptions({
        ...remainingPayload,
        clientId: resolvedClientId,
        clientSecret: this.workos.key,
      }),
    );

    return this.prepareAuthenticationResponse({
      authenticationResponse: deserializeAuthenticationResponse(data),
      session,
    });
  }

  /** Authenticate with organization selection. */
  async authenticateWithOrganizationSelection(
    payload: AuthenticateWithOrganizationSelectionOptions,
  ): Promise<AuthenticationResponse> {
    const { session, clientId, ...remainingPayload } = payload;
    const resolvedClientId = this.resolveClientId(clientId);

    const { data } = await this.workos.post<
      AuthenticationResponseResponse,
      SerializedAuthenticateWithOrganizationSelectionOptions
    >(
      '/user_management/authenticate',
      serializeAuthenticateWithOrganizationSelectionOptions({
        ...remainingPayload,
        clientId: resolvedClientId,
        clientSecret: this.workos.key,
      }),
    );

    return this.prepareAuthenticationResponse({
      authenticationResponse: deserializeAuthenticationResponse(data),
      session,
    });
  }

  async authenticateWithSessionCookie({
    sessionData,
    cookiePassword = getEnv('WORKOS_COOKIE_PASSWORD'),
  }: AuthenticateWithSessionCookieOptions): Promise<
    | AuthenticateWithSessionCookieSuccessResponse
    | AuthenticateWithSessionCookieFailedResponse
  > {
    if (!cookiePassword) {
      throw new Error('Cookie password is required');
    }

    const jwks = await this.getJWKS();

    if (!jwks) {
      throw new Error('Must provide clientId to initialize JWKS');
    }

    const { decodeJwt } = await getJose();

    if (!sessionData) {
      return {
        authenticated: false,
        reason:
          AuthenticateWithSessionCookieFailureReason.NO_SESSION_COOKIE_PROVIDED,
      };
    }

    const session = await unsealData<SessionCookieData>(sessionData, {
      password: cookiePassword,
    });

    if (!session.accessToken) {
      return {
        authenticated: false,
        reason:
          AuthenticateWithSessionCookieFailureReason.INVALID_SESSION_COOKIE,
      };
    }

    if (!(await this.isValidJwt(session.accessToken))) {
      return {
        authenticated: false,
        reason: AuthenticateWithSessionCookieFailureReason.INVALID_JWT,
      };
    }

    const {
      sid: sessionId,
      org_id: organizationId,
      role,
      roles,
      permissions,
      entitlements,
      feature_flags: featureFlags,
    } = decodeJwt<AccessToken>(session.accessToken);

    return {
      authenticated: true,
      sessionId,
      organizationId,
      role,
      roles,
      user: session.user,
      permissions,
      entitlements,
      featureFlags,
      accessToken: session.accessToken,
      authenticationMethod: session.authenticationMethod,
    };
  }

  private async isValidJwt(accessToken: string): Promise<boolean> {
    const jwks = await this.getJWKS();
    const { jwtVerify } = await getJose();
    if (!jwks) {
      throw new Error('Must provide clientId to initialize JWKS');
    }

    try {
      await jwtVerify(accessToken, jwks);
      return true;
    } catch (e) {
      // Only treat as invalid JWT if it's an actual JWT/JWS error from jose
      // Network errors, crypto failures, etc. should propagate
      if (
        e instanceof Error &&
        'code' in e &&
        typeof e.code === 'string' &&
        (e.code.startsWith('ERR_JWT_') || e.code.startsWith('ERR_JWS_'))
      ) {
        return false;
      }
      throw e;
    }
  }

  private async prepareAuthenticationResponse({
    authenticationResponse,
    session,
  }: {
    authenticationResponse: AuthenticationResponse;
    session?: AuthenticateWithSessionOptions;
  }): Promise<AuthenticationResponse> {
    if (session?.sealSession) {
      if (!this.workos.key) {
        throw new Error(
          'Session sealing requires server-side usage with an API key. ' +
            'Public clients should store tokens directly ' +
            '(e.g., secure storage on mobile, keychain on desktop).',
        );
      }

      return {
        ...authenticationResponse,
        sealedSession: await this.sealSessionDataFromAuthenticationResponse({
          authenticationResponse,
          cookiePassword: session.cookiePassword,
        }),
      };
    }

    return authenticationResponse;
  }

  private async sealSessionDataFromAuthenticationResponse({
    authenticationResponse,
    cookiePassword,
  }: {
    authenticationResponse: AuthenticationResponse;
    cookiePassword?: string;
  }): Promise<string> {
    if (!cookiePassword) {
      throw new Error('Cookie password is required');
    }

    const { decodeJwt } = await getJose();

    const { org_id: organizationIdFromAccessToken } = decodeJwt<AccessToken>(
      authenticationResponse.accessToken,
    );

    const sessionData: SessionCookieData = {
      organizationId: organizationIdFromAccessToken,
      user: authenticationResponse.user,
      accessToken: authenticationResponse.accessToken,
      refreshToken: authenticationResponse.refreshToken,
      authenticationMethod: authenticationResponse.authenticationMethod,
      impersonator: authenticationResponse.impersonator,
    };

    return sealData(sessionData, {
      password: cookiePassword,
    });
  }

  async getSessionFromCookie({
    sessionData,
    cookiePassword = getEnv('WORKOS_COOKIE_PASSWORD'),
  }: SessionHandlerOptions): Promise<SessionCookieData | undefined> {
    if (!cookiePassword) {
      throw new Error('Cookie password is required');
    }

    if (sessionData) {
      return unsealData<SessionCookieData>(sessionData, {
        password: cookiePassword,
      });
    }

    return undefined;
  }

  /**
   * Get an email verification code
   *
   * Get the details of an existing email verification code that can be used to send an email to a user for verification.
   * @returns {EmailVerification}
   * @throws {NotFoundException} 404
   */
  async getEmailVerification(
    emailVerificationId: string,
  ): Promise<EmailVerification> {
    const { data } = await this.workos.get<EmailVerificationResponse>(
      `/user_management/email_verification/${emailVerificationId}`,
    );

    return deserializeEmailVerification(data);
  }

  /**
   * Send verification email
   *
   * Sends an email that contains a one-time code used to verify a user’s email address.
   * @param id - The ID of the user.
   * @example "user_01E4ZCR3C56J083X43JQXF3JK5"
   * @returns {SendVerificationEmailResponse}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {RateLimitExceededException} 429
   */
  async sendVerificationEmail({
    userId,
  }: SendVerificationEmailOptions): Promise<{ user: User }> {
    const { data } = await this.workos.post<{ user: UserResponse }>(
      `/user_management/users/${userId}/email_verification/send`,
      {},
    );

    return { user: deserializeUser(data.user) };
  }

  /**
   * Get Magic Auth code details
   *
   * Get the details of an existing [Magic Auth](https://workos.com/docs/reference/authkit/magic-auth) code that can be used to send an email to a user for authentication.
   * @returns {MagicAuth}
   * @throws {NotFoundException} 404
   */
  async getMagicAuth(magicAuthId: string): Promise<MagicAuth> {
    const { data } = await this.workos.get<MagicAuthResponse>(
      `/user_management/magic_auth/${magicAuthId}`,
    );

    return deserializeMagicAuth(data);
  }

  /**
   * Create a Magic Auth code
   *
   * Creates a one-time authentication code that can be sent to the user's email address. The code expires in 10 minutes. To verify the code, [authenticate the user with Magic Auth](https://workos.com/docs/reference/authkit/authentication/magic-auth).
   * @param payload - Object containing email.
   * @returns {MagicAuth}
   * @throws {BadRequestException} 400
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async createMagicAuth(options: CreateMagicAuthOptions): Promise<MagicAuth> {
    const { data } = await this.workos.post<
      MagicAuthResponse,
      SerializedCreateMagicAuthOptions
    >(
      '/user_management/magic_auth',
      serializeCreateMagicAuthOptions({
        ...options,
      }),
    );

    return deserializeMagicAuth(data);
  }

  /**
   * Verify email
   *
   * Verifies an email address using the one-time code received by the user.
   * @param id - The ID of the user.
   * @example "user_01E4ZCR3C56J083X43JQXF3JK5"
   * @param payload - Object containing code.
   * @returns {VerifyEmailResponse}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async verifyEmail({
    code,
    userId,
  }: VerifyEmailOptions): Promise<{ user: User }> {
    const { data } = await this.workos.post<
      { user: UserResponse },
      SerializedVerifyEmailOptions
    >(`/user_management/users/${userId}/email_verification/confirm`, {
      code,
    });

    return { user: deserializeUser(data.user) };
  }

  /**
   * Get a password reset token
   *
   * Get the details of an existing password reset token that can be used to reset a user's password.
   * @returns {PasswordReset}
   * @throws {NotFoundException} 404
   */
  async getPasswordReset(passwordResetId: string): Promise<PasswordReset> {
    const { data } = await this.workos.get<PasswordResetResponse>(
      `/user_management/password_reset/${passwordResetId}`,
    );

    return deserializePasswordReset(data);
  }

  /**
   * Create a password reset token
   *
   * Creates a one-time token that can be used to reset a user's password.
   * @param payload - Object containing email.
   * @returns {PasswordReset}
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   * @throws {RateLimitExceededException} 429
   */
  async createPasswordReset(
    options: CreatePasswordResetOptions,
  ): Promise<PasswordReset> {
    const { data } = await this.workos.post<
      PasswordResetResponse,
      SerializedCreatePasswordResetOptions
    >(
      '/user_management/password_reset',
      serializeCreatePasswordResetOptions({
        ...options,
      }),
    );

    return deserializePasswordReset(data);
  }

  /**
   * Reset the password
   *
   * Sets a new password using the `token` query parameter from the link that the user received. Successfully resetting the password will verify a user's email, if it hasn't been verified yet.
   * @param payload - Object containing token, newPassword.
   * @returns {ResetPasswordResponse}
   * @throws {BadRequestException} 400
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async resetPassword(payload: ResetPasswordOptions): Promise<{ user: User }> {
    const { data } = await this.workos.post<
      { user: UserResponse },
      SerializedResetPasswordOptions
    >(
      '/user_management/password_reset/confirm',
      serializeResetPasswordOptions(payload),
    );

    return { user: deserializeUser(data.user) };
  }

  /**
   * Update a user
   *
   * Updates properties of a user. The omitted properties will be left unchanged.
   * @param payload - The request body.
   * @returns {User}
   * @throws {BadRequestException} 400
   * @throws {UnprocessableEntityException} 422
   */
  async updateUser(payload: UpdateUserOptions): Promise<User> {
    const { data } = await this.workos.put<UserResponse>(
      `/user_management/users/${payload.userId}`,
      serializeUpdateUserOptions(payload),
    );

    return deserializeUser(data);
  }

  async enrollAuthFactor(payload: EnrollAuthFactorOptions): Promise<{
    authenticationFactor: FactorWithSecrets;
    authenticationChallenge: Challenge;
  }> {
    const { data } = await this.workos.post<{
      authentication_factor: FactorWithSecretsResponse;
      authentication_challenge: ChallengeResponse;
    }>(
      `/user_management/users/${payload.userId}/auth_factors`,
      serializeEnrollAuthFactorOptions(payload),
    );

    return {
      authenticationFactor: deserializeFactorWithSecrets(
        data.authentication_factor,
      ),
      authenticationChallenge: deserializeChallenge(
        data.authentication_challenge,
      ),
    };
  }

  async listAuthFactors(
    options: ListAuthFactorsOptions,
  ): Promise<AutoPaginatable<Factor, PaginationOptions>> {
    const { userId, ...restOfOptions } = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<FactorResponse, Factor>(
        this.workos,
        `/user_management/users/${userId}/auth_factors`,
        deserializeFactor,
        restOfOptions,
      ),
      (params) =>
        fetchAndDeserialize<FactorResponse, Factor>(
          this.workos,
          `/user_management/users/${userId}/auth_factors`,
          deserializeFactor,
          params,
        ),
      restOfOptions,
    );
  }

  async listUserFeatureFlags(
    options: ListUserFeatureFlagsOptions,
  ): Promise<AutoPaginatable<FeatureFlag>> {
    const { userId, ...paginationOptions } = options;

    return new AutoPaginatable(
      await fetchAndDeserialize<FeatureFlagResponse, FeatureFlag>(
        this.workos,
        `/user_management/users/${userId}/feature-flags`,
        deserializeFeatureFlag,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<FeatureFlagResponse, FeatureFlag>(
          this.workos,
          `/user_management/users/${userId}/feature-flags`,
          deserializeFeatureFlag,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * List sessions
   *
   * Get a list of all active sessions for a specific user.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<UserSessionsListItem>}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listSessions(
    userId: string,
    options?: ListSessionsOptions,
  ): Promise<AutoPaginatable<Session, SerializedListSessionsOptions>> {
    return new AutoPaginatable(
      await fetchAndDeserialize<SessionResponse, Session>(
        this.workos,
        `/user_management/users/${userId}/sessions`,
        deserializeSession,
        options ? serializeListSessionsOptions(options) : undefined,
      ),
      (params) =>
        fetchAndDeserialize<SessionResponse, Session>(
          this.workos,
          `/user_management/users/${userId}/sessions`,
          deserializeSession,
          params,
        ),
      options ? serializeListSessionsOptions(options) : undefined,
    );
  }

  /**
   * Delete a user
   *
   * Permanently deletes a user in the current environment. It cannot be undone.
   * @returns {void}
   * @throws {NotFoundException} 404
   */
  async deleteUser(userId: string) {
    await this.workos.delete(`/user_management/users/${userId}`);
  }

  /**
   * Get user identities
   *
   * Get a list of identities associated with the user. A user can have multiple associated identities after going through [identity linking](https://workos.com/docs/authkit/identity-linking). Currently only OAuth identities are supported. More provider types may be added in the future.
   * @param id - The unique ID of the user.
   * @example "user_01E4ZCR3C56J083X43JQXF3JK5"
   * @returns {UserIdentitiesGetItem}
   * @throws {NotFoundException} 404
   */
  async getUserIdentities(userId: string): Promise<Identity[]> {
    if (!userId) {
      throw new TypeError(`Incomplete arguments. Need to specify 'userId'.`);
    }

    const { data } = await this.workos.get<IdentityResponse[]>(
      `/user_management/users/${userId}/identities`,
    );

    return deserializeIdentities(data);
  }

  /**
   * Get an organization membership
   *
   * Get the details of an existing organization membership.
   * @returns {UserOrganizationMembership}
   * @throws {NotFoundException} 404
   */
  async getOrganizationMembership(
    organizationMembershipId: string,
  ): Promise<OrganizationMembership> {
    const { data } = await this.workos.get<OrganizationMembershipResponse>(
      `/user_management/organization_memberships/${organizationMembershipId}`,
    );

    return deserializeOrganizationMembership(data);
  }

  /**
   * List organization memberships
   *
   * Get a list of all organization memberships matching the criteria specified. At least one of `user_id` or `organization_id` must be provided. By default only active memberships are returned. Use the `statuses` parameter to filter by other statuses.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<UserOrganizationMembership>}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async listOrganizationMemberships(
    options: ListOrganizationMembershipsOptions,
  ): Promise<
    AutoPaginatable<
      OrganizationMembership,
      SerializedListOrganizationMembershipsOptions
    >
  > {
    const serializedOptions =
      serializeListOrganizationMembershipsOptions(options);

    return new AutoPaginatable(
      await fetchAndDeserialize<
        OrganizationMembershipResponse,
        OrganizationMembership
      >(
        this.workos,
        '/user_management/organization_memberships',
        deserializeOrganizationMembership,
        serializedOptions,
      ),
      (params) =>
        fetchAndDeserialize<
          OrganizationMembershipResponse,
          OrganizationMembership
        >(
          this.workos,
          '/user_management/organization_memberships',
          deserializeOrganizationMembership,
          params,
        ),
      serializedOptions,
    );
  }

  /**
   * List organization memberships
   *
   * Get a list of all organization memberships matching the criteria specified. At least one of `user_id` or `organization_id` must be provided. By default only active memberships are returned. Use the `statuses` parameter to filter by other statuses.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<UserOrganizationMembership>}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async createOrganizationMembership(
    options: CreateOrganizationMembershipOptions,
  ): Promise<OrganizationMembership> {
    const { data } = await this.workos.post<
      OrganizationMembershipResponse,
      SerializedCreateOrganizationMembershipOptions
    >(
      '/user_management/organization_memberships',
      serializeCreateOrganizationMembershipOptions(options),
    );

    return deserializeOrganizationMembership(data);
  }

  /**
   * Update an organization membership
   *
   * Update the details of an existing organization membership.
   * @param payload - The request body.
   * @returns {UserOrganizationMembership}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updateOrganizationMembership(
    organizationMembershipId: string,
    options: UpdateOrganizationMembershipOptions,
  ): Promise<OrganizationMembership> {
    const { data } = await this.workos.put<
      OrganizationMembershipResponse,
      SerializedUpdateOrganizationMembershipOptions
    >(
      `/user_management/organization_memberships/${organizationMembershipId}`,
      serializeUpdateOrganizationMembershipOptions(options),
    );

    return deserializeOrganizationMembership(data);
  }

  /**
   * Delete an organization membership
   *
   * Permanently deletes an existing organization membership. It cannot be undone.
   * @returns {void}
   * @throws {NotFoundException} 404
   */
  async deleteOrganizationMembership(
    organizationMembershipId: string,
  ): Promise<void> {
    await this.workos.delete(
      `/user_management/organization_memberships/${organizationMembershipId}`,
    );
  }

  /**
   * Deactivate an organization membership
   *
   * Deactivates an `active` organization membership. Emits an [organization_membership.updated](https://workos.com/docs/events/organization-membership) event upon successful deactivation.
   *
   * - Deactivating an `inactive` membership is a no-op and does not emit an event.
   * - Deactivating a `pending` membership returns an error. This membership should be [deleted](https://workos.com/docs/reference/authkit/organization-membership/delete) instead.
   *
   * See the [membership management documentation](https://workos.com/docs/authkit/users-organizations/organizations/membership-management) for additional details.
   * @returns {OrganizationMembership}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async deactivateOrganizationMembership(
    organizationMembershipId: string,
  ): Promise<OrganizationMembership> {
    const { data } = await this.workos.put<OrganizationMembershipResponse>(
      `/user_management/organization_memberships/${organizationMembershipId}/deactivate`,
      {},
    );

    return deserializeOrganizationMembership(data);
  }

  /**
   * Reactivate an organization membership
   *
   * Reactivates an `inactive` organization membership, retaining the pre-existing role(s). Emits an [organization_membership.updated](https://workos.com/docs/events/organization-membership) event upon successful reactivation.
   *
   * - Reactivating an `active` membership is a no-op and does not emit an event.
   * - Reactivating a `pending` membership returns an error. The user needs to [accept the invitation](https://workos.com/docs/authkit/invitations) instead.
   *
   * See the [membership management documentation](https://workos.com/docs/authkit/users-organizations/organizations/membership-management) for additional details.
   * @returns {UserOrganizationMembership}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async reactivateOrganizationMembership(
    organizationMembershipId: string,
  ): Promise<OrganizationMembership> {
    const { data } = await this.workos.put<OrganizationMembershipResponse>(
      `/user_management/organization_memberships/${organizationMembershipId}/reactivate`,
      {},
    );

    return deserializeOrganizationMembership(data);
  }

  /**
   * Get an invitation
   *
   * Get the details of an existing invitation.
   * @returns {UserInvite}
   * @throws {NotFoundException} 404
   */
  async getInvitation(invitationId: string): Promise<Invitation> {
    const { data } = await this.workos.get<InvitationResponse>(
      `/user_management/invitations/${invitationId}`,
    );

    return deserializeInvitation(data);
  }

  /**
   * Find an invitation by token
   *
   * Retrieve an existing invitation using the token.
   * @param token - The token used to accept the invitation.
   * @example "Z1uX3RbwcIl5fIGJJJCXXisdI"
   * @returns {UserInvite}
   * @throws {NotFoundException} 404
   */
  async findInvitationByToken(invitationToken: string): Promise<Invitation> {
    const { data } = await this.workos.get<InvitationResponse>(
      `/user_management/invitations/by_token/${invitationToken}`,
    );

    return deserializeInvitation(data);
  }

  /**
   * List invitations
   *
   * Get a list of all of invitations matching the criteria specified.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<UserInvite>}
   * @throws {UnprocessableEntityException} 422
   */
  async listInvitations(
    options: ListInvitationsOptions,
  ): Promise<AutoPaginatable<Invitation, SerializedListInvitationsOptions>> {
    return new AutoPaginatable(
      await fetchAndDeserialize<InvitationResponse, Invitation>(
        this.workos,
        '/user_management/invitations',
        deserializeInvitation,
        options ? serializeListInvitationsOptions(options) : undefined,
      ),
      (params) =>
        fetchAndDeserialize<InvitationResponse, Invitation>(
          this.workos,
          '/user_management/invitations',
          deserializeInvitation,
          params,
        ),
      options ? serializeListInvitationsOptions(options) : undefined,
    );
  }

  /**
   * List invitations
   *
   * Get a list of all of invitations matching the criteria specified.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<UserInvite>}
   * @throws {UnprocessableEntityException} 422
   */
  async sendInvitation(payload: SendInvitationOptions): Promise<Invitation> {
    const { data } = await this.workos.post<
      InvitationResponse,
      SerializedSendInvitationOptions
    >(
      '/user_management/invitations',
      serializeSendInvitationOptions({
        ...payload,
      }),
    );

    return deserializeInvitation(data);
  }

  /**
   * Accept an invitation
   *
   * Accepts an invitation and, if linked to an organization, activates the user's membership in that organization.
   * @returns {Invitation}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   */
  async acceptInvitation(invitationId: string): Promise<Invitation> {
    const { data } = await this.workos.post<InvitationResponse, any>(
      `/user_management/invitations/${invitationId}/accept`,
      null,
    );

    return deserializeInvitation(data);
  }

  /**
   * Revoke an invitation
   *
   * Revokes an existing invitation.
   * @returns {Invitation}
   * @throws {BadRequestException} 400
   */
  async revokeInvitation(invitationId: string): Promise<Invitation> {
    const { data } = await this.workos.post<InvitationResponse, any>(
      `/user_management/invitations/${invitationId}/revoke`,
      null,
    );

    return deserializeInvitation(data);
  }

  /**
   * Resend an invitation
   *
   * Resends an invitation email to the recipient. The invitation must be in a pending state.
   * @param payload - The request body.
   * @returns {UserInvite}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async resendInvitation(
    invitationId: string,
    options?: ResendInvitationOptions,
  ): Promise<Invitation> {
    const { data } = await this.workos.post<
      InvitationResponse,
      SerializedResendInvitationOptions
    >(
      `/user_management/invitations/${invitationId}/resend`,
      options ? serializeResendInvitationOptions(options) : {},
    );

    return deserializeInvitation(data);
  }

  /**
   * Revoke Session
   *
   * Revoke a [user session](https://workos.com/docs/reference/authkit/session).
   * @param payload - Object containing sessionId.
   * @returns {void}
   * @throws {BadRequestException} 400
   */
  async revokeSession(payload: RevokeSessionOptions): Promise<void> {
    await this.workos.post<void, SerializedRevokeSessionOptions>(
      '/user_management/sessions/revoke',
      serializeRevokeSessionOptions(payload),
    );
  }

  /**
   * Get an authorization URL
   *
   * Generates an OAuth 2.0 authorization URL to authenticate a user with AuthKit or SSO.
   * @param options.codeChallengeMethod - The only valid PKCE code challenge method is `"S256"`. Required when specifying a `code_challenge`.
   * @example "S256"
   * @param options.codeChallenge - Code challenge derived from the code verifier used for the PKCE flow.
   * @example "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"
   * @param options.domainHint - A domain hint for SSO connection lookup.
   * @example "example.com"
   * @param options.connectionId - The ID of an SSO connection to use for authentication.
   * @example "conn_01EHQMYV6MBK39QC5PZXHY59C3"
   * @param options.providerQueryParams - Key/value pairs of query parameters to pass to the OAuth provider.
   * @example {"hd":"example.com","access_type":"offline"}
   * @param options.providerScopes - Additional OAuth scopes to request from the identity provider.
   * @example ["openid","profile","email"]
   * @param options.invitationToken - A token representing a user invitation to redeem during authentication.
   * @example "inv_token_abc123"
   * @param options.screenHint - Used to specify which screen to display when the provider is `authkit`.
   * @default "sign-in"
   * @example "sign-in"
   * @param options.loginHint - A hint to the authorization server about the login identifier the user might use.
   * @example "user@example.com"
   * @param options.provider - The OAuth provider to authenticate with (e.g., GoogleOAuth, MicrosoftOAuth, GitHubOAuth).
   * @example "GoogleOAuth"
   * @param options.prompt - Controls the authentication flow behavior for the user.
   * @example "login"
   * @param options.state - An opaque value used to maintain state between the request and the callback.
   * @example "eyJyZXR1cm5UbyI6ICIvZGFzaGJvYXJkIn0="
   * @param options.organizationId - The ID of the organization to authenticate the user against.
   * @example "org_01EHQMYV6MBK39QC5PZXHY59C3"
   * @param options.responseType - The response type of the application.
   * @example "code"
   * @param options.redirectUri - The callback URI where the authorization code will be sent after authentication.
   * @example "https://example.com/callback"
   * @param options.clientId - The unique identifier of the WorkOS environment client.
   * @example "client_01HZBC6N1EB1ZY7KG32X"
   * @param options - Additional query options.
   * @returns {void}
   */
  getAuthorizationUrl(options: UserManagementAuthorizationURLOptions): string {
    const {
      claimNonce,
      connectionId,
      codeChallenge,
      codeChallengeMethod,
      clientId,
      domainHint,
      loginHint,
      organizationId,
      provider,
      providerQueryParams,
      providerScopes,
      prompt,
      redirectUri,
      state,
      screenHint,
    } = options;
    const resolvedClientId = this.resolveClientId(clientId);

    if (!provider && !connectionId && !organizationId) {
      throw new TypeError(
        `Incomplete arguments. Need to specify either a 'connectionId', 'organizationId', or 'provider'.`,
      );
    }

    if (provider !== 'authkit' && screenHint) {
      throw new TypeError(
        `'screenHint' is only supported for 'authkit' provider`,
      );
    }

    const query = toQueryString({
      claim_nonce: claimNonce,
      connection_id: connectionId,
      code_challenge: codeChallenge,
      code_challenge_method: codeChallengeMethod,
      organization_id: organizationId,
      domain_hint: domainHint,
      login_hint: loginHint,
      provider,
      provider_query_params: providerQueryParams,
      provider_scopes: providerScopes,
      prompt,
      client_id: resolvedClientId,
      redirect_uri: redirectUri,
      response_type: 'code',
      state,
      screen_hint: screenHint,
    });

    return `${this.workos.baseURL}/user_management/authorize?${query}`;
  }

  /**
   * Generate an OAuth 2.0 authorization URL with automatic PKCE.
   *
   * This method generates PKCE parameters internally and returns them along with
   * the authorization URL. Use this for public clients (CLI apps, Electron, mobile)
   * that cannot securely store a client secret.
   *
   * @returns Object containing url, state, and codeVerifier
   *
   * @example
   * ```typescript
   * const { url, state, codeVerifier } = await workos.userManagement.getAuthorizationUrlWithPKCE({
   *   provider: 'authkit',
   *   clientId: 'client_123',
   *   redirectUri: 'myapp://callback',
   * });
   *
   * // Store state and codeVerifier securely, then redirect user to url
   * // After callback, exchange the code:
   * const response = await workos.userManagement.authenticateWithCode({
   *   code: authorizationCode,
   *   codeVerifier,
   *   clientId: 'client_123',
   * });
   * ```
   */
  async getAuthorizationUrlWithPKCE(
    options: Omit<
      UserManagementAuthorizationURLOptions,
      'codeChallenge' | 'codeChallengeMethod' | 'state'
    >,
  ): Promise<PKCEAuthorizationURLResult> {
    const {
      clientId,
      connectionId,
      domainHint,
      loginHint,
      organizationId,
      provider,
      providerQueryParams,
      providerScopes,
      prompt,
      redirectUri,
      screenHint,
    } = options;
    const resolvedClientId = this.resolveClientId(clientId);

    if (!provider && !connectionId && !organizationId) {
      throw new TypeError(
        `Incomplete arguments. Need to specify either a 'connectionId', 'organizationId', or 'provider'.`,
      );
    }

    if (provider !== 'authkit' && screenHint) {
      throw new TypeError(
        `'screenHint' is only supported for 'authkit' provider`,
      );
    }

    // Generate PKCE parameters
    const pkce = await this.workos.pkce.generate();

    // Generate secure random state
    const state = this.workos.pkce.generateCodeVerifier(43);

    const query = toQueryString({
      connection_id: connectionId,
      code_challenge: pkce.codeChallenge,
      code_challenge_method: 'S256',
      organization_id: organizationId,
      domain_hint: domainHint,
      login_hint: loginHint,
      provider,
      provider_query_params: providerQueryParams,
      provider_scopes: providerScopes,
      prompt,
      client_id: resolvedClientId,
      redirect_uri: redirectUri,
      response_type: 'code',
      state,
      screen_hint: screenHint,
    });

    const url = `${this.workos.baseURL}/user_management/authorize?${query}`;

    return { url, state, codeVerifier: pkce.codeVerifier };
  }

  /**
   * Logout
   *
   * Logout a user from the current [session](https://workos.com/docs/reference/authkit/session).
   * @param options.sessionId - The ID of the session to revoke. This can be extracted from the `sid` claim of the access token.
   * @example "session_01H93ZY4F80QPBEZ1R5B2SHQG8"
   * @param options.returnTo - The URL to redirect the user to after session revocation.
   * @example "https://example.com"
   * @param options - Additional query options.
   * @returns {void}
   * @throws {UnprocessableEntityException} 422
   */
  getLogoutUrl(options: LogoutURLOptions): string {
    const { sessionId, returnTo } = options;

    if (!sessionId) {
      throw new TypeError(`Incomplete arguments. Need to specify 'sessionId'.`);
    }

    const url = new URL(
      '/user_management/sessions/logout',
      this.workos.baseURL,
    );

    url.searchParams.set('session_id', sessionId);
    if (returnTo) {
      url.searchParams.set('return_to', returnTo);
    }

    return url.toString();
  }

  getJwksUrl(clientId: string): string {
    if (!clientId) {
      throw new TypeError('clientId must be a valid clientId');
    }

    return `${this.workos.baseURL}/sso/jwks/${clientId}`;
  }
}

export interface GetAuthorizationUrlOptions {
  /** The only valid PKCE code challenge method is `"S256"`. Required when specifying a `code_challenge`. */
  codeChallengeMethod?: 'S256';
  /** Code challenge derived from the code verifier used for the PKCE flow. */
  codeChallenge?: string;
  /** A domain hint for SSO connection lookup. */
  domainHint?: string;
  /** The ID of an SSO connection to use for authentication. */
  connectionId?: string;
  /** Key/value pairs of query parameters to pass to the OAuth provider. */
  providerQueryParams?: Record<string, string>;
  /** Additional OAuth scopes to request from the identity provider. */
  providerScopes?: string[];
  /** A token representing a user invitation to redeem during authentication. */
  invitationToken?: string;
  /** Used to specify which screen to display when the provider is `authkit`. */
  screenHint?: UserManagementAuthenticationScreenHint;
  /** A hint to the authorization server about the login identifier the user might use. */
  loginHint?: string;
  /** The OAuth provider to authenticate with (e.g., GoogleOAuth, MicrosoftOAuth, GitHubOAuth). */
  provider?: UserManagementAuthenticationProvider;
  /** Controls the authentication flow behavior for the user. */
  prompt?: string;
  /** An opaque value used to maintain state between the request and the callback. */
  state?: string;
  /** The ID of the organization to authenticate the user against. */
  organizationId?: string;
  /** The response type of the application. */
  responseType: 'code';
  /** The callback URI where the authorization code will be sent after authentication. */
  redirectUri: string;
  /** The unique identifier of the WorkOS environment client. */
  clientId: string;
}

export interface GetLogoutUrlOptions {
  /** The ID of the session to revoke. This can be extracted from the `sid` claim of the access token. */
  sessionId: string;
  /** The URL to redirect the user to after session revocation. */
  returnTo?: string;
}
