// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type {
  RedirectUri,
  RedirectUriResponse,
} from '../workos-connect/interfaces/redirect-uri.interface';
import type { CreateRedirectUri } from './interfaces/create-redirect-uri.interface';
import { deserializeRedirectUri } from '../workos-connect/serializers/redirect-uri.serializer';
import { serializeCreateRedirectUri } from './serializers/create-redirect-uri.serializer';

export class UserManagementRedirectUris {
  constructor(private readonly workos: WorkOS) {}

  /**
   * Create a redirect URI
   *
   * Creates a new redirect URI for an environment.
   * @param payload - Object containing uri.
   * @returns {RedirectUri}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {UnprocessableEntityException} 422
   */
  async create(payload: CreateRedirectUri): Promise<RedirectUri> {
    const { data } = await this.workos.post<RedirectUriResponse>(
      '/user_management/redirect_uris',
      serializeCreateRedirectUri(payload),
    );
    return deserializeRedirectUri(data);
  }
}
