// This file is auto-generated by oagen. Do not edit.

import type {
  FlagOwner,
  FlagOwnerResponse,
} from '../interfaces/flag-owner.interface';

export const deserializeFlagOwner = (
  response: FlagOwnerResponse,
): FlagOwner => ({
  email: response.email,
  firstName: response.first_name ?? null,
  lastName: response.last_name ?? null,
});
