// This file is auto-generated by oagen. Do not edit.

/** SMS-based authentication factor details. */
export interface AuthenticationFactorSms {
  /** The user's phone number for SMS-based authentication. */
  phoneNumber: string;
}

export interface AuthenticationFactorSmsResponse {
  phone_number: string;
}
