// This file is auto-generated by oagen. Do not edit.

/** The authentication challenge object. */
export interface AuthenticationChallenge {
  /** Distinguishes the authentication challenge object. */
  object: 'authentication_challenge';
  /** The unique ID of the authentication challenge. */
  id: string;
  /** The timestamp when the challenge will expire. Does not apply to TOTP factors. */
  expiresAt?: string;
  /** The one-time code for the challenge. */
  code?: string;
  /** The unique ID of the authentication factor the challenge belongs to. */
  authenticationFactorId: string;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
}

export interface AuthenticationChallengeResponse {
  object: 'authentication_challenge';
  id: string;
  expires_at?: string;
  code?: string;
  authentication_factor_id: string;
  created_at: string;
  updated_at: string;
}
