// This file is auto-generated by oagen. Do not edit.

import type {
  CreateGroupMembership,
  CreateGroupMembershipResponse,
} from '../interfaces/create-group-membership.interface';

export const serializeCreateGroupMembership = (
  model: CreateGroupMembership,
): CreateGroupMembershipResponse => ({
  organization_membership_id: model.organizationMembershipId,
});
