// This file is auto-generated by oagen. Do not edit.

import type { Group, GroupResponse } from '../interfaces/group.interface';

export const deserializeGroup = (response: GroupResponse): Group => ({
  object: response.object,
  id: response.id,
  organizationId: response.organization_id,
  name: response.name,
  description: response.description ?? null,
  createdAt: new Date(response.created_at),
  updatedAt: new Date(response.updated_at),
});

export const serializeGroup = (model: Group): GroupResponse => ({
  object: model.object,
  id: model.id,
  organization_id: model.organizationId,
  name: model.name,
  description: model.description,
  created_at: model.createdAt.toISOString(),
  updated_at: model.updatedAt.toISOString(),
});
