// This file is auto-generated by oagen. Do not edit.

import type { ItContact, ItContactResponse } from './it-contact.interface';
import type {
  ItContactListListMetadata,
  ItContactListListMetadataResponse,
} from './it-contact-list-list-metadata.interface';

export interface ItContactList {
  /** Indicates this is a list response. */
  object: 'list';
  /** The list of records for the current page. */
  data: ItContact[];
  /** Pagination cursors for navigating between pages of results. */
  listMetadata: ItContactListListMetadata;
}

export interface ItContactListResponse {
  object: 'list';
  data: ItContactResponse[];
  list_metadata: ItContactListListMetadataResponse;
}
