// This file is auto-generated by oagen. Do not edit.

export interface ItContact {
  /** The IT Contact object. */
  object: 'it_contact';
  /** The unique ID of the IT Contact. */
  id: string;
  /** The email address of the IT Contact. */
  email: string;
  /** An ISO 8601 timestamp. */
  createdAt: Date;
  /** An ISO 8601 timestamp. */
  updatedAt: Date;
}

export interface ItContactResponse {
  object: 'it_contact';
  id: string;
  email: string;
  created_at: string;
  updated_at: string;
}
