// This file is auto-generated by oagen. Do not edit.

import type { UserObject } from './user-object.interface';
import type { UserConsentOption } from './user-consent-option.interface';

export interface CompleteOAuth2Options {
  /** Identifier provided when AuthKit redirected to your login page. */
  externalAuthId: string;
  /** The user to create or update in AuthKit. */
  user: UserObject;
  /** Array of [User Consent Options](https://workos.com/docs/reference/workos-connect/standalone/user-consent-options) to store with the session. */
  userConsentOptions?: UserConsentOption[];
}
