// This file is auto-generated by oagen. Do not edit.

import type {
  RedirectUriInput,
  RedirectUriInputResponse,
} from './redirect-uri-input.interface';

export interface UpdateOAuthApplication {
  /** The name of the application. */
  name?: string;
  /** A description for the application. */
  description?: string | null;
  /** The OAuth scopes granted to the application. */
  scopes?: string[] | null;
  /** Updated redirect URIs for the application. OAuth applications only. */
  redirectUris?: RedirectUriInput[] | null;
}

export interface UpdateOAuthApplicationResponse {
  name?: string;
  description?: string | null;
  scopes?: string[] | null;
  redirect_uris?: RedirectUriInputResponse[] | null;
}
