// This file is auto-generated by oagen. Do not edit.

import type {
  SSOIntentOptions,
  SSOIntentOptionsResponse,
} from '../interfaces/sso-intent-options.interface';

export const deserializeSSOIntentOptions = (
  response: SSOIntentOptionsResponse,
): SSOIntentOptions => ({
  bookmarkSlug: response.bookmark_slug,
  providerType: response.provider_type,
});

export const serializeSSOIntentOptions = (
  model: SSOIntentOptions,
): SSOIntentOptionsResponse => ({
  bookmark_slug: model.bookmarkSlug,
  provider_type: model.providerType,
});
