// This file is auto-generated by oagen. Do not edit.

import type {
  SSOIntentOptions,
  SSOIntentOptionsResponse,
} from '../interfaces/sso-intent-options.interface';

export const serializeSSOIntentOptions = (
  model: SSOIntentOptions,
): SSOIntentOptionsResponse => ({
  bookmark_slug: model.bookmarkSlug,
  provider_type: model.providerType,
});
