// This file is auto-generated by oagen. Do not edit.

import { serializeTokenQuery } from './serializers/token-query.serializer';
import { deserializeConnection } from './serializers/connection.serializer';
import { deserializeSSOAuthorizeUrlResponse } from './serializers/sso-authorize-url-response.serializer';
import { deserializeProfile } from './serializers/profile.serializer';
import { deserializeSSOTokenResponse } from './serializers/sso-token-response.serializer';
import { deserializeSSOLogoutAuthorizeResponse } from './serializers/sso-logout-authorize-response.serializer';
import { deserializeSSOTokenResponseOAuthToken } from './serializers/sso-token-response-oauth-token.serializer';
import { deserializeConnectionDomain } from './serializers/connection-domain.serializer';
import { deserializeConnectionOption } from './serializers/connection-option.serializer';
import { serializeSSOLogoutAuthorizeRequest } from './serializers/sso-logout-authorize-request.serializer';
import type { TokenQueryResponse } from './interfaces/token-query.interface';
import type { ConnectionResponse } from './interfaces/connection.interface';
import type { SSOAuthorizeUrlResponseWire } from './interfaces/sso-authorize-url-response.interface';
import type { ProfileResponse } from './interfaces/profile.interface';
import type { SSOTokenResponseWire } from './interfaces/sso-token-response.interface';
import type { SSOLogoutAuthorizeResponseWire } from './interfaces/sso-logout-authorize-response.interface';
import type { SSOTokenResponseOAuthTokenResponse } from './interfaces/sso-token-response-oauth-token.interface';
import type { ConnectionDomainResponse } from './interfaces/connection-domain.interface';
import type { ConnectionOptionResponse } from './interfaces/connection-option.interface';
import type { SSOLogoutAuthorizeRequestResponse } from './interfaces/sso-logout-authorize-request.interface';
import tokenQueryFixture from './fixtures/token-query.json';
import connectionFixture from './fixtures/connection.json';
import ssoAuthorizeUrlResponseFixture from './fixtures/sso-authorize-url-response.json';
import profileFixture from './fixtures/profile.json';
import ssoTokenResponseFixture from './fixtures/sso-token-response.json';
import ssoLogoutAuthorizeResponseFixture from './fixtures/sso-logout-authorize-response.json';
import ssoTokenResponseOAuthTokenFixture from './fixtures/sso-token-response-oauth-token.json';
import connectionDomainFixture from './fixtures/connection-domain.json';
import connectionOptionFixture from './fixtures/connection-option.json';
import ssoLogoutAuthorizeRequestFixture from './fixtures/sso-logout-authorize-request.json';

describe('TokenQuerySerializer', () => {
  it('serializes correctly', () => {
    const fixture = tokenQueryFixture as TokenQueryResponse;
    const serialized = serializeTokenQuery(fixture as any);
    expect(serialized).toBeDefined();
  });
});

describe('ConnectionSerializer', () => {
  it('deserializes correctly', () => {
    const fixture = connectionFixture as ConnectionResponse;
    const deserialized = deserializeConnection(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('SSOAuthorizeUrlResponseSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      ssoAuthorizeUrlResponseFixture as SSOAuthorizeUrlResponseWire;
    const deserialized = deserializeSSOAuthorizeUrlResponse(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('ProfileSerializer', () => {
  it('deserializes correctly', () => {
    const fixture = profileFixture as ProfileResponse;
    const deserialized = deserializeProfile(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('SSOTokenResponseSerializer', () => {
  it('deserializes correctly', () => {
    const fixture = ssoTokenResponseFixture as SSOTokenResponseWire;
    const deserialized = deserializeSSOTokenResponse(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('SSOLogoutAuthorizeResponseSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      ssoLogoutAuthorizeResponseFixture as SSOLogoutAuthorizeResponseWire;
    const deserialized = deserializeSSOLogoutAuthorizeResponse(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('SSOTokenResponseOAuthTokenSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      ssoTokenResponseOAuthTokenFixture as SSOTokenResponseOAuthTokenResponse;
    const deserialized = deserializeSSOTokenResponseOAuthToken(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('ConnectionDomainSerializer', () => {
  it('deserializes correctly', () => {
    const fixture = connectionDomainFixture as ConnectionDomainResponse;
    const deserialized = deserializeConnectionDomain(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('ConnectionOptionSerializer', () => {
  it('deserializes correctly', () => {
    const fixture = connectionOptionFixture as ConnectionOptionResponse;
    const deserialized = deserializeConnectionOption(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('SSOLogoutAuthorizeRequestSerializer', () => {
  it('serializes correctly', () => {
    const fixture =
      ssoLogoutAuthorizeRequestFixture as SSOLogoutAuthorizeRequestResponse;
    const serialized = serializeSSOLogoutAuthorizeRequest(fixture as any);
    expect(serialized).toBeDefined();
  });
});
