// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import type { AutoPaginatable } from '../common/utils/pagination';
import { createPaginatedList } from '../common/utils/fetch-and-deserialize';
import type {
  Flag,
  FlagResponse,
} from '../feature-flags/interfaces/flag.interface';
import { deserializeFlag } from '../feature-flags/serializers/flag.serializer';

export class UserManagementUsersFeatureFlags {
  constructor(private readonly workos: WorkOS) {}

  /**
   * List enabled feature flags for a user
   *
   * Get a list of all enabled feature flags for the provided user. This includes feature flags enabled specifically for the user as well as any organizations that the user is a member of.
   * @param userId - The ID of the user.
   * @example "user_01E4ZCR3C56J083X43JQXF3JK5"
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<Flag>}
   * @throws {NotFoundException} 404
   */
  async list(
    userId: string,
    options?: PaginationOptions,
  ): Promise<AutoPaginatable<Flag, PaginationOptions>> {
    return createPaginatedList<FlagResponse, Flag, PaginationOptions>(
      this.workos,
      `/user_management/users/${userId}/feature-flags`,
      deserializeFlag,
      options,
    );
  }
}
