export enum ConnectionType {
  ADFSSAML = 'ADFSSAML',
  Auth0SAML = 'Auth0SAML',
  AzureSAML = 'AzureSAML',
  GenericOIDC = 'GenericOIDC',
  GenericSAML = 'GenericSAML',
  GoogleOAuth = 'GoogleOAuth',
  GoogleSAML = 'GoogleSAML',
  MagicLink = 'MagicLink',
  OktaSAML = 'OktaSAML',
  OneLoginSAML = 'OneLoginSAML',
  PingFederateSAML = 'PingFederateSAML',
  PingOneSAML = 'PingOneSAML',
  VMwareSAML = 'VMwareSAML',
}
