// This file is auto-generated by oagen. Do not edit.

export const ConnectionState = {
  RequiresType: 'requires_type',
  Draft: 'draft',
  Active: 'active',
  Validating: 'validating',
  Inactive: 'inactive',
  Deleting: 'deleting',
} as const;

export type ConnectionState =
  (typeof ConnectionState)[keyof typeof ConnectionState];
