// This file is auto-generated by oagen. Do not edit.

import type { SSOProvider } from './sso-provider.interface';

export interface GetAuthorizationUrlOptions {
  /** Additional scopes to request from the identity provider. Applicable when using OAuth or OpenID Connect connections. */
  providerScopes?: string[];
  /** Key/value pairs of query parameters to pass to the OAuth provider. Only applicable when using OAuth connections. */
  providerQueryParams?: Record<string, string>;
  /**
   * Deprecated. Use `connection` or `organization` instead. Used to initiate SSO for a connection by domain. The domain must be associated with a connection in your WorkOS environment.
   * @deprecated
   */
  domain?: string;
  /** Used to initiate OAuth authentication with various providers. */
  provider?: SSOProvider;
  /** Where to redirect the user after they complete the authentication process. You must use one of the redirect URIs configured via the [Redirects](https://dashboard.workos.com/redirects) page on the dashboard. */
  redirectUri: string;
  /** An optional parameter that can be used to encode arbitrary information to help restore application state between redirects. If included, the redirect URI received from WorkOS will contain the exact `state` that was passed. */
  state?: string;
  /**
   * Used to initiate SSO for a connection. The value should be a WorkOS connection ID.
   *
   * You can persist the WorkOS connection ID with application user or team identifiers. WorkOS will use the connection indicated by the connection parameter to direct the user to the corresponding IdP for authentication.
   */
  connection?: string;
  /**
   * Used to initiate SSO for an organization. The value should be a WorkOS organization ID.
   *
   * You can persist the WorkOS organization ID with application user or team identifiers. WorkOS will use the organization ID to determine the appropriate connection and the IdP to direct the user to for authentication.
   */
  organization?: string;
  /** Can be used to pre-fill the domain field when initiating authentication with Microsoft OAuth or with a Google SAML connection type. */
  domainHint?: string;
  /** Can be used to pre-fill the username/email address field of the IdP sign-in page for the user, if you know their username ahead of time. Currently supported for OAuth, OpenID Connect, Okta, Entra ID, and custom SAML connections. */
  loginHint?: string;
  /** A random string generated by the client that is used to mitigate replay attacks. */
  nonce?: string;
}
