// This file is auto-generated by oagen. Do not edit.

export interface TokenQuery {
  /** The client ID of the WorkOS environment. */
  clientId: string;
  /** The client secret of the WorkOS environment. */
  clientSecret: string;
  /** The authorization code received from the authorization callback. */
  code: string;
  /** The grant type for the token request. */
  grantType: 'authorization_code';
}

export interface TokenQueryResponse {
  client_id: string;
  client_secret: string;
  code: string;
  grant_type: 'authorization_code';
}
