// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import { AutoPaginatable } from '../common/utils/pagination';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import type { ListEventOptions } from './interfaces/list-events-options.interface';
import type {
  Event,
  EventResponse,
} from '../common/interfaces/event.interface';
import { deserializeEvent } from '../common/serializers/event.serializer';

const serializeListEventOptions = (
  options: ListEventOptions,
): PaginationOptions => {
  const wire: Record<string, unknown> = {
    limit: options.limit,
    after: options.after,
    order: options.order,
  };
  if (options.events !== undefined) wire.events = options.events;
  if (options.rangeStart !== undefined) wire.range_start = options.rangeStart;
  if (options.rangeEnd !== undefined) wire.range_end = options.rangeEnd;
  if (options.organizationId !== undefined)
    wire.organization_id = options.organizationId;
  return wire as PaginationOptions;
};

export class Events {
  constructor(private readonly workos: WorkOS) {}

  /**
   * List events
   *
   * List events for the current environment.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<Event>>}
   * @throws {BadRequestException} 400
   * @throws {UnprocessableEntityException} 422
   */
  async listEvents(options: ListEventOptions): Promise<AutoPaginatable<Event>> {
    const paginationOptions = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<EventResponse, Event>(
        this.workos,
        '/events',
        deserializeEvent,
        options ? serializeListEventOptions(options) : undefined,
      ),
      (params) =>
        fetchAndDeserialize<EventResponse, Event>(
          this.workos,
          '/events',
          deserializeEvent,
          params,
        ),
      paginationOptions,
    );
  }
}
