// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogSchema,
  AuditLogSchemaResponse,
} from './audit-log-schema.interface';

export interface AuditLogAction {
  /** Distinguishes the Audit Log Action object. */
  object: 'audit_log_action';
  /** Identifier of what action was taken. */
  name: string;
  /** The schema associated with the action. */
  schema: AuditLogSchema;
  /** An ISO 8601 timestamp. */
  createdAt: Date;
  /** An ISO 8601 timestamp. */
  updatedAt: Date;
}

export interface AuditLogActionResponse {
  object: 'audit_log_action';
  name: string;
  schema: AuditLogSchemaResponse;
  created_at: string;
  updated_at: string;
}
