// This file is auto-generated by oagen. Do not edit.

export interface AuditLogExportCreation {
  /** The unique ID of the Organization. */
  organizationId: string;
  /** ISO-8601 value for start of the export range. */
  rangeStart: string;
  /** ISO-8601 value for end of the export range. */
  rangeEnd: string;
  /** List of actions to filter against. */
  actions?: string[];
  /**
   * Deprecated. Use `actor_names` instead.
   * @deprecated
   */
  actors?: string[];
  /** List of actor names to filter against. */
  actorNames?: string[];
  /** List of actor IDs to filter against. */
  actorIds?: string[];
  /** List of target types to filter against. */
  targets?: string[];
}

export interface AuditLogExportCreationResponse {
  organization_id: string;
  range_start: string;
  range_end: string;
  actions?: string[];
  actors?: string[];
  actor_names?: string[];
  actor_ids?: string[];
  targets?: string[];
}
