// This file is auto-generated by oagen. Do not edit.

export interface AuditLogEventActor {
  /** Actor identifier. */
  id: string;
  /** Actor type. */
  type: string;
  /** Optional actor name. */
  name?: string;
  /** Additional data associated with the event or entity. */
  metadata?: Record<string, string | number | boolean>;
}

export interface AuditLogEventActorResponse {
  id: string;
  type: string;
  name?: string;
  metadata?: Record<string, string | number | boolean>;
}
