// This file is auto-generated by oagen. Do not edit.

export interface AuditLogSchemaActor {
  /** JSON schema for actor metadata. */
  metadata: Record<string, any>;
}

export interface AuditLogSchemaActorResponse {
  metadata: Record<string, any>;
}
