// This file is auto-generated by oagen. Do not edit.

import type { AuditLogSchemaActorInput } from './audit-log-schema-actor-input.interface';
import type { AuditLogSchemaTargetInput } from './audit-log-schema-target-input.interface';

export interface CreateSchemaOptions {
  /** The name of the Audit Log action. */
  actionName: string;
  /** The metadata schema for the actor. */
  actor?: AuditLogSchemaActorInput;
  /** The list of targets for the schema. */
  targets: AuditLogSchemaTargetInput[];
  /** Optional JSON schema for event metadata. */
  metadata?: Record<string, any>;
}
