// This file is auto-generated by oagen. Do not edit.

import fetch from 'jest-fetch-mock';
import {
  fetchOnce,
  fetchURL,
  fetchMethod,
  fetchSearchParams,
} from '../common/utils/test-utils';
import { WorkOS } from '../workos';

import listDirectoryFixture from './fixtures/list-directory.json';
import directoryFixture from './fixtures/directory.json';
import listDirectoryGroupFixture from './fixtures/list-directory-group.json';
import directoryGroupFixture from './fixtures/directory-group.json';

const workos = new WorkOS('sk_test_Sz3IQjepeSWaI4cMS4ms4sMuU');

function expectDirectory(result: any) {
  expect(result.object).toBe('directory');
  expect(result.id).toBe('directory_01ECAZ4NV9QMV47GW873HDCX74');
  expect(result.organizationId).toBe('org_01EHZNVPK3SFK441A1RGBFSHRT');
  expect(result.externalKey).toBe('sPa12dwRQ');
  expect(result.type).toBe('gsuite directory');
  expect(result.state).toBe('active');
  expect(result.name).toBe('Foo Corp');
  expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
  expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
}

function expectDirectoryGroup(result: any) {
  expect(result.object).toBe('directory_group');
  expect(result.id).toBe('directory_group_01E1JJS84MFPPQ3G655FHTKX6Z');
  expect(result.idpId).toBe('02grqrue4294w24');
  expect(result.directoryId).toBe('directory_01ECAZ4NV9QMV47GW873HDCX74');
  expect(result.organizationId).toBe('org_01EZTR6WYX1A0DSE2CYMGXQ24Y');
  expect(result.name).toBe('Developers');
  expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
  expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
}

describe('DirectorySync', () => {
  beforeEach(() => fetch.resetMocks());

  describe('listDirectories', () => {
    it('returns paginated results', async () => {
      fetchOnce(listDirectoryFixture);

      const { data, listMetadata } = await workos.directorySync.listDirectories(
        {
          order: 'desc',
          organizationId: 'org_01EHZNVPK3SFK441A1RGBFSHRT',
          search: 'Foo Corp',
        },
      );

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe('/directories');
      expect(fetchSearchParams()).toHaveProperty('order');
      expect(Array.isArray(data)).toBe(true);
      expect(listMetadata).toBeDefined();
      expect(data.length).toBeGreaterThan(0);
      expectDirectory(data[0]);
    });

    it('throws when the API responds with an error', async () => {
      fetchOnce({ message: 'Bad Request' }, { status: 400 });

      await expect(
        workos.directorySync.listDirectories({
          order: 'desc',
          organizationId: 'org_01EHZNVPK3SFK441A1RGBFSHRT',
          search: 'Foo Corp',
        }),
      ).rejects.toThrow();
    });
  });

  describe('getDirectory', () => {
    it('returns the expected result', async () => {
      fetchOnce(directoryFixture);

      const result = await workos.directorySync.getDirectory({ id: 'test_id' });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe('/directories/test_id');
      expectDirectory(result);
    });

    it('throws when the API responds with an error', async () => {
      fetchOnce({ message: 'Bad Request' }, { status: 400 });

      await expect(
        workos.directorySync.getDirectory({ id: 'test_id' }),
      ).rejects.toThrow();
    });
  });

  describe('deleteDirectory', () => {
    it('sends a DELETE request', async () => {
      fetchOnce({}, { status: 204 });

      await workos.directorySync.deleteDirectory({ id: 'test_id' });

      expect(fetchMethod()).toBe('DELETE');
      expect(new URL(String(fetchURL())).pathname).toBe('/directories/test_id');
    });

    it('throws when the API responds with an error', async () => {
      fetchOnce({ message: 'Bad Request' }, { status: 400 });

      await expect(
        workos.directorySync.deleteDirectory({ id: 'test_id' }),
      ).rejects.toThrow();
    });
  });

  describe('listGroups', () => {
    it('returns paginated results', async () => {
      fetchOnce(listDirectoryGroupFixture);

      const { data, listMetadata } = await workos.directorySync.listGroups({
        order: 'desc',
        directory: 'directory_01ECAZ4NV9QMV47GW873HDCX74',
        user: 'directory_user_01E1JG7J09H96KYP8HM9B0G5SJ',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe('/directory_groups');
      expect(fetchSearchParams()).toHaveProperty('order');
      expect(Array.isArray(data)).toBe(true);
      expect(listMetadata).toBeDefined();
      expect(data.length).toBeGreaterThan(0);
      expectDirectoryGroup(data[0]);
    });

    it('throws when the API responds with an error', async () => {
      fetchOnce({ message: 'Bad Request' }, { status: 400 });

      await expect(
        workos.directorySync.listGroups({
          order: 'desc',
          directory: 'directory_01ECAZ4NV9QMV47GW873HDCX74',
          user: 'directory_user_01E1JG7J09H96KYP8HM9B0G5SJ',
        }),
      ).rejects.toThrow();
    });
  });

  describe('getGroup', () => {
    it('returns the expected result', async () => {
      fetchOnce(directoryGroupFixture);

      const result = await workos.directorySync.getGroup({ id: 'test_id' });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/directory_groups/test_id',
      );
      expectDirectoryGroup(result);
    });

    it('throws when the API responds with an error', async () => {
      fetchOnce({ message: 'Bad Request' }, { status: 400 });

      await expect(
        workos.directorySync.getGroup({ id: 'test_id' }),
      ).rejects.toThrow();
    });
  });
});
