// This file is auto-generated by oagen. Do not edit.

import fetch from 'jest-fetch-mock';
import {
  fetchOnce,
  fetchURL,
  fetchMethod,
  fetchSearchParams,
  fetchBody,
} from '../common/utils/test-utils';
import { WorkOS } from '../workos';

import listWebhookEndpointFixture from './fixtures/list-webhook-endpoint.json';
import webhookEndpointFixture from './fixtures/webhook-endpoint.json';
import crypto from 'crypto';
import mockWebhook from './fixtures/webhook.json';
import { SignatureVerificationException } from '../common/exceptions';

// @oagen-ignore-start
describe('Webhook signatures', () => {
  let payload: any;
  let secret: string;
  let timestamp: number;
  let unhashedString: string;
  let signatureHash: string;
  let expectation: object;

  beforeEach(() => {
    payload = mockWebhook;
    secret = 'secret';
    timestamp = Date.now() * 1000;
    unhashedString = `${timestamp}.${JSON.stringify(payload)}`;
    signatureHash = crypto
      .createHmac('sha256', secret)
      .update(unhashedString)
      .digest()
      .toString('hex');
    expectation = {
      id: 'directory_user_01FAEAJCR3ZBZ30D8BD1924TVG',
      state: 'active',
      idpId: '00u1e8mutl6wlH3lL4x7',
      object: 'directory_user',
      lastName: 'Lunchford',
      firstName: 'Blair',
      directoryId: 'directory_01F9M7F68PZP8QXP8G7X5QRHS7',
      createdAt: '2021-06-25T19:07:33.155Z',
      updatedAt: '2021-06-25T19:07:33.155Z',
      rawAttributes: {
        name: {
          givenName: 'Blair',
          familyName: 'Lunchford',
          middleName: 'Elizabeth',
          honorificPrefix: 'Ms.',
        },
        title: 'Software Engineer',
        active: true,
        groups: [],
        locale: 'en-US',
        schemas: [
          'urn:ietf:params:scim:schemas:core:2.0:User',
          'urn:ietf:params:scim:schemas:extension:enterprise:2.0:User',
        ],
        addresses: [
          {
            region: 'CA',
            primary: true,
            locality: 'San Francisco',
            postalCode: '94016',
          },
        ],
        externalId: '00u1e8mutl6wlH3lL4x7',
        displayName: 'Blair Lunchford',
        'urn:ietf:params:scim:schemas:extension:enterprise:2.0:User': {
          manager: {
            value: '2',
            displayName: 'Kate Chapman',
          },
          division: 'Engineering',
          department: 'Customer Success',
        },
      },
    };
  });

  describe('constructEvent', () => {
    describe('with the correct payload, sig_header, and secret', () => {
      it('returns a webhook event', async () => {
        const sigHeader = `t=${timestamp}, v1=${signatureHash}`;
        const options = { payload, sigHeader, secret };
        const webhook = await workos.webhooks.constructEvent(options);

        expect(webhook.data).toEqual(expectation);
        expect(webhook.event).toEqual('dsync.user.created');
        expect(webhook.id).toEqual('wh_123');
      });
    });

    describe('with the correct payload, sig_header, secret, and tolerance', () => {
      it('returns a webhook event', async () => {
        const sigHeader = `t=${timestamp}, v1=${signatureHash}`;
        const options = { payload, sigHeader, secret, tolerance: 200 };
        const webhook = await workos.webhooks.constructEvent(options);

        expect(webhook.data).toEqual(expectation);
        expect(webhook.event).toEqual('dsync.user.created');
        expect(webhook.id).toEqual('wh_123');
      });
    });

    describe('with an empty header', () => {
      it('raises an error', async () => {
        const sigHeader = '';
        const options = { payload, sigHeader, secret };

        await expect(workos.webhooks.constructEvent(options)).rejects.toThrow(
          SignatureVerificationException,
        );
      });
    });

    describe('with an empty signature hash', () => {
      it('raises an error', async () => {
        const sigHeader = `t=${timestamp}, v1=`;
        const options = { payload, sigHeader, secret };

        await expect(workos.webhooks.constructEvent(options)).rejects.toThrow(
          SignatureVerificationException,
        );
      });
    });

    describe('with an incorrect signature hash', () => {
      it('raises an error', async () => {
        const sigHeader = `t=${timestamp}, v1=99999`;
        const options = { payload, sigHeader, secret };

        await expect(workos.webhooks.constructEvent(options)).rejects.toThrow(
          SignatureVerificationException,
        );
      });
    });

    describe('with an incorrect payload', () => {
      it('raises an error', async () => {
        const sigHeader = `t=${timestamp}, v1=${signatureHash}`;
        payload = 'invalid';
        const options = { payload, sigHeader, secret };

        await expect(workos.webhooks.constructEvent(options)).rejects.toThrow(
          SignatureVerificationException,
        );
      });
    });

    describe('with an incorrect webhook secret', () => {
      it('raises an error', async () => {
        const sigHeader = `t=${timestamp}, v1=${signatureHash}`;
        secret = 'invalid';
        const options = { payload, sigHeader, secret };

        await expect(workos.webhooks.constructEvent(options)).rejects.toThrow(
          SignatureVerificationException,
        );
      });
    });

    describe('with a timestamp outside tolerance', () => {
      it('raises an error', async () => {
        const sigHeader = `t=9999, v1=${signatureHash}`;
        const options = { payload, sigHeader, secret };

        await expect(workos.webhooks.constructEvent(options)).rejects.toThrow(
          SignatureVerificationException,
        );
      });
    });
  });

  describe('verifyHeader', () => {
    it('aliases to the signature provider', async () => {
      const spy = jest.spyOn(
        // tslint:disable-next-line
        workos.webhooks['signatureProvider'],
        'verifyHeader',
      );

      await workos.webhooks.verifyHeader({
        payload,
        sigHeader: `t=${timestamp}, v1=${signatureHash}`,
        secret,
      });

      expect(spy).toHaveBeenCalled();
    });
  });

  describe('computeSignature', () => {
    it('aliases to the signature provider', async () => {
      const spy = jest.spyOn(
        // tslint:disable-next-line
        workos.webhooks['signatureProvider'],
        'computeSignature',
      );

      await workos.webhooks.computeSignature(timestamp, payload, secret);

      expect(spy).toHaveBeenCalled();
    });
  });

  describe('getTimestampAndSignatureHash', () => {
    it('aliases to the signature provider', async () => {
      const spy = jest.spyOn(
        // tslint:disable-next-line
        workos.webhooks['signatureProvider'],
        'getTimestampAndSignatureHash',
      );

      workos.webhooks.getTimestampAndSignatureHash(
        `t=${timestamp}, v1=${signatureHash}`,
      );

      expect(spy).toHaveBeenCalled();
    });
  });

  describe('raw-bytes payload path (non-breaking overload)', () => {
    // Sign the exact bytes WorkOS would send on the wire. The SDK should HMAC
    // those same bytes (not a re-stringified round-trip), matching the pattern
    // used by Stripe, GitHub, and Svix.
    const signRaw = (rawBody: string, ts: number, sec: string): string =>
      crypto.createHmac('sha256', sec).update(`${ts}.${rawBody}`).digest('hex');

    it('verifies when payload is a raw JSON string matching the signed bytes', async () => {
      const rawBody = JSON.stringify(mockWebhook);
      const hash = signRaw(rawBody, timestamp, secret);
      const sigHeader = `t=${timestamp}, v1=${hash}`;

      const webhook = await workos.webhooks.constructEvent({
        payload: rawBody,
        sigHeader,
        secret,
      });

      expect(webhook.id).toEqual('wh_123');
    });

    it('verifies when payload is a Buffer matching the signed bytes', async () => {
      const rawBody = JSON.stringify(mockWebhook);
      const hash = signRaw(rawBody, timestamp, secret);
      const sigHeader = `t=${timestamp}, v1=${hash}`;

      const webhook = await workos.webhooks.constructEvent({
        payload: Buffer.from(rawBody, 'utf-8'),
        sigHeader,
        secret,
      });

      expect(webhook.id).toEqual('wh_123');
    });

    it('verifies when payload is a Uint8Array matching the signed bytes', async () => {
      const rawBody = JSON.stringify(mockWebhook);
      const hash = signRaw(rawBody, timestamp, secret);
      const sigHeader = `t=${timestamp}, v1=${hash}`;
      const bytes = new TextEncoder().encode(rawBody);

      const webhook = await workos.webhooks.constructEvent({
        payload: bytes,
        sigHeader,
        secret,
      });

      expect(webhook.id).toEqual('wh_123');
    });

    it('verifies when payload is an ArrayBuffer matching the signed bytes', async () => {
      const rawBody = JSON.stringify(mockWebhook);
      const hash = signRaw(rawBody, timestamp, secret);
      const sigHeader = `t=${timestamp}, v1=${hash}`;
      const bytes = new TextEncoder().encode(rawBody);
      const arrayBuffer = bytes.buffer.slice(
        bytes.byteOffset,
        bytes.byteOffset + bytes.byteLength,
      );

      const webhook = await workos.webhooks.constructEvent({
        payload: arrayBuffer,
        sigHeader,
        secret,
      });

      expect(webhook.id).toEqual('wh_123');
    });

    it('rejects mutated bytes that round-trip through JSON.parse to the same object (whitespace)', async () => {
      // Server signs canonical bytes; attacker forwards bytes with injected
      // whitespace that parse to the same object.
      const signedBytes = JSON.stringify(mockWebhook);
      const mutatedBytes = JSON.stringify(mockWebhook, null, 2); // pretty-printed
      expect(JSON.parse(signedBytes)).toEqual(JSON.parse(mutatedBytes));
      expect(signedBytes).not.toEqual(mutatedBytes);

      const hash = signRaw(signedBytes, timestamp, secret);
      const sigHeader = `t=${timestamp}, v1=${hash}`;

      await expect(
        workos.webhooks.constructEvent({
          payload: mutatedBytes,
          sigHeader,
          secret,
        }),
      ).rejects.toThrow(SignatureVerificationException);
    });

    it('rejects mutated bytes with unicode-escaped characters (same parsed object)', async () => {
      const signedBytes =
        '{"event":"dsync.user.created","data":{"name":"hello"}}';
      // hello parses to "hello" — same object, different bytes
      const mutatedBytes =
        '{"event":"dsync.user.created","data":{"name":"\\u0068\\u0065\\u006c\\u006c\\u006f"}}';
      expect(JSON.parse(signedBytes)).toEqual(JSON.parse(mutatedBytes));
      expect(signedBytes).not.toEqual(mutatedBytes);

      const hash = signRaw(signedBytes, timestamp, secret);
      const sigHeader = `t=${timestamp}, v1=${hash}`;

      await expect(
        workos.webhooks.constructEvent({
          payload: mutatedBytes,
          sigHeader,
          secret,
        }),
      ).rejects.toThrow(SignatureVerificationException);
    });

    it('rejects mutated bytes with reordered keys (same parsed object)', async () => {
      const signedBytes = '{"a":1,"b":2}';
      const mutatedBytes = '{"b":2,"a":1}';
      expect(JSON.parse(signedBytes)).toEqual(JSON.parse(mutatedBytes));

      const hash = signRaw(signedBytes, timestamp, secret);
      const sigHeader = `t=${timestamp}, v1=${hash}`;

      await expect(
        workos.webhooks.verifyHeader({
          payload: mutatedBytes,
          sigHeader,
          secret,
        }),
      ).rejects.toThrow(SignatureVerificationException);
    });

    it('rejects Buffer with a prepended UTF-8 BOM', async () => {
      const signedBytes = JSON.stringify(mockWebhook);
      const bomBuffer = Buffer.concat([
        Buffer.from([0xef, 0xbb, 0xbf]),
        Buffer.from(signedBytes, 'utf-8'),
      ]);

      const hash = signRaw(signedBytes, timestamp, secret);
      const sigHeader = `t=${timestamp}, v1=${hash}`;

      await expect(
        workos.webhooks.constructEvent({
          payload: bomBuffer,
          sigHeader,
          secret,
        }),
      ).rejects.toThrow(SignatureVerificationException);
    });

    it('legacy object path still verifies (back-compat)', async () => {
      // Existing caller shape: pre-parsed object, SDK re-stringifies internally.
      // Unsafe to byte-level mutation but must keep working until we deprecate.
      const sigHeader = `t=${timestamp}, v1=${signatureHash}`;
      const webhook = await workos.webhooks.constructEvent({
        payload: mockWebhook as unknown as Record<string, unknown>,
        sigHeader,
        secret,
      });

      expect(webhook.id).toEqual('wh_123');
    });
  });
});
// @oagen-ignore-end
const workos = new WorkOS('sk_test_Sz3IQjepeSWaI4cMS4ms4sMuU');

function expectWebhookEndpoint(result: any) {
  expect(result.object).toBe('webhook_endpoint');
  expect(result.id).toBe('we_0123456789');
  expect(result.endpointUrl).toBe('https://example.com/webhooks');
  expect(result.secret).toBe('whsec_0FWAiVGkEfGBqqsJH4aNAGBJ4');
  expect(result.status).toBe('enabled');
  expect(result.events).toEqual(['user.created', 'dsync.user.created']);
  expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
  expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
}

describe('Webhooks', () => {
  beforeEach(() => fetch.resetMocks());

  describe('listWebhookEndpoints', () => {
    it('returns paginated results', async () => {
      fetchOnce(listWebhookEndpointFixture);

      const { data, listMetadata } = await workos.webhooks.listWebhookEndpoints(
        { order: 'desc' },
      );

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe('/webhook_endpoints');
      expect(fetchSearchParams()).toHaveProperty('order');
      expect(Array.isArray(data)).toBe(true);
      expect(listMetadata).toBeDefined();
      expect(data.length).toBeGreaterThan(0);
      expectWebhookEndpoint(data[0]);
    });
  });

  describe('createWebhookEndpoint', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(webhookEndpointFixture);

      const result = await workos.webhooks.createWebhookEndpoint({
        endpointUrl: 'https://example.com',
        events: ['authentication.email_verification_succeeded'],
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe('/webhook_endpoints');
      expect(fetchBody()).toEqual(
        expect.objectContaining({
          endpoint_url: 'https://example.com',
          events: ['authentication.email_verification_succeeded'],
        }),
      );
      expectWebhookEndpoint(result);
    });
  });

  describe('updateWebhookEndpoint', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(webhookEndpointFixture);

      const result = await workos.webhooks.updateWebhookEndpoint({
        id: 'test_id',
        endpointUrl: 'https://example.com',
        status: 'enabled',
      });

      expect(fetchMethod()).toBe('PATCH');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/webhook_endpoints/test_id',
      );
      expect(fetchBody()).toEqual(
        expect.objectContaining({
          endpoint_url: 'https://example.com',
          status: 'enabled',
        }),
      );
      expectWebhookEndpoint(result);
    });
  });

  describe('deleteWebhookEndpoint', () => {
    it('sends a DELETE request', async () => {
      fetchOnce({}, { status: 204 });

      await workos.webhooks.deleteWebhookEndpoint({ id: 'test_id' });

      expect(fetchMethod()).toBe('DELETE');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/webhook_endpoints/test_id',
      );
    });
  });
});
