// This file is auto-generated by oagen. Do not edit.

/** The owner of the API key. */
export interface ApiKeyCreatedDataOwner {
  /** The type of the API key owner. */
  type: 'organization';
  /** The unique identifier of the API key owner. */
  id: string;
}

export interface ApiKeyCreatedDataOwnerResponse {
  type: 'organization';
  id: string;
}
