// This file is auto-generated by oagen. Do not edit.

export type AuditLogConfigurationLogStreamType =
  | 'AzureSentinel'
  | 'Datadog'
  | 'GenericHttps'
  | 'GoogleCloudStorage'
  | 'S3'
  | 'Splunk';
