// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationPasswordSucceededData,
  AuthenticationPasswordSucceededDataResponse,
} from './authentication-password-succeeded-data.interface';
import type {
  AuthenticationPasswordSucceededContext,
  AuthenticationPasswordSucceededContextResponse,
} from './authentication-password-succeeded-context.interface';

export interface AuthenticationPasswordSucceeded {
  /** Unique identifier for the event. */
  id: string;
  event: 'authentication.password_succeeded';
  /** The event payload. */
  data: AuthenticationPasswordSucceededData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: AuthenticationPasswordSucceededContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface AuthenticationPasswordSucceededResponse {
  id: string;
  event: 'authentication.password_succeeded';
  data: AuthenticationPasswordSucceededDataResponse;
  created_at: string;
  context?: AuthenticationPasswordSucceededContextResponse;
  object: 'event';
}
