// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationSSOFailedDataSSO,
  AuthenticationSSOFailedDataSSOResponse,
} from './authentication-sso-failed-data-sso.interface';
import type {
  AuthenticationSSOFailedDataError,
  AuthenticationSSOFailedDataErrorResponse,
} from './authentication-sso-failed-data-error.interface';

/** The event payload. */
export interface AuthenticationSSOFailedData {
  type: 'sso';
  status: 'failed';
  /** The IP address of the request. */
  ipAddress: string | null;
  /** The user agent of the request. */
  userAgent: string | null;
  /** The ID of the user. */
  userId: string | null;
  /** The email address of the user. */
  email: string | null;
  /** SSO connection details. */
  sso: AuthenticationSSOFailedDataSSO;
  /** Details about the authentication error. */
  error: AuthenticationSSOFailedDataError;
}

export interface AuthenticationSSOFailedDataResponse {
  type: 'sso';
  status: 'failed';
  ip_address: string | null;
  user_agent: string | null;
  user_id: string | null;
  email: string | null;
  sso: AuthenticationSSOFailedDataSSOResponse;
  error: AuthenticationSSOFailedDataErrorResponse;
}
