// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationPasswordSucceededContextGoogleAnalyticsSession,
  AuthenticationPasswordSucceededContextGoogleAnalyticsSessionResponse,
} from './authentication-password-succeeded-context-google-analytics-session.interface';
import type {
  AuthenticationPasswordSucceededContextActor,
  AuthenticationPasswordSucceededContextActorResponse,
} from './authentication-password-succeeded-context-actor.interface';

/** Additional context about the event. */
export interface AuthenticationPasswordSucceededContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: AuthenticationPasswordSucceededContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: AuthenticationPasswordSucceededContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface AuthenticationPasswordSucceededContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: AuthenticationPasswordSucceededContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: AuthenticationPasswordSucceededContextActorResponse;
  previous_attributes?: Record<string, any>;
}
