// This file is auto-generated by oagen. Do not edit.

import type { AuthenticationMagicAuthSucceededContextActorSource } from './authentication-magic-auth-succeeded-context-actor-source.interface';

/** The actor who performed the action. */
export interface AuthenticationMagicAuthSucceededContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: AuthenticationMagicAuthSucceededContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface AuthenticationMagicAuthSucceededContextActorResponse {
  id: string;
  source: AuthenticationMagicAuthSucceededContextActorSource;
  name: string | null;
}
