// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationRadarRiskDetectedContextGoogleAnalyticsSession,
  AuthenticationRadarRiskDetectedContextGoogleAnalyticsSessionResponse,
} from './authentication-radar-risk-detected-context-google-analytics-session.interface';
import type {
  AuthenticationRadarRiskDetectedContextActor,
  AuthenticationRadarRiskDetectedContextActorResponse,
} from './authentication-radar-risk-detected-context-actor.interface';

/** Additional context about the event. */
export interface AuthenticationRadarRiskDetectedContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: AuthenticationRadarRiskDetectedContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: AuthenticationRadarRiskDetectedContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface AuthenticationRadarRiskDetectedContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: AuthenticationRadarRiskDetectedContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: AuthenticationRadarRiskDetectedContextActorResponse;
  previous_attributes?: Record<string, any>;
}
