// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationEmailVerificationFailedDataError,
  AuthenticationEmailVerificationFailedDataErrorResponse,
} from './authentication-email-verification-failed-data-error.interface';

export type AuthenticationMfaFailedDataError =
  AuthenticationEmailVerificationFailedDataError;
export type AuthenticationMfaFailedDataErrorResponse =
  AuthenticationEmailVerificationFailedDataErrorResponse;
