// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationRadarRiskDetectedData,
  AuthenticationRadarRiskDetectedDataResponse,
} from './authentication-radar-risk-detected-data.interface';
import type {
  AuthenticationRadarRiskDetectedContext,
  AuthenticationRadarRiskDetectedContextResponse,
} from './authentication-radar-risk-detected-context.interface';

export interface AuthenticationRadarRiskDetected {
  /** Unique identifier for the event. */
  id: string;
  event: 'authentication.radar_risk_detected';
  /** The event payload. */
  data: AuthenticationRadarRiskDetectedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: AuthenticationRadarRiskDetectedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface AuthenticationRadarRiskDetectedResponse {
  id: string;
  event: 'authentication.radar_risk_detected';
  data: AuthenticationRadarRiskDetectedDataResponse;
  created_at: string;
  context?: AuthenticationRadarRiskDetectedContextResponse;
  object: 'event';
}
