// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationMfaSucceededData,
  AuthenticationMfaSucceededDataResponse,
} from './authentication-mfa-succeeded-data.interface';
import type {
  AuthenticationMfaSucceededContext,
  AuthenticationMfaSucceededContextResponse,
} from './authentication-mfa-succeeded-context.interface';

export interface AuthenticationMfaSucceeded {
  /** Unique identifier for the event. */
  id: string;
  event: 'authentication.mfa_succeeded';
  /** The event payload. */
  data: AuthenticationMfaSucceededData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: AuthenticationMfaSucceededContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface AuthenticationMfaSucceededResponse {
  id: string;
  event: 'authentication.mfa_succeeded';
  data: AuthenticationMfaSucceededDataResponse;
  created_at: string;
  context?: AuthenticationMfaSucceededContextResponse;
  object: 'event';
}
