// This file is auto-generated by oagen. Do not edit.

import type { AuthenticationRadarRiskDetectedContextActorSource } from './authentication-radar-risk-detected-context-actor-source.interface';

/** The actor who performed the action. */
export interface AuthenticationRadarRiskDetectedContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: AuthenticationRadarRiskDetectedContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface AuthenticationRadarRiskDetectedContextActorResponse {
  id: string;
  source: AuthenticationRadarRiskDetectedContextActorSource;
  name: string | null;
}
