// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationMagicAuthFailedContextGoogleAnalyticsSession,
  AuthenticationMagicAuthFailedContextGoogleAnalyticsSessionResponse,
} from './authentication-magic-auth-failed-context-google-analytics-session.interface';
import type {
  AuthenticationMagicAuthFailedContextActor,
  AuthenticationMagicAuthFailedContextActorResponse,
} from './authentication-magic-auth-failed-context-actor.interface';

/** Additional context about the event. */
export interface AuthenticationMagicAuthFailedContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: AuthenticationMagicAuthFailedContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: AuthenticationMagicAuthFailedContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface AuthenticationMagicAuthFailedContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: AuthenticationMagicAuthFailedContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: AuthenticationMagicAuthFailedContextActorResponse;
  previous_attributes?: Record<string, any>;
}
