// This file is auto-generated by oagen. Do not edit.

/** SSO connection details. */
export interface AuthenticationSSOFailedDataSSO {
  /** The ID of the organization. */
  organizationId: string | null;
  /** The ID of the SSO connection. */
  connectionId: string | null;
  /** The ID of the SSO session. */
  sessionId: string | null;
}

export interface AuthenticationSSOFailedDataSSOResponse {
  organization_id: string | null;
  connection_id: string | null;
  session_id: string | null;
}
