// This file is auto-generated by oagen. Do not edit.

import type { ConnectionDeletedDataState } from './connection-deleted-data-state.interface';
import type { ConnectionDeletedDataConnectionType } from './connection-deleted-data-connection-type.interface';

/** The event payload. */
export interface ConnectionDeletedData {
  /** Distinguishes the connection object. */
  object: 'connection';
  /** Unique identifier of the connection. */
  id: string;
  /** The current state of the connection. */
  state: ConnectionDeletedDataState;
  /** The name of the connection. */
  name: string;
  /** The type of the connection. */
  connectionType: ConnectionDeletedDataConnectionType;
  /** The ID of the organization the connection belongs to. */
  organizationId?: string;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
}

export interface ConnectionDeletedDataResponse {
  object: 'connection';
  id: string;
  state: ConnectionDeletedDataState;
  name: string;
  connection_type: ConnectionDeletedDataConnectionType;
  organization_id?: string;
  created_at: string;
  updated_at: string;
}
