// This file is auto-generated by oagen. Do not edit.

import type {
  ConnectionSAMLCertificateRenewalRequiredContextGoogleAnalyticsSession,
  ConnectionSAMLCertificateRenewalRequiredContextGoogleAnalyticsSessionResponse,
} from './connection-saml-certificate-renewal-required-context-google-analytics-session.interface';
import type {
  ConnectionSAMLCertificateRenewalRequiredContextActor,
  ConnectionSAMLCertificateRenewalRequiredContextActorResponse,
} from './connection-saml-certificate-renewal-required-context-actor.interface';

/** Additional context about the event. */
export interface ConnectionSAMLCertificateRenewalRequiredContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: ConnectionSAMLCertificateRenewalRequiredContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: ConnectionSAMLCertificateRenewalRequiredContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface ConnectionSAMLCertificateRenewalRequiredContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: ConnectionSAMLCertificateRenewalRequiredContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: ConnectionSAMLCertificateRenewalRequiredContextActorResponse;
  previous_attributes?: Record<string, any>;
}
