// This file is auto-generated by oagen. Do not edit.

import type {
  ConnectionActivatedDataDomain,
  ConnectionActivatedDataDomainResponse,
} from './connection-activated-data-domain.interface';
import type { ConnectionActivatedDataState } from './connection-activated-data-state.interface';
import type { ConnectionActivatedDataConnectionType } from './connection-activated-data-connection-type.interface';
import type { ConnectionActivatedDataStatus } from './connection-activated-data-status.interface';

/** The event payload. */
export interface ConnectionActivatedData {
  /** Distinguishes the connection object. */
  object: 'connection';
  /** Unique identifier of the connection. */
  id: string;
  /** The current state of the connection. */
  state: ConnectionActivatedDataState;
  /** The name of the connection. */
  name: string;
  /** The type of the connection. */
  connectionType: ConnectionActivatedDataConnectionType;
  /** The ID of the organization the connection belongs to. */
  organizationId?: string;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
  /** The external key of the connection. */
  externalKey: string;
  /** Deprecated. Use state instead. */
  status: ConnectionActivatedDataStatus;
  /** The domains associated with the connection. */
  domains: ConnectionActivatedDataDomain[];
}

export interface ConnectionActivatedDataResponse {
  object: 'connection';
  id: string;
  state: ConnectionActivatedDataState;
  name: string;
  connection_type: ConnectionActivatedDataConnectionType;
  organization_id?: string;
  created_at: string;
  updated_at: string;
  external_key: string;
  status: ConnectionActivatedDataStatus;
  domains: ConnectionActivatedDataDomainResponse[];
}
