// This file is auto-generated by oagen. Do not edit.

import type {
  ConnectionActivatedContextGoogleAnalyticsSession,
  ConnectionActivatedContextGoogleAnalyticsSessionResponse,
} from './connection-activated-context-google-analytics-session.interface';
import type {
  ConnectionActivatedContextActor,
  ConnectionActivatedContextActorResponse,
} from './connection-activated-context-actor.interface';

/** Additional context about the event. */
export interface ConnectionActivatedContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: ConnectionActivatedContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: ConnectionActivatedContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface ConnectionActivatedContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: ConnectionActivatedContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: ConnectionActivatedContextActorResponse;
  previous_attributes?: Record<string, any>;
}
