// This file is auto-generated by oagen. Do not edit.

import type {
  ActionAuthenticationDeniedContextGoogleAnalyticsSession,
  ActionAuthenticationDeniedContextGoogleAnalyticsSessionResponse,
} from './action-authentication-denied-context-google-analytics-session.interface';

export type ConnectionDeactivatedContextGoogleAnalyticsSession =
  ActionAuthenticationDeniedContextGoogleAnalyticsSession;
export type ConnectionDeactivatedContextGoogleAnalyticsSessionResponse =
  ActionAuthenticationDeniedContextGoogleAnalyticsSessionResponse;
