// This file is auto-generated by oagen. Do not edit.

import type { ConnectionSAMLCertificateRenewalRequiredDataCertificateCertificateType } from './connection-saml-certificate-renewal-required-data-certificate-certificate-type.interface';

/** The SAML certificate details. */
export interface ConnectionSAMLCertificateRenewalRequiredDataCertificate {
  /** The type of the SAML certificate. */
  certificateType: ConnectionSAMLCertificateRenewalRequiredDataCertificateCertificateType;
  /** An ISO 8601 timestamp. */
  expiryDate: string;
  /** Whether the certificate has already expired. */
  isExpired: boolean;
}

export interface ConnectionSAMLCertificateRenewalRequiredDataCertificateResponse {
  certificate_type: ConnectionSAMLCertificateRenewalRequiredDataCertificateCertificateType;
  expiry_date: string;
  is_expired: boolean;
}
