// This file is auto-generated by oagen. Do not edit.

import type { ConnectionSAMLCertificateRenewalRequiredContextActorSource } from './connection-saml-certificate-renewal-required-context-actor-source.interface';

/** The actor who performed the action. */
export interface ConnectionSAMLCertificateRenewalRequiredContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: ConnectionSAMLCertificateRenewalRequiredContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface ConnectionSAMLCertificateRenewalRequiredContextActorResponse {
  id: string;
  source: ConnectionSAMLCertificateRenewalRequiredContextActorSource;
  name: string | null;
}
