// This file is auto-generated by oagen. Do not edit.

import type { ConnectionDeletedContextActorSource } from './connection-deleted-context-actor-source.interface';

/** The actor who performed the action. */
export interface ConnectionDeletedContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: ConnectionDeletedContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface ConnectionDeletedContextActorResponse {
  id: string;
  source: ConnectionDeletedContextActorSource;
  name: string | null;
}
