// This file is auto-generated by oagen. Do not edit.

import type {
  ConnectionActivatedData,
  ConnectionActivatedDataResponse,
} from './connection-activated-data.interface';
import type {
  ConnectionActivatedContext,
  ConnectionActivatedContextResponse,
} from './connection-activated-context.interface';

export interface ConnectionActivated {
  /** Unique identifier for the event. */
  id: string;
  event: 'connection.activated';
  /** The event payload. */
  data: ConnectionActivatedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: ConnectionActivatedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface ConnectionActivatedResponse {
  id: string;
  event: 'connection.activated';
  data: ConnectionActivatedDataResponse;
  created_at: string;
  context?: ConnectionActivatedContextResponse;
  object: 'event';
}
