// This file is auto-generated by oagen. Do not edit.

import type {
  DirectoryUserEmail,
  DirectoryUserEmailResponse,
} from './directory-user-email.interface';
import type {
  SlimRole,
  SlimRoleResponse,
} from '../../authorization/interfaces/slim-role.interface';

export interface DirectoryUser {
  /** Distinguishes the Directory User object. */
  object: 'directory_user';
  /** Unique identifier for the Directory User. */
  id: string;
  /** The identifier of the Directory the Directory User belongs to. */
  directoryId: string;
  /** The identifier for the Organization in which the Directory resides. */
  organizationId: string | null;
  /** Unique identifier for the user, assigned by the Directory Provider. Different Directory Providers use different ID formats. */
  idpId: string;
  /** The email address of the user. */
  email: string | null;
  /** The first name of the user. */
  firstName?: string | null;
  /** The last name of the user. */
  lastName?: string | null;
  /**
   * A list of email addresses for the user.
   * @deprecated
   */
  emails?: DirectoryUserEmail[];
  /**
   * The job title of the user.
   * @deprecated
   */
  jobTitle?: string | null;
  /**
   * The username of the user.
   * @deprecated
   */
  username?: string | null;
  /** The state of the user. */
  state: 'active' | 'inactive';
  /**
   * The raw attributes received from the directory provider.
   * @deprecated
   */
  rawAttributes: Record<string, any>;
  /** An object containing the custom attribute mapping for the Directory Provider. */
  customAttributes: Record<string, any>;
  role?: SlimRole;
  /** All roles assigned to the user. */
  roles?: SlimRole[];
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
}

export interface DirectoryUserResponse {
  object: 'directory_user';
  id: string;
  directory_id: string;
  organization_id: string | null;
  idp_id: string;
  email: string | null;
  first_name?: string | null;
  last_name?: string | null;
  emails?: DirectoryUserEmailResponse[];
  job_title?: string | null;
  username?: string | null;
  state: 'active' | 'inactive';
  raw_attributes: Record<string, any>;
  custom_attributes: Record<string, any>;
  role?: SlimRoleResponse;
  roles?: SlimRoleResponse[];
  created_at: string;
  updated_at: string;
}
