// This file is auto-generated by oagen. Do not edit.

import type {
  DirectoryGroup,
  DirectoryGroupResponse,
} from '../../directory-sync/interfaces/directory-group.interface';

export type DsyncGroupUserRemovedDataGroup = DirectoryGroup;
export type DsyncGroupUserRemovedDataGroupResponse = DirectoryGroupResponse;
