// This file is auto-generated by oagen. Do not edit.

import type {
  DsyncActivatedData,
  DsyncActivatedDataResponse,
} from './dsync-activated-data.interface';
import type {
  DsyncActivatedContext,
  DsyncActivatedContextResponse,
} from './dsync-activated-context.interface';

export interface DsyncActivated {
  /** Unique identifier for the event. */
  id: string;
  event: 'dsync.activated';
  /** The event payload. */
  data: DsyncActivatedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: DsyncActivatedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface DsyncActivatedResponse {
  id: string;
  event: 'dsync.activated';
  data: DsyncActivatedDataResponse;
  created_at: string;
  context?: DsyncActivatedContextResponse;
  object: 'event';
}
