// This file is auto-generated by oagen. Do not edit.

import type {
  DsyncDeletedData,
  DsyncDeletedDataResponse,
} from './dsync-deleted-data.interface';
import type {
  DsyncDeletedContext,
  DsyncDeletedContextResponse,
} from './dsync-deleted-context.interface';

export interface DsyncDeleted {
  /** Unique identifier for the event. */
  id: string;
  event: 'dsync.deleted';
  /** The event payload. */
  data: DsyncDeletedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: DsyncDeletedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface DsyncDeletedResponse {
  id: string;
  event: 'dsync.deleted';
  data: DsyncDeletedDataResponse;
  created_at: string;
  context?: DsyncDeletedContextResponse;
  object: 'event';
}
