// This file is auto-generated by oagen. Do not edit.

import type {
  DsyncGroupDeletedData,
  DsyncGroupDeletedDataResponse,
} from './dsync-group-deleted-data.interface';
import type {
  DsyncGroupDeletedContext,
  DsyncGroupDeletedContextResponse,
} from './dsync-group-deleted-context.interface';

export interface DsyncGroupDeleted {
  /** Unique identifier for the event. */
  id: string;
  event: 'dsync.group.deleted';
  /** The event payload. */
  data: DsyncGroupDeletedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: DsyncGroupDeletedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface DsyncGroupDeletedResponse {
  id: string;
  event: 'dsync.group.deleted';
  data: DsyncGroupDeletedDataResponse;
  created_at: string;
  context?: DsyncGroupDeletedContextResponse;
  object: 'event';
}
