// This file is auto-generated by oagen. Do not edit.

import type {
  DsyncGroupCreatedContextGoogleAnalyticsSession,
  DsyncGroupCreatedContextGoogleAnalyticsSessionResponse,
} from './dsync-group-created-context-google-analytics-session.interface';
import type {
  DsyncGroupCreatedContextActor,
  DsyncGroupCreatedContextActorResponse,
} from './dsync-group-created-context-actor.interface';

/** Additional context about the event. */
export interface DsyncGroupCreatedContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: DsyncGroupCreatedContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: DsyncGroupCreatedContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface DsyncGroupCreatedContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: DsyncGroupCreatedContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: DsyncGroupCreatedContextActorResponse;
  previous_attributes?: Record<string, any>;
}
