// This file is auto-generated by oagen. Do not edit.

export interface DsyncActivatedDataDomain {
  /** Distinguishes the organization domain object. */
  object: 'organization_domain';
  /** Unique identifier of the organization domain. */
  id: string;
  /** The domain value. */
  domain: string;
}

export interface DsyncActivatedDataDomainResponse {
  object: 'organization_domain';
  id: string;
  domain: string;
}
