// This file is auto-generated by oagen. Do not edit.

import type { FlagRuleUpdatedContextActorSource } from './flag-rule-updated-context-actor-source.interface';

/** The actor who performed the action. */
export interface FlagRuleUpdatedContextActor {
  /** Unique identifier of the actor. */
  id: string;
  source: FlagRuleUpdatedContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface FlagRuleUpdatedContextActorResponse {
  id: string;
  source: FlagRuleUpdatedContextActorSource;
  name: string | null;
}
