// This file is auto-generated by oagen. Do not edit.

export interface FlagRuleUpdatedContextConfiguredTargetOrganization {
  /** The ID of the organization. */
  id: string;
  /** The name of the organization. */
  name: string;
}

export interface FlagRuleUpdatedContextConfiguredTargetOrganizationResponse {
  id: string;
  name: string;
}
