// This file is auto-generated by oagen. Do not edit.

import type { FlagDeletedContextActorSource } from './flag-deleted-context-actor-source.interface';

/** The actor who performed the action. */
export interface FlagDeletedContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: FlagDeletedContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface FlagDeletedContextActorResponse {
  id: string;
  source: FlagDeletedContextActorSource;
  name: string | null;
}
