// This file is auto-generated by oagen. Do not edit.

import type {
  FlagDeletedDataOwner,
  FlagDeletedDataOwnerResponse,
} from './flag-deleted-data-owner.interface';

/** The event payload. */
export interface FlagDeletedData {
  object: 'feature_flag';
  /** Unique identifier of the Feature Flag. */
  id: string;
  /** The ID of the environment the Feature Flag belongs to. */
  environmentId: string;
  /** A unique key to reference the Feature Flag. */
  slug: string;
  /** A descriptive name for the Feature Flag. */
  name: string;
  /** A description for the Feature Flag. */
  description: string | null;
  /** The owner of the Feature Flag. */
  owner: FlagDeletedDataOwner | null;
  /** Labels assigned to the Feature Flag for categorizing and filtering. */
  tags: string[];
  /** Specifies whether the Feature Flag is active for the current environment. */
  enabled: boolean;
  /** The value returned for users and organizations who don't match any configured targeting rules. */
  defaultValue: boolean;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
}

export interface FlagDeletedDataResponse {
  object: 'feature_flag';
  id: string;
  environment_id: string;
  slug: string;
  name: string;
  description: string | null;
  owner: FlagDeletedDataOwnerResponse | null;
  tags: string[];
  enabled: boolean;
  default_value: boolean;
  created_at: string;
  updated_at: string;
}
