// This file is auto-generated by oagen. Do not edit.

import type {
  InvitationRevokedData,
  InvitationRevokedDataResponse,
} from './invitation-revoked-data.interface';
import type {
  InvitationRevokedContext,
  InvitationRevokedContextResponse,
} from './invitation-revoked-context.interface';

export interface InvitationRevoked {
  /** Unique identifier for the event. */
  id: string;
  event: 'invitation.revoked';
  /** The event payload. */
  data: InvitationRevokedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: InvitationRevokedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface InvitationRevokedResponse {
  id: string;
  event: 'invitation.revoked';
  data: InvitationRevokedDataResponse;
  created_at: string;
  context?: InvitationRevokedContextResponse;
  object: 'event';
}
