// This file is auto-generated by oagen. Do not edit.

import type {
  InvitationRevokedContextGoogleAnalyticsSession,
  InvitationRevokedContextGoogleAnalyticsSessionResponse,
} from './invitation-revoked-context-google-analytics-session.interface';
import type {
  InvitationRevokedContextActor,
  InvitationRevokedContextActorResponse,
} from './invitation-revoked-context-actor.interface';

/** Additional context about the event. */
export interface InvitationRevokedContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: InvitationRevokedContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: InvitationRevokedContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface InvitationRevokedContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: InvitationRevokedContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: InvitationRevokedContextActorResponse;
  previous_attributes?: Record<string, any>;
}
