// This file is auto-generated by oagen. Do not edit.

import type { InvitationRevokedContextActorSource } from './invitation-revoked-context-actor-source.interface';

/** The actor who performed the action. */
export interface InvitationRevokedContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: InvitationRevokedContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface InvitationRevokedContextActorResponse {
  id: string;
  source: InvitationRevokedContextActorSource;
  name: string | null;
}
