// This file is auto-generated by oagen. Do not edit.

import type {
  OrganizationRoleCreatedData,
  OrganizationRoleCreatedDataResponse,
} from './organization-role-created-data.interface';

export type OrganizationRoleDeletedData = OrganizationRoleCreatedData;
export type OrganizationRoleDeletedDataResponse =
  OrganizationRoleCreatedDataResponse;
