// This file is auto-generated by oagen. Do not edit.

export enum OrganizationDomainState {
  Failed = 'failed',
  Pending = 'pending',
  Verified = 'verified',
  LegacyVerified = 'legacy_verified',
  Unverified = 'unverified',
}
