// This file is auto-generated by oagen. Do not edit.

export type OrganizationDomainVerificationFailedDataOrganizationDomainState =
  | 'failed'
  | 'legacy_verified'
  | 'pending'
  | 'unverified'
  | 'verified';
