// This file is auto-generated by oagen. Do not edit.

import type {
  OrganizationDomainVerifiedData,
  OrganizationDomainVerifiedDataResponse,
} from './organization-domain-verified-data.interface';
import type {
  OrganizationDomainVerifiedContext,
  OrganizationDomainVerifiedContextResponse,
} from './organization-domain-verified-context.interface';

export interface OrganizationDomainVerified {
  /** Unique identifier for the event. */
  id: string;
  event: 'organization_domain.verified';
  /** The event payload. */
  data: OrganizationDomainVerifiedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: OrganizationDomainVerifiedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface OrganizationDomainVerifiedResponse {
  id: string;
  event: 'organization_domain.verified';
  data: OrganizationDomainVerifiedDataResponse;
  created_at: string;
  context?: OrganizationDomainVerifiedContextResponse;
  object: 'event';
}
