// This file is auto-generated by oagen. Do not edit.

import type {
  OrganizationRoleUpdatedData,
  OrganizationRoleUpdatedDataResponse,
} from './organization-role-updated-data.interface';
import type {
  OrganizationRoleUpdatedContext,
  OrganizationRoleUpdatedContextResponse,
} from './organization-role-updated-context.interface';

export interface OrganizationRoleUpdated {
  /** Unique identifier for the event. */
  id: string;
  event: 'organization_role.updated';
  /** The event payload. */
  data: OrganizationRoleUpdatedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: OrganizationRoleUpdatedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface OrganizationRoleUpdatedResponse {
  id: string;
  event: 'organization_role.updated';
  data: OrganizationRoleUpdatedDataResponse;
  created_at: string;
  context?: OrganizationRoleUpdatedContextResponse;
  object: 'event';
}
