// This file is auto-generated by oagen. Do not edit.

import type { OrganizationMembershipCreatedDataStatus } from './organization-membership-created-data-status.interface';

/** The event payload. */
export interface OrganizationMembershipCreatedData {
  /** Distinguishes the organization membership object. */
  object: 'organization_membership';
  /** Unique identifier of the organization membership. */
  id: string;
  /** The ID of the user. */
  userId: string;
  /** The ID of the organization. */
  organizationId: string;
  /** The status of the organization membership. */
  status: OrganizationMembershipCreatedDataStatus;
  /** The role associated with the membership. */
  role: Record<string, any>;
  /** The roles associated with the membership. */
  roles?: Record<string, any>[];
  /** Custom attributes associated with the membership. */
  customAttributes: Record<string, any>;
  /** Whether the membership is managed by a directory sync provider. */
  directoryManaged: boolean;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
}

export interface OrganizationMembershipCreatedDataResponse {
  object: 'organization_membership';
  id: string;
  user_id: string;
  organization_id: string;
  status: OrganizationMembershipCreatedDataStatus;
  role: Record<string, any>;
  roles?: Record<string, any>[];
  custom_attributes: Record<string, any>;
  directory_managed: boolean;
  created_at: string;
  updated_at: string;
}
