// This file is auto-generated by oagen. Do not edit.

import type { PasswordResetCreatedContextActorSource } from './password-reset-created-context-actor-source.interface';

/** The actor who performed the action. */
export interface PasswordResetCreatedContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: PasswordResetCreatedContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface PasswordResetCreatedContextActorResponse {
  id: string;
  source: PasswordResetCreatedContextActorSource;
  name: string | null;
}
