// This file is auto-generated by oagen. Do not edit.

import type {
  PermissionDeletedData,
  PermissionDeletedDataResponse,
} from './permission-deleted-data.interface';
import type {
  PermissionDeletedContext,
  PermissionDeletedContextResponse,
} from './permission-deleted-context.interface';

export interface PermissionDeleted {
  /** Unique identifier for the event. */
  id: string;
  event: 'permission.deleted';
  /** The event payload. */
  data: PermissionDeletedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: PermissionDeletedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface PermissionDeletedResponse {
  id: string;
  event: 'permission.deleted';
  data: PermissionDeletedDataResponse;
  created_at: string;
  context?: PermissionDeletedContextResponse;
  object: 'event';
}
