// This file is auto-generated by oagen. Do not edit.

import type {
  PermissionUpdatedContextGoogleAnalyticsSession,
  PermissionUpdatedContextGoogleAnalyticsSessionResponse,
} from './permission-updated-context-google-analytics-session.interface';
import type {
  PermissionUpdatedContextActor,
  PermissionUpdatedContextActorResponse,
} from './permission-updated-context-actor.interface';

/** Additional context about the event. */
export interface PermissionUpdatedContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: PermissionUpdatedContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: PermissionUpdatedContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface PermissionUpdatedContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: PermissionUpdatedContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: PermissionUpdatedContextActorResponse;
  previous_attributes?: Record<string, any>;
}
