// This file is auto-generated by oagen. Do not edit.

import type {
  PermissionUpdatedData,
  PermissionUpdatedDataResponse,
} from './permission-updated-data.interface';
import type {
  PermissionUpdatedContext,
  PermissionUpdatedContextResponse,
} from './permission-updated-context.interface';

export interface PermissionUpdated {
  /** Unique identifier for the event. */
  id: string;
  event: 'permission.updated';
  /** The event payload. */
  data: PermissionUpdatedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: PermissionUpdatedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface PermissionUpdatedResponse {
  id: string;
  event: 'permission.updated';
  data: PermissionUpdatedDataResponse;
  created_at: string;
  context?: PermissionUpdatedContextResponse;
  object: 'event';
}
