// This file is auto-generated by oagen. Do not edit.

import type {
  PermissionCreatedData,
  PermissionCreatedDataResponse,
} from './permission-created-data.interface';
import type {
  PermissionCreatedContext,
  PermissionCreatedContextResponse,
} from './permission-created-context.interface';

export interface PermissionCreated {
  /** Unique identifier for the event. */
  id: string;
  event: 'permission.created';
  /** The event payload. */
  data: PermissionCreatedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: PermissionCreatedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface PermissionCreatedResponse {
  id: string;
  event: 'permission.created';
  data: PermissionCreatedDataResponse;
  created_at: string;
  context?: PermissionCreatedContextResponse;
  object: 'event';
}
