// This file is auto-generated by oagen. Do not edit.

import type {
  PermissionDeletedContextGoogleAnalyticsSession,
  PermissionDeletedContextGoogleAnalyticsSessionResponse,
} from './permission-deleted-context-google-analytics-session.interface';
import type {
  PermissionDeletedContextActor,
  PermissionDeletedContextActorResponse,
} from './permission-deleted-context-actor.interface';

/** Additional context about the event. */
export interface PermissionDeletedContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: PermissionDeletedContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: PermissionDeletedContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface PermissionDeletedContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: PermissionDeletedContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: PermissionDeletedContextActorResponse;
  previous_attributes?: Record<string, any>;
}
