// This file is auto-generated by oagen. Do not edit.

import type {
  RoleCreatedContextGoogleAnalyticsSession,
  RoleCreatedContextGoogleAnalyticsSessionResponse,
} from './role-created-context-google-analytics-session.interface';
import type {
  RoleCreatedContextActor,
  RoleCreatedContextActorResponse,
} from './role-created-context-actor.interface';

/** Additional context about the event. */
export interface RoleCreatedContext {
  /** The Google Analytics client ID. */
  googleAnalyticsClientId?: string;
  /** The Google Analytics sessions associated with the event. */
  googleAnalyticsSessions?: RoleCreatedContextGoogleAnalyticsSession[];
  /** The anonymous ID from analytics. */
  ajsAnonymousId?: string;
  /** The client ID associated with the event. */
  clientId?: string;
  /** The actor who performed the action. */
  actor?: RoleCreatedContextActor;
  /** Attributes that changed from their previous values. */
  previousAttributes?: Record<string, any>;
}

export interface RoleCreatedContextResponse {
  google_analytics_client_id?: string;
  google_analytics_sessions?: RoleCreatedContextGoogleAnalyticsSessionResponse[];
  ajs_anonymous_id?: string;
  client_id?: string;
  actor?: RoleCreatedContextActorResponse;
  previous_attributes?: Record<string, any>;
}
