// This file is auto-generated by oagen. Do not edit.

import type { RoleCreatedContextActorSource } from './role-created-context-actor-source.interface';

/** The actor who performed the action. */
export interface RoleCreatedContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: RoleCreatedContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface RoleCreatedContextActorResponse {
  id: string;
  source: RoleCreatedContextActorSource;
  name: string | null;
}
