// This file is auto-generated by oagen. Do not edit.

import type {
  SessionCreatedData,
  SessionCreatedDataResponse,
} from './session-created-data.interface';
import type {
  SessionCreatedContext,
  SessionCreatedContextResponse,
} from './session-created-context.interface';

export interface SessionCreated {
  /** Unique identifier for the event. */
  id: string;
  event: 'session.created';
  /** The event payload. */
  data: SessionCreatedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: SessionCreatedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface SessionCreatedResponse {
  id: string;
  event: 'session.created';
  data: SessionCreatedDataResponse;
  created_at: string;
  context?: SessionCreatedContextResponse;
  object: 'event';
}
