// This file is auto-generated by oagen. Do not edit.

export type SessionCreatedDataAuthMethod =
  | 'cross_app_auth'
  | 'external_auth'
  | 'impersonation'
  | 'magic_code'
  | 'migrated_session'
  | 'oauth'
  | 'passkey'
  | 'password'
  | 'sso'
  | 'unknown';
