// This file is auto-generated by oagen. Do not edit.

import type {
  SessionRevokedDataImpersonator,
  SessionRevokedDataImpersonatorResponse,
} from './session-revoked-data-impersonator.interface';
import type { SessionRevokedDataAuthMethod } from './session-revoked-data-auth-method.interface';
import type { SessionRevokedDataStatus } from './session-revoked-data-status.interface';

/** The event payload. */
export interface SessionRevokedData {
  /** Distinguishes the session object. */
  object: 'session';
  /** The unique ID of the session. */
  id: string;
  /** Information about the impersonator if this session was created via impersonation. */
  impersonator?: SessionRevokedDataImpersonator;
  /** The IP address from which the session was created. */
  ipAddress: string | null;
  /** The ID of the organization this session is associated with. */
  organizationId?: string;
  /** The user agent string from the device that created the session. */
  userAgent: string | null;
  /** The ID of the user this session belongs to. */
  userId: string;
  /** The authentication method used to create this session. */
  authMethod: SessionRevokedDataAuthMethod;
  /** The current status of the session. */
  status: SessionRevokedDataStatus;
  /** The timestamp when the session expires. */
  expiresAt: string;
  /** The timestamp when the session ended. */
  endedAt: string | null;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** An ISO 8601 timestamp. */
  updatedAt: string;
}

export interface SessionRevokedDataResponse {
  object: 'session';
  id: string;
  impersonator?: SessionRevokedDataImpersonatorResponse;
  ip_address: string | null;
  organization_id?: string;
  user_agent: string | null;
  user_id: string;
  auth_method: SessionRevokedDataAuthMethod;
  status: SessionRevokedDataStatus;
  expires_at: string;
  ended_at: string | null;
  created_at: string;
  updated_at: string;
}
