// This file is auto-generated by oagen. Do not edit.

import type { SessionCreatedContextActorSource } from './session-created-context-actor-source.interface';

/** The actor who performed the action. */
export interface SessionCreatedContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: SessionCreatedContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface SessionCreatedContextActorResponse {
  id: string;
  source: SessionCreatedContextActorSource;
  name: string | null;
}
