// This file is auto-generated by oagen. Do not edit.

import type {
  UserDeletedData,
  UserDeletedDataResponse,
} from './user-deleted-data.interface';
import type {
  UserDeletedContext,
  UserDeletedContextResponse,
} from './user-deleted-context.interface';

export interface UserDeleted {
  /** Unique identifier for the event. */
  id: string;
  event: 'user.deleted';
  /** The event payload. */
  data: UserDeletedData;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: UserDeletedContext;
  /** Distinguishes the Event object. */
  object: 'event';
}

export interface UserDeletedResponse {
  id: string;
  event: 'user.deleted';
  data: UserDeletedDataResponse;
  created_at: string;
  context?: UserDeletedContextResponse;
  object: 'event';
}
