// This file is auto-generated by oagen. Do not edit.

import type { VaultDataReadContextActorSource } from './vault-data-read-context-actor-source.interface';

/** The actor who performed the action. */
export interface VaultDataReadContextActor {
  /** Unique identifier of the actor. */
  id: string;
  /** The source of the actor that performed the action. */
  source: VaultDataReadContextActorSource;
  /** The name of the actor. */
  name: string | null;
}

export interface VaultDataReadContextActorResponse {
  id: string;
  source: VaultDataReadContextActorSource;
  name: string | null;
}
