// This file is auto-generated by oagen. Do not edit.

export type WidgetSessionTokenScopes =
  | 'widgets:users-table:manage'
  | 'widgets:domain-verification:manage'
  | 'widgets:sso:manage'
  | 'widgets:api-keys:manage'
  | 'widgets:dsync:manage'
  | 'widgets:audit-log-streaming:manage';
