// This file is auto-generated by oagen. Do not edit.

/** An event emitted by WorkOS. */
export interface EventSchema {
  /** Distinguishes the Event object. */
  object: 'event';
  /** Unique identifier for the Event. */
  id: string;
  /** The type of event that occurred. */
  event: string;
  /** The event payload. */
  data: Record<string, any>;
  /** An ISO 8601 timestamp. */
  createdAt: string;
  /** Additional context about the event. */
  context?: Record<string, any>;
}

export interface EventSchemaResponse {
  object: 'event';
  id: string;
  event: string;
  data: Record<string, any>;
  created_at: string;
  context?: Record<string, any>;
}
