// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import { AutoPaginatable } from '../common/utils/pagination';
import { fetchAndDeserialize } from '../common/utils/fetch-and-deserialize';
import type { CreateDataIntegrationOptions } from './interfaces/create-data-integration-options.interface';
import type { GetDataIntegrationOptions } from './interfaces/get-data-integration-options.interface';
import type { UpdateDataIntegrationOptions } from './interfaces/update-data-integration-options.interface';
import type { DeleteDataIntegrationOptions } from './interfaces/delete-data-integration-options.interface';
import type { UpdateDataIntegrationApiKeyOptions } from './interfaces/update-data-integration-api-key-options.interface';
import type { AuthorizeDataIntegrationOptions } from './interfaces/authorize-data-integration-options.interface';
import type { CreateDataIntegrationCredentialOptions } from './interfaces/create-data-integration-credential-options.interface';
import type { GetAccessTokenOptions } from './interfaces/get-access-token-options.interface';
import type { GetUserConnectedAccountOptions } from './interfaces/get-user-connected-account-options.interface';
import type { CreateUserConnectedAccountOptions } from './interfaces/create-user-connected-account-options.interface';
import type { UpdateUserConnectedAccountOptions } from './interfaces/update-user-connected-account-options.interface';
import type { DeleteUserConnectedAccountOptions } from './interfaces/delete-user-connected-account-options.interface';
import type { ListUserDataProvidersOptions } from './interfaces/list-user-data-providers-options.interface';
import type {
  DataIntegration,
  DataIntegrationResponse,
} from './interfaces/data-integration.interface';
import type {
  ConnectedAccount,
  ConnectedAccountResponse,
} from './interfaces/connected-account.interface';
import type {
  DataIntegrationAuthorizeUrlResponse,
  DataIntegrationAuthorizeUrlResponseWire,
} from './interfaces/data-integration-authorize-url-response.interface';
import type {
  DataIntegrationCredentialsResponse,
  DataIntegrationCredentialsResponseWire,
} from './interfaces/data-integration-credentials-response.interface';
import type {
  DataIntegrationAccessTokenResponse,
  DataIntegrationAccessTokenResponseWire,
} from './interfaces/data-integration-access-token-response.interface';
import type {
  DataIntegrationsListResponse,
  DataIntegrationsListResponseWire,
} from './interfaces/data-integrations-list-response.interface';
import type { CreateDataIntegrationResponse } from './interfaces/create-data-integration.interface';
import type { UpdateDataIntegrationResponse } from './interfaces/update-data-integration.interface';
import type { DataIntegrationsUpsertApiKeyRequestResponse } from './interfaces/data-integrations-upsert-api-key-request.interface';
import type { DataIntegrationsGetDataIntegrationAuthorizeUrlRequestResponse } from './interfaces/data-integrations-get-data-integration-authorize-url-request.interface';
import type { DataIntegrationsVendCredentialsRequestResponse } from './interfaces/data-integrations-vend-credentials-request.interface';
import type { DataIntegrationsGetUserTokenRequestResponse } from './interfaces/data-integrations-get-user-token-request.interface';
import type { ConnectedAccountDtoResponse } from './interfaces/connected-account-dto.interface';
import { deserializeDataIntegration } from './serializers/data-integration.serializer';
import { deserializeConnectedAccount } from './serializers/connected-account.serializer';
import { deserializeDataIntegrationAuthorizeUrlResponse } from './serializers/data-integration-authorize-url-response.serializer';
import { deserializeDataIntegrationCredentialsResponse } from './serializers/data-integration-credentials-response.serializer';
import { deserializeDataIntegrationAccessTokenResponse } from './serializers/data-integration-access-token-response.serializer';
import { deserializeDataIntegrationsListResponse } from './serializers/data-integrations-list-response.serializer';
import { serializeCreateDataIntegration } from './serializers/create-data-integration.serializer';
import { serializeUpdateDataIntegration } from './serializers/update-data-integration.serializer';
import { serializeDataIntegrationsUpsertApiKeyRequest } from './serializers/data-integrations-upsert-api-key-request.serializer';
import { serializeDataIntegrationsGetDataIntegrationAuthorizeUrlRequest } from './serializers/data-integrations-get-data-integration-authorize-url-request.serializer';
import { serializeDataIntegrationsVendCredentialsRequest } from './serializers/data-integrations-vend-credentials-request.serializer';
import { serializeDataIntegrationsGetUserTokenRequest } from './serializers/data-integrations-get-user-token-request.serializer';
import { serializeConnectedAccountDto } from './serializers/connected-account-dto.serializer';

export class Pipes {
  constructor(private readonly workos: WorkOS) {}

  /**
   * List data integrations
   *
   * Lists the environment's data integrations configured with `custom` or `organization` credentials, including custom providers.
   * @param options - Pagination and filter options.
   * @returns {Promise<AutoPaginatable<DataIntegration, PaginationOptions>>}
   * @throws {UnauthorizedException} 401
   */
  async listDataIntegrations(
    options?: PaginationOptions,
  ): Promise<AutoPaginatable<DataIntegration, PaginationOptions>> {
    const paginationOptions = options;
    return new AutoPaginatable(
      await fetchAndDeserialize<DataIntegrationResponse, DataIntegration>(
        this.workos,
        '/data-integrations',
        deserializeDataIntegration,
        paginationOptions,
      ),
      (params) =>
        fetchAndDeserialize<DataIntegrationResponse, DataIntegration>(
          this.workos,
          '/data-integrations',
          deserializeDataIntegration,
          params,
        ),
      paginationOptions,
    );
  }

  /**
   * Create a data integration
   *
   * Creates a data integration for a provider. Set `credentials.type` to `custom` to use your own OAuth app credentials, or `organization` to have each organization supply its own. For a built-in provider, pass its slug as `provider`. For a custom provider, pass a new slug plus a `custom_provider` definition.
   * @param options - Object containing provider.
   * @param options.provider - The provider to create a Data Integration for. For a built-in provider use its slug (e.g. `github`, `slack`). For a custom provider, this is the new provider slug and `custom_provider` must be supplied. A custom provider slug cannot shadow an existing global provider slug.
   * @example "github"
   * @param options.description - An optional description of the Data Integration.
   * @example "Production GitHub app"
   * @param options.enabled - Whether the Data Integration is enabled. Defaults to `false`.
   * @example true
   * @param options.scopes - The OAuth scopes to request for the Data Integration. Defaults to the provider's configured scopes when omitted.
   * @example ["repo","read:org"]
   * @param options.credentials - The credentials to configure for the Data Integration. Required for both built-in and custom providers.
   * @param options.customProvider - The OAuth definition for a custom provider. Supply this to define a custom provider; omit it to create an integration for a built-in provider.
   * @returns {Promise<DataIntegration>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async createDataIntegration(
    options: CreateDataIntegrationOptions,
  ): Promise<DataIntegration> {
    const payload = options;
    const { data } = await this.workos.post<
      DataIntegrationResponse,
      CreateDataIntegrationResponse
    >('/data-integrations', serializeCreateDataIntegration(payload));
    return deserializeDataIntegration(data);
  }

  /**
   * Get a data integration
   *
   * Retrieves a data integration by its slug.
   * @param options - The request options.
   * @param options.slug - The slug identifier of the data integration.
   * @example "github"
   * @returns {Promise<DataIntegration>}
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   */
  async getDataIntegration(
    options: GetDataIntegrationOptions,
  ): Promise<DataIntegration> {
    const { slug } = options;
    const { data } = await this.workos.get<DataIntegrationResponse>(
      `/data-integrations/${encodeURIComponent(slug)}`,
    );
    return deserializeDataIntegration(data);
  }

  /**
   * Update a data integration
   *
   * Updates the description, enabled state, or custom credentials of a data integration. For custom providers, `custom_provider` updates the OAuth definition.
   * @param options - The request body.
   * @param options.slug - The slug identifier of the data integration.
   * @example "github"
   * @param options.description - An optional description of the Data Integration.
   * @example "Production GitHub app"
   * @param options.enabled - Whether the Data Integration is enabled.
   * @example true
   * @param options.scopes - The OAuth scopes to request for the Data Integration. Pass `null` to reset to the provider's configured scopes.
   * @example ["repo","read:org"]
   * @param options.credentials - New credentials for the Data Integration. When provided, rotates the stored client secret.
   * @param options.customProvider - Updates to a custom provider's OAuth definition. Only valid for custom-provider integrations.
   * @returns {Promise<DataIntegration>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updateDataIntegration(
    options: UpdateDataIntegrationOptions,
  ): Promise<DataIntegration> {
    const { slug, ...payload } = options;
    const { data } = await this.workos.put<
      DataIntegrationResponse,
      UpdateDataIntegrationResponse
    >(
      `/data-integrations/${encodeURIComponent(slug)}`,
      serializeUpdateDataIntegration(payload),
    );
    return deserializeDataIntegration(data);
  }

  /**
   * Delete a data integration
   *
   * Deletes a data integration and all of its connected installations. For a custom provider, also deletes the custom provider definition.
   * @param options - The request options.
   * @param options.slug - The slug identifier of the data integration.
   * @example "github"
   * @returns {Promise<void>}
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   */
  async deleteDataIntegration(
    options: DeleteDataIntegrationOptions,
  ): Promise<void> {
    const { slug } = options;
    await this.workos.delete(`/data-integrations/${encodeURIComponent(slug)}`);
  }

  /**
   * Upsert an API key for a connected account
   *
   * Creates or updates an API-key-based installation for the specified integration and user. If an installation already exists, the stored API key is rotated to the new value.
   * @param options - Object containing userId, secret.
   * @param options.slug - The identifier of the integration.
   * @example "github"
   * @param options.userId - A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.organizationId - An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.secret - The API key secret to store for this integration.
   * @example "sk-1234567890abcdef"
   * @returns {Promise<ConnectedAccount>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async updateDataIntegrationApiKey(
    options: UpdateDataIntegrationApiKeyOptions,
  ): Promise<ConnectedAccount> {
    const { slug, ...payload } = options;
    const { data } = await this.workos.put<
      ConnectedAccountResponse,
      DataIntegrationsUpsertApiKeyRequestResponse
    >(
      `/data-integrations/${encodeURIComponent(slug)}/api-key`,
      serializeDataIntegrationsUpsertApiKeyRequest(payload),
    );
    return deserializeConnectedAccount(data);
  }

  /**
   * Get authorization URL
   *
   * Generates an OAuth authorization URL to initiate the connection flow for a user. Redirect the user to the returned URL to begin the OAuth flow with the third-party provider.
   * @param options - Object containing userId.
   * @param options.slug - The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
   * @example "github"
   * @param options.userId - The ID of the user to authorize.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.organizationId - An organization ID to scope the authorization to a specific organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.returnTo - The URL to redirect the user to after authorization.
   * @example "https://example.com/callback"
   * @returns {Promise<DataIntegrationAuthorizeUrlResponse>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {AuthorizationException} 403
   * @throws {NotFoundException} 404
   */
  async authorizeDataIntegration(
    options: AuthorizeDataIntegrationOptions,
  ): Promise<DataIntegrationAuthorizeUrlResponse> {
    const { slug, ...payload } = options;
    const { data } = await this.workos.post<
      DataIntegrationAuthorizeUrlResponseWire,
      DataIntegrationsGetDataIntegrationAuthorizeUrlRequestResponse
    >(
      `/data-integrations/${encodeURIComponent(slug)}/authorize`,
      serializeDataIntegrationsGetDataIntegrationAuthorizeUrlRequest(payload),
    );
    return deserializeDataIntegrationAuthorizeUrlResponse(data);
  }

  /**
   * Vend credentials for a connected account
   *
   * Returns credentials for a user's connected account. Branches on the installation's `auth_method`: OAuth installations return an access token (refreshed if needed); API-key installations return the stored secret.
   * @param options - Object containing userId.
   * @param options.slug - The identifier of the integration.
   * @example "github"
   * @param options.userId - A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.organizationId - An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @returns {Promise<DataIntegrationCredentialsResponse>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   */
  async createDataIntegrationCredential(
    options: CreateDataIntegrationCredentialOptions,
  ): Promise<DataIntegrationCredentialsResponse> {
    const { slug, ...payload } = options;
    const { data } = await this.workos.post<
      DataIntegrationCredentialsResponseWire,
      DataIntegrationsVendCredentialsRequestResponse
    >(
      `/data-integrations/${encodeURIComponent(slug)}/credentials`,
      serializeDataIntegrationsVendCredentialsRequest(payload),
    );
    return deserializeDataIntegrationCredentialsResponse(data);
  }

  /**
   * Get an access token for a connected account
   *
   * Fetches a valid OAuth access token for a user's connected account. WorkOS automatically handles token refresh, ensuring you always receive a valid, non-expired token.
   * @param options - Object containing userId.
   * @param options.provider - The identifier of the integration.
   * @example "github"
   * @param options.userId - A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.organizationId - An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @returns {Promise<DataIntegrationAccessTokenResponse>}
   * @throws {BadRequestException} 400
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async getAccessToken(
    options: GetAccessTokenOptions,
  ): Promise<DataIntegrationAccessTokenResponse> {
    const { provider, ...payload } = options;
    const { data } = await this.workos.post<
      DataIntegrationAccessTokenResponseWire,
      DataIntegrationsGetUserTokenRequestResponse
    >(
      `/data-integrations/${encodeURIComponent(provider)}/token`,
      serializeDataIntegrationsGetUserTokenRequest(payload),
    );
    return deserializeDataIntegrationAccessTokenResponse(data);
  }

  /**
   * Get a connected account
   *
   * Retrieves a user's [connected account](https://workos.com/docs/reference/pipes/connected-account) for a specific provider.
   * @param options - Additional query options.
   * @param options.userId - A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
   * @example "github"
   * @param options.organizationId - An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @returns {Promise<ConnectedAccount>}
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   */
  async getUserConnectedAccount(
    options: GetUserConnectedAccountOptions,
  ): Promise<ConnectedAccount> {
    const { userId, slug } = options;
    const { data } = await this.workos.get<ConnectedAccountResponse>(
      `/user_management/users/${encodeURIComponent(userId)}/connected_accounts/${encodeURIComponent(slug)}`,
      {
        query: {
          ...(options.organizationId !== undefined && {
            organization_id: options.organizationId,
          }),
        },
      },
    );
    return deserializeConnectedAccount(data);
  }

  /**
   * Import a connected account
   *
   * Imports a [connected account](https://workos.com/docs/reference/pipes/connected-account) for a user by providing OAuth tokens directly. Use this to migrate existing connections or set up connections without going through the OAuth flow.
   * @param options - The request body.
   * @param options.userId - A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
   * @example "github"
   * @param options.organizationId - An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.accessToken - The OAuth access token for the connected account.
   * @example "gho_16C7e42F292c6912E7710c838347Ae178B4a"
   * @param options.refreshToken - The OAuth refresh token for the connected account.
   * @example "ghr_xxxxxxxxxxxxxxxxxxxx"
   * @param options.expiresAt - The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire.
   * @example "2025-12-31T23:59:59.000Z"
   * @param options.scopes - The OAuth scopes granted for this connection.
   * @example ["repo","user:email"]
   * @param options.state - Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided.
   * @example "connected"
   * @returns {Promise<ConnectedAccount>}
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async createUserConnectedAccount(
    options: CreateUserConnectedAccountOptions,
  ): Promise<ConnectedAccount> {
    const { userId, slug, organizationId, ...payload } = options;
    const { data } = await this.workos.post<
      ConnectedAccountResponse,
      ConnectedAccountDtoResponse
    >(
      `/user_management/users/${encodeURIComponent(userId)}/connected_accounts/${encodeURIComponent(slug)}`,
      serializeConnectedAccountDto(payload),
      {
        query: {
          ...(options.organizationId !== undefined && {
            organization_id: options.organizationId,
          }),
        },
      },
    );
    return deserializeConnectedAccount(data);
  }

  /**
   * Update a connected account
   *
   * Updates a user's [connected account](https://workos.com/docs/reference/pipes/connected-account) tokens, scopes, or state for a specific provider.
   * @param options - The request body.
   * @param options.userId - A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
   * @example "github"
   * @param options.organizationId - An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.accessToken - The OAuth access token for the connected account.
   * @example "gho_16C7e42F292c6912E7710c838347Ae178B4a"
   * @param options.refreshToken - The OAuth refresh token for the connected account.
   * @example "ghr_xxxxxxxxxxxxxxxxxxxx"
   * @param options.expiresAt - The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire.
   * @example "2025-12-31T23:59:59.000Z"
   * @param options.scopes - The OAuth scopes granted for this connection.
   * @example ["repo","user:email"]
   * @param options.state - Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided.
   * @example "connected"
   * @returns {Promise<ConnectedAccount>}
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   */
  async updateUserConnectedAccount(
    options: UpdateUserConnectedAccountOptions,
  ): Promise<ConnectedAccount> {
    const { userId, slug, organizationId, ...payload } = options;
    const { data } = await this.workos.put<
      ConnectedAccountResponse,
      ConnectedAccountDtoResponse
    >(
      `/user_management/users/${encodeURIComponent(userId)}/connected_accounts/${encodeURIComponent(slug)}`,
      serializeConnectedAccountDto(payload),
      {
        query: {
          ...(options.organizationId !== undefined && {
            organization_id: options.organizationId,
          }),
        },
      },
    );
    return deserializeConnectedAccount(data);
  }

  /**
   * Delete a connected account
   *
   * Disconnects WorkOS's account for the user, including removing any stored access and refresh tokens. The user will need to reauthorize if they want to reconnect. This does not revoke access on the provider side.
   * @param options - Additional query options.
   * @param options.userId - A [User](https://workos.com/docs/reference/authkit/user) identifier.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.slug - The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
   * @example "github"
   * @param options.organizationId - An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @returns {Promise<void>}
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   */
  async deleteUserConnectedAccount(
    options: DeleteUserConnectedAccountOptions,
  ): Promise<void> {
    const { userId, slug } = options;
    await this.workos.delete(
      `/user_management/users/${encodeURIComponent(userId)}/connected_accounts/${encodeURIComponent(slug)}`,
      {
        query: {
          ...(options.organizationId !== undefined && {
            organization_id: options.organizationId,
          }),
        },
      },
    );
  }

  /**
   * List providers for a user
   *
   * Retrieves a list of available providers and the user's connection status for each. Returns all providers configured for your environment, along with the user's [connected account](https://workos.com/docs/reference/pipes/connected-account) information where applicable.
   * @param options - Additional query options.
   * @param options.userId - A [User](https://workos.com/docs/reference/authkit/user) identifier to list providers and connected accounts for.
   * @example "user_01EHZNVPK3SFK441A1RGBFSHRT"
   * @param options.organizationId - An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to filter connections for a specific organization.
   * @example "org_01EHZNVPK3SFK441A1RGBFSHRT"
   * @returns {Promise<DataIntegrationsListResponse>}
   * @throws {UnauthorizedException} 401
   * @throws {NotFoundException} 404
   */
  async listUserDataProviders(
    options: ListUserDataProvidersOptions,
  ): Promise<DataIntegrationsListResponse> {
    const { userId } = options;
    const { data } = await this.workos.get<DataIntegrationsListResponseWire>(
      `/user_management/users/${encodeURIComponent(userId)}/data_providers`,
      {
        query: {
          ...(options.organizationId !== undefined && {
            organization_id: options.organizationId,
          }),
        },
      },
    );
    return deserializeDataIntegrationsListResponse(data);
  }
}
