// This file is auto-generated by oagen. Do not edit.

import { deserializeDataIntegrationAuthorizeUrlResponse } from './serializers/data-integration-authorize-url-response.serializer';
import { deserializeConnectedAccount } from './serializers/connected-account.serializer';
import { deserializeDataIntegrationsListResponse } from './serializers/data-integrations-list-response.serializer';
import { deserializeDataIntegrationsListResponseData } from './serializers/data-integrations-list-response-data.serializer';
import { deserializeDataIntegrationAccessTokenResponseAccessToken } from './serializers/data-integration-access-token-response-access-token.serializer';
import { serializeDataIntegrationsGetDataIntegrationAuthorizeUrlRequest } from './serializers/data-integrations-get-data-integration-authorize-url-request.serializer';
import { serializeDataIntegrationsGetUserTokenRequest } from './serializers/data-integrations-get-user-token-request.serializer';
import { deserializeDataIntegrationsListResponseDataConnectedAccount } from './serializers/data-integrations-list-response-data-connected-account.serializer';
import type { DataIntegrationAuthorizeUrlResponseWire } from './interfaces/data-integration-authorize-url-response.interface';
import type { ConnectedAccountResponse } from './interfaces/connected-account.interface';
import type { DataIntegrationsListResponseWire } from './interfaces/data-integrations-list-response.interface';
import type { DataIntegrationsListResponseDataResponse } from './interfaces/data-integrations-list-response-data.interface';
import type { DataIntegrationAccessTokenResponseAccessTokenResponse } from './interfaces/data-integration-access-token-response-access-token.interface';
import type { DataIntegrationsGetDataIntegrationAuthorizeUrlRequestResponse } from './interfaces/data-integrations-get-data-integration-authorize-url-request.interface';
import type { DataIntegrationsGetUserTokenRequestResponse } from './interfaces/data-integrations-get-user-token-request.interface';
import type { DataIntegrationsListResponseDataConnectedAccountResponse } from './interfaces/data-integrations-list-response-data-connected-account.interface';
import dataIntegrationAuthorizeUrlResponseFixture from './fixtures/data-integration-authorize-url-response.json';
import connectedAccountFixture from './fixtures/connected-account.json';
import dataIntegrationsListResponseFixture from './fixtures/data-integrations-list-response.json';
import dataIntegrationsListResponseDataFixture from './fixtures/data-integrations-list-response-data.json';
import dataIntegrationAccessTokenResponseAccessTokenFixture from './fixtures/data-integration-access-token-response-access-token.json';
import dataIntegrationsGetDataIntegrationAuthorizeUrlRequestFixture from './fixtures/data-integrations-get-data-integration-authorize-url-request.json';
import dataIntegrationsGetUserTokenRequestFixture from './fixtures/data-integrations-get-user-token-request.json';
import dataIntegrationsListResponseDataConnectedAccountFixture from './fixtures/data-integrations-list-response-data-connected-account.json';

describe('DataIntegrationAuthorizeUrlResponseSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      dataIntegrationAuthorizeUrlResponseFixture as DataIntegrationAuthorizeUrlResponseWire;
    const deserialized =
      deserializeDataIntegrationAuthorizeUrlResponse(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('ConnectedAccountSerializer', () => {
  it('deserializes correctly', () => {
    const fixture = connectedAccountFixture as ConnectedAccountResponse;
    const deserialized = deserializeConnectedAccount(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('DataIntegrationsListResponseSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      dataIntegrationsListResponseFixture as DataIntegrationsListResponseWire;
    const deserialized = deserializeDataIntegrationsListResponse(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('DataIntegrationsListResponseDataSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      dataIntegrationsListResponseDataFixture as DataIntegrationsListResponseDataResponse;
    const deserialized = deserializeDataIntegrationsListResponseData(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('DataIntegrationAccessTokenResponseAccessTokenSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      dataIntegrationAccessTokenResponseAccessTokenFixture as DataIntegrationAccessTokenResponseAccessTokenResponse;
    const deserialized =
      deserializeDataIntegrationAccessTokenResponseAccessToken(fixture);
    expect(deserialized).toBeDefined();
  });
});

describe('DataIntegrationsGetDataIntegrationAuthorizeUrlRequestSerializer', () => {
  it('serializes correctly', () => {
    const fixture =
      dataIntegrationsGetDataIntegrationAuthorizeUrlRequestFixture as DataIntegrationsGetDataIntegrationAuthorizeUrlRequestResponse;
    const serialized =
      serializeDataIntegrationsGetDataIntegrationAuthorizeUrlRequest(
        fixture as any,
      );
    expect(serialized).toBeDefined();
  });
});

describe('DataIntegrationsGetUserTokenRequestSerializer', () => {
  it('serializes correctly', () => {
    const fixture =
      dataIntegrationsGetUserTokenRequestFixture as DataIntegrationsGetUserTokenRequestResponse;
    const serialized = serializeDataIntegrationsGetUserTokenRequest(
      fixture as any,
    );
    expect(serialized).toBeDefined();
  });
});

describe('DataIntegrationsListResponseDataConnectedAccountSerializer', () => {
  it('deserializes correctly', () => {
    const fixture =
      dataIntegrationsListResponseDataConnectedAccountFixture as DataIntegrationsListResponseDataConnectedAccountResponse;
    const deserialized =
      deserializeDataIntegrationsListResponseDataConnectedAccount(fixture);
    expect(deserialized).toBeDefined();
  });
});
