// This file is auto-generated by oagen. Do not edit.

import type { CreateDataIntegration } from './create-data-integration.interface';

export type CreateDataIntegrationOptions = CreateDataIntegration;
