// This file is auto-generated by oagen. Do not edit.

export const CreateOrganizationConnectedAccountState = {
  Connected: 'connected',
  NeedsReauthorization: 'needs_reauthorization',
} as const;

export type CreateOrganizationConnectedAccountState =
  (typeof CreateOrganizationConnectedAccountState)[keyof typeof CreateOrganizationConnectedAccountState];
