// This file is auto-generated by oagen. Do not edit.

import type { DataIntegrationsVendCredentialsRequest } from './data-integrations-vend-credentials-request.interface';

export interface CreateDataIntegrationCredentialOptions extends DataIntegrationsVendCredentialsRequest {
  /** The identifier of the integration. */
  slug: string;
}
