// This file is auto-generated by oagen. Do not edit.

import type { DataIntegrationCredentialsDto } from './data-integration-credentials-dto.interface';
import type { CustomProviderDefinition } from './custom-provider-definition.interface';

export interface CreateDataIntegrationOptions {
  /** The provider to create a Data Integration for. For a built-in provider use its slug (e.g. `github`, `slack`). For a custom provider, this is the new provider slug and `custom_provider` must be supplied. A custom provider slug cannot shadow an existing global provider slug. */
  provider: string;
  /** An optional description of the Data Integration. */
  description?: string | null;
  /** Whether the Data Integration is enabled. Defaults to `false`. */
  enabled?: boolean;
  /** The OAuth scopes to request for the Data Integration. Defaults to the provider's configured scopes when omitted. */
  scopes?: string[] | null;
  /** The credentials to configure for the Data Integration. Required for both built-in and custom providers. */
  credentials?: DataIntegrationCredentialsDto;
  /** The OAuth definition for a custom provider. Supply this to define a custom provider; omit it to create an integration for a built-in provider. */
  customProvider?: CustomProviderDefinition;
}
