// This file is auto-generated by oagen. Do not edit.

import type { CustomProviderDefinitionAuthenticateVia } from './custom-provider-definition-authenticate-via.interface';

export interface CustomProviderDefinition {
  /** A descriptive name for the custom provider. */
  name: string;
  /** The provider's OAuth authorization endpoint. Required for OAuth providers; omit for `api_key` providers. Must be a static URL: `${config.…}` placeholders are resolved against a provider's declared config fields, which custom providers cannot declare. */
  authorizationUrl?: string;
  /** The provider's OAuth token endpoint. Required for OAuth and `client_credentials` providers; omit for `api_key` providers. Must be a static URL: `${config.…}` placeholders are resolved against a provider's declared config fields, which custom providers cannot declare. */
  tokenUrl?: string;
  /** The endpoint used to refresh tokens, if different from the token endpoint. Must be a static URL, like the other endpoints. */
  refreshTokenUrl?: string | null;
  /** Whether PKCE is used during the authorization code flow. Defaults to `true`. */
  pkceEnabled?: boolean;
  /** The separator used to join requested scopes. Defaults to a space. */
  requestScopeSeparator?: string;
  /** Whether at least one scope must be selected when connecting an account. Defaults to `false`. */
  scopesRequired?: boolean;
  /** Whether a client secret is required for this provider. Defaults to `true`. */
  clientSecretRequired?: boolean;
  /** Additional static query parameters appended to the authorization request. */
  additionalAuthorizationParameters?: Record<string, string>;
  /** The Content-Type used when exchanging the token request. */
  tokenBodyContentType?: string;
  /** How client credentials are sent when exchanging authorization codes and refreshing tokens. */
  authenticateVia?: CustomProviderDefinitionAuthenticateVia;
}

export interface CustomProviderDefinitionResponse {
  name: string;
  authorization_url?: string;
  token_url?: string;
  refresh_token_url?: string | null;
  pkce_enabled?: boolean;
  request_scope_separator?: string;
  scopes_required?: boolean;
  client_secret_required?: boolean;
  additional_authorization_parameters?: Record<string, string>;
  token_body_content_type?: string;
  authenticate_via?: CustomProviderDefinitionAuthenticateVia;
}
