// This file is auto-generated by oagen. Do not edit.

export const DataIntegrationsListResponseDataConnectedAccountAuthMethod = {
  OAuth: 'oauth',
  ApiKey: 'api_key',
  ClientCredentials: 'client_credentials',
} as const;

export type DataIntegrationsListResponseDataConnectedAccountAuthMethod =
  (typeof DataIntegrationsListResponseDataConnectedAccountAuthMethod)[keyof typeof DataIntegrationsListResponseDataConnectedAccountAuthMethod];
