// This file is auto-generated by oagen. Do not edit.

import type {
  DataIntegrationCredentialsResponseCredential,
  DataIntegrationCredentialsResponseCredentialResponse,
} from './data-integration-credentials-response-credential.interface';
import type { DataIntegrationCredentialsResponseError } from './data-integration-credentials-response-error.interface';

export interface DataIntegrationCredentialsResponse {
  /** Indicates credentials are available. */
  active?: true;
  /** The credential object containing the vended secret. */
  credential?: DataIntegrationCredentialsResponseCredential;
  /**
   * The reason credentials are unavailable. Additional values may be added in the future; handle unknown values gracefully.
   * - `"not_installed"`: The user does not have the integration installed.
   * - `"needs_reauthorization"`: The user needs to reauthorize the integration.
   */
  error?: DataIntegrationCredentialsResponseError;
}

export interface DataIntegrationCredentialsResponseWire {
  active?: true;
  credential?: DataIntegrationCredentialsResponseCredentialResponse;
  error?: DataIntegrationCredentialsResponseError;
}
