// This file is auto-generated by oagen. Do not edit.

export interface DataIntegrationsUpsertApiKeyRequest {
  /** A [User](https://workos.com/docs/reference/authkit/user) identifier. */
  userId: string;
  /** An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization. */
  organizationId?: string;
  /** The API key secret to store for this integration. */
  secret: string;
}

export interface DataIntegrationsUpsertApiKeyRequestResponse {
  user_id: string;
  organization_id?: string;
  secret: string;
}
