// This file is auto-generated by oagen. Do not edit.

export const UpdateCustomProviderDefinitionAuthenticateVia = {
  RequestBody: 'request_body',
  BasicAuthHeader: 'basic_auth_header',
} as const;

export type UpdateCustomProviderDefinitionAuthenticateVia =
  (typeof UpdateCustomProviderDefinitionAuthenticateVia)[keyof typeof UpdateCustomProviderDefinitionAuthenticateVia];
