// This file is auto-generated by oagen. Do not edit.

import type {
  DataIntegrationCredentialsInput,
  DataIntegrationCredentialsInputResponse,
} from './data-integration-credentials-input.interface';
import type {
  ApiKeyInstallation,
  ApiKeyInstallationResponse,
} from './api-key-installation.interface';
import type {
  UpdateCustomProviderDefinition,
  UpdateCustomProviderDefinitionResponse,
} from './update-custom-provider-definition.interface';

export interface UpdateDataIntegration {
  /** An optional description of the Data Integration. */
  description?: string | null;
  /** Whether the Data Integration is enabled. */
  enabled?: boolean;
  /** The OAuth scopes to request for the Data Integration. Pass `null` to reset to the provider's configured scopes. */
  scopes?: string[] | null;
  /** New OAuth credentials for the Data Integration. When provided, rotates the stored client secret. Mutually exclusive with `api_key`. */
  credentials?: DataIntegrationCredentialsInput;
  /** An API key to install or rotate for a tenant on an `api_key` integration. Upserts the tenant installation identified by `user_id` (and optional `organization_id`). */
  apiKey?: ApiKeyInstallation;
  /** Updates to a custom provider's OAuth definition. Only valid for custom-provider integrations. */
  customProvider?: UpdateCustomProviderDefinition;
}

export interface UpdateDataIntegrationResponse {
  description?: string | null;
  enabled?: boolean;
  scopes?: string[] | null;
  credentials?: DataIntegrationCredentialsInputResponse;
  api_key?: ApiKeyInstallationResponse;
  custom_provider?: UpdateCustomProviderDefinitionResponse;
}
