// This file is auto-generated by oagen. Do not edit.

import type {
  CreateObjectRequest,
  CreateObjectRequestResponse,
} from '../interfaces/create-object-request.interface';

export const serializeCreateObjectRequest = (
  model: CreateObjectRequest,
): CreateObjectRequestResponse => ({
  key_context: model.keyContext,
  name: model.name,
  value: model.value,
});
