// This file is auto-generated by oagen. Do not edit.

import type {
  DecryptRequest,
  DecryptRequestResponse,
} from '../interfaces/decrypt-request.interface';

export const serializeDecryptRequest = (
  model: DecryptRequest,
): DecryptRequestResponse => ({
  keys: model.keys,
});
