// This file is auto-generated by oagen. Do not edit.

import type {
  ListMetadata,
  ListMetadataResponse,
} from '../interfaces/list-metadata.interface';

export const deserializeListMetadata = (
  response: ListMetadataResponse,
): ListMetadata => ({
  after: response.after ?? null,
  before: response.before ?? null,
});

export const serializeListMetadata = (
  model: ListMetadata,
): ListMetadataResponse => ({
  after: model.after ?? null,
  before: model.before ?? null,
});
