// This file is auto-generated by oagen. Do not edit.

import type {
  ObjectMetadata,
  ObjectMetadataResponse,
} from '../interfaces/object-metadata.interface';
import { deserializeActor } from './actor.serializer';

export const deserializeObjectMetadata = (
  response: ObjectMetadataResponse,
): ObjectMetadata => ({
  context: response.context,
  environmentId: response.environment_id,
  id: response.id,
  keyId: response.key_id,
  updatedAt: new Date(response.updated_at),
  updatedBy: deserializeActor(response.updated_by),
  versionId: response.version_id ?? null,
});
