// This file is auto-generated by oagen. Do not edit.

import type {
  RekeyRequest,
  RekeyRequestResponse,
} from '../interfaces/rekey-request.interface';

export const serializeRekeyRequest = (
  model: RekeyRequest,
): RekeyRequestResponse => ({
  context: model.context,
  encrypted_keys: model.encryptedKeys,
});
