// This file is auto-generated by oagen. Do not edit.

import type {
  VersionListResponse,
  VersionListResponseWire,
} from '../interfaces/version-list-response.interface';
import { deserializeObjectVersion } from './object-version.serializer';
import { deserializeListMetadata } from './list-metadata.serializer';

export const deserializeVersionListResponse = (
  response: VersionListResponseWire,
): VersionListResponse => ({
  data: response.data.map(deserializeObjectVersion),
  listMetadata: deserializeListMetadata(response.list_metadata),
});
