// This file is auto-generated by oagen. Do not edit.

export const RadarType = {
  IpAddress: 'ip_address',
  Domain: 'domain',
  Email: 'email',
  Device: 'device',
  UserAgent: 'user_agent',
  DeviceFingerprint: 'device_fingerprint',
  Country: 'country',
} as const;

export type RadarType = (typeof RadarType)[keyof typeof RadarType];
