// This file is auto-generated by oagen. Do not edit.

export interface RadarStandaloneDeleteRadarListEntryRequest {
  /** The value to remove from the list. Must match an existing entry. */
  entry: string;
}

export interface RadarStandaloneDeleteRadarListEntryRequestResponse {
  entry: string;
}
