// This file is auto-generated by oagen. Do not edit.

import type { RadarStandaloneResponseVerdict } from '../../common/interfaces/radar-standalone-response-verdict.interface';
import type { RadarStandaloneResponseControl } from '../../common/interfaces/radar-standalone-response-control.interface';
import type { RadarStandaloneResponseBlocklistType } from '../../common/interfaces/radar-standalone-response-blocklist-type.interface';

export interface RadarStandaloneResponse {
  /** The verdict of the risk assessment. */
  verdict: RadarStandaloneResponseVerdict;
  /** A human-readable reason for the verdict. */
  reason: string;
  /** Unique identifier of the authentication attempt. */
  attemptId: string;
  /** The Radar control that triggered the verdict. Only present if the verdict is `block` or `challenge`. */
  control?: RadarStandaloneResponseControl;
  /** The type of blocklist entry that triggered the verdict. Only present if the control is `restriction`. */
  blocklistType?: RadarStandaloneResponseBlocklistType;
}

export interface RadarStandaloneResponseWire {
  verdict: RadarStandaloneResponseVerdict;
  reason: string;
  attempt_id: string;
  control?: RadarStandaloneResponseControl;
  blocklist_type?: RadarStandaloneResponseBlocklistType;
}
