// This file is auto-generated by oagen. Do not edit.

import type { RadarStandaloneAssessRequestAuthMethod } from '../../common/interfaces/radar-standalone-assess-request-auth-method.interface';
import type { RadarStandaloneAssessRequestAction } from '../../common/interfaces/radar-standalone-assess-request-action.interface';

export interface RadarStandaloneAssessRequest {
  /** The IP address of the request to assess. */
  ipAddress: string;
  /** The user agent string of the request to assess. */
  userAgent: string;
  /** The email address of the user making the request. */
  email: string;
  /** The authentication method being used. */
  authMethod: RadarStandaloneAssessRequestAuthMethod;
  /** The action being performed. */
  action: RadarStandaloneAssessRequestAction;
  /** An optional device fingerprint for the request. */
  deviceFingerprint?: string;
  /** An optional bot detection score for the request. */
  botScore?: string;
}

export interface RadarStandaloneAssessRequestResponse {
  ip_address: string;
  user_agent: string;
  email: string;
  auth_method: RadarStandaloneAssessRequestAuthMethod;
  action: RadarStandaloneAssessRequestAction;
  device_fingerprint?: string;
  bot_score?: string;
}
