// This file is auto-generated by oagen. Do not edit.

import type { RadarListType } from './radar-list-type.interface';
import type { RadarListAction } from './radar-list-action.interface';

export interface RemoveListEntryOptions {
  /** The type of the Radar list (e.g. ip_address, domain, email). */
  type: RadarListType;
  /** The list action indicating whether to remove the entry from the allow or block list. */
  action: RadarListAction;
  /** The value to remove from the list. Must match an existing entry. */
  entry: string;
}
