// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type { PaginationOptions } from '../common/interfaces/pagination-options.interface';
import type { AutoPaginatable } from '../common/utils/pagination';
import { createPaginatedList } from '../common/utils/fetch-and-deserialize';
import type {
  AuthorizationPermission,
  AuthorizationPermissionResponse,
} from './interfaces/authorization-permission.interface';
import type {
  Permission,
  PermissionResponse,
} from './interfaces/permission.interface';
import type { CreateAuthorizationPermission } from './interfaces/create-authorization-permission.interface';
import type { UpdateAuthorizationPermission } from './interfaces/update-authorization-permission.interface';
import { deserializeAuthorizationPermission } from './serializers/authorization-permission.serializer';
import { deserializePermission } from './serializers/permission.serializer';
import { serializeCreateAuthorizationPermission } from './serializers/create-authorization-permission.serializer';
import { serializeUpdateAuthorizationPermission } from './serializers/update-authorization-permission.serializer';

export class Permissions {
  constructor(private readonly workos: WorkOS) {}

  /**
   * List permissions
   *
   * Get a list of all permissions in your WorkOS environment.
   * @param options - Pagination and filter options.
   * @returns {AutoPaginatable<AuthorizationPermission>}
   * @throws {NotFoundException} 404
   */
  async list(
    options?: PaginationOptions,
  ): Promise<AutoPaginatable<AuthorizationPermission, PaginationOptions>> {
    return createPaginatedList<
      AuthorizationPermissionResponse,
      AuthorizationPermission,
      PaginationOptions
    >(
      this.workos,
      '/authorization/permissions',
      deserializeAuthorizationPermission,
      options,
    );
  }

  /**
   * Create a permission
   *
   * Create a new permission in your WorkOS environment. The permission can then be assigned to environment roles and organization roles.
   * @param payload - Object containing slug, name.
   * @returns {Permission}
   * @throws {BadRequestException} 400
   * @throws {NotFoundException} 404
   * @throws {ConflictException} 409
   * @throws {UnprocessableEntityException} 422
   */
  async create(payload: CreateAuthorizationPermission): Promise<Permission> {
    const { data } = await this.workos.post<PermissionResponse>(
      '/authorization/permissions',
      serializeCreateAuthorizationPermission(payload),
    );
    return deserializePermission(data);
  }

  /**
   * Get a permission
   *
   * Retrieve a permission by its unique slug.
   * @param slug - A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
   * @example "documents:read"
   * @returns {AuthorizationPermission}
   * @throws {NotFoundException} 404
   */
  async find(slug: string): Promise<AuthorizationPermission> {
    const { data } = await this.workos.get<AuthorizationPermissionResponse>(
      `/authorization/permissions/${slug}`,
    );
    return deserializeAuthorizationPermission(data);
  }

  /**
   * Update a permission
   *
   * Update an existing permission. Only the fields provided in the request body will be updated.
   * @param slug - A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
   * @example "documents:read"
   * @param payload - The request body.
   * @returns {AuthorizationPermission}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async update(
    slug: string,
    payload: UpdateAuthorizationPermission,
  ): Promise<AuthorizationPermission> {
    const { data } = await this.workos.patch<AuthorizationPermissionResponse>(
      `/authorization/permissions/${slug}`,
      serializeUpdateAuthorizationPermission(payload),
    );
    return deserializeAuthorizationPermission(data);
  }

  /**
   * Delete a permission
   *
   * Delete an existing permission. System permissions cannot be deleted.
   * @param slug - A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
   * @example "documents:read"
   * @returns {void}
   * @throws {NotFoundException} 404
   */
  async delete(slug: string): Promise<void> {
    await this.workos.delete(`/authorization/permissions/${slug}`);
  }
}
