// This file is auto-generated by oagen. Do not edit.

import fetch from 'jest-fetch-mock';
import {
  fetchOnce,
  fetchURL,
  fetchMethod,
  fetchSearchParams,
  fetchBody,
} from '../common/utils/test-utils';
import { WorkOS } from '../workos';

import listFlagTargetFixture from './fixtures/list-flag-target.json';
import flagTargetFixture from './fixtures/flag-target.json';

const workos = new WorkOS('sk_test_Sz3IQjepeSWaI4cMS4ms4sMuU');

function expectFlagTarget(result: any) {
  expect(result.object).toBe('flag_target');
  expect(result.id).toBe('flag_target_01EHZNVPK3SFK441A1RGBFSHRT');
  expect(result.flagId).toBe('flag_01EHZNVPK3SFK441A1RGBFSHRT');
  expect(result.flagSlug).toBe('new-checkout');
  expect(result.environmentId).toBe('environment_01EHWNCE74X7JSDV0X3SZ3KJNY');
  expect(result.targetType).toBe('organization');
  expect(result.targetId).toBe('org_01EHWNCE74X7JSDV0X3SZ3KJNY');
  expect(result.valueType).toBe('boolean');
  expect(result.value).toBe(true);
  expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
  expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
}

describe('FlagTargets', () => {
  beforeEach(() => fetch.resetMocks());

  describe('listFlagTargets', () => {
    it('returns paginated results', async () => {
      fetchOnce(listFlagTargetFixture);

      const { data, listMetadata } = await workos.flagTargets.listFlagTargets({
        order: 'desc',
        flagSlug: 'new-checkout',
        targetType: 'organization',
        targetId: 'org_01EHWNCE74X7JSDV0X3SZ3KJNY',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe('/flag_targets');
      expect(fetchSearchParams()).toHaveProperty('order');
      expect(Array.isArray(data)).toBe(true);
      expect(listMetadata).toBeDefined();
      expect(data.length).toBeGreaterThan(0);
      expectFlagTarget(data[0]);
    });
  });

  describe('createFlagTarget', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(flagTargetFixture);

      const result = await workos.flagTargets.createFlagTarget({
        flagSlug: 'test_flag_slug',
        targetType: 'test_target_type',
        targetId: 'target_id_01234',
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe('/flag_targets');
      expect(fetchBody()).toEqual(
        expect.objectContaining({
          flag_slug: 'test_flag_slug',
          target_type: 'test_target_type',
          target_id: 'target_id_01234',
        }),
      );
      expectFlagTarget(result);
    });
  });

  describe('getFlagTarget', () => {
    it('returns the expected result', async () => {
      fetchOnce(flagTargetFixture);

      const result = await workos.flagTargets.getFlagTarget({ id: 'test_id' });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/flag_targets/test_id',
      );
      expectFlagTarget(result);
    });
  });

  describe('deleteFlagTarget', () => {
    it('sends a DELETE request', async () => {
      fetchOnce({}, { status: 204 });

      await workos.flagTargets.deleteFlagTarget({ id: 'test_id' });

      expect(fetchMethod()).toBe('DELETE');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/flag_targets/test_id',
      );
    });
  });
});
