// This file is auto-generated by oagen. Do not edit.

import type {
  AddRolePermission,
  AddRolePermissionResponse,
} from '../interfaces/add-role-permission.interface';

export const serializeAddRolePermission = (
  model: AddRolePermission,
): AddRolePermissionResponse => ({
  slug: model.slug,
});
