// This file is auto-generated by oagen. Do not edit.

import type {
  AuthorizationOrganizationRolesListItem,
  AuthorizationOrganizationRolesListItemResponse,
} from '../interfaces/authorization-organization-roles-list-item.interface';

export const deserializeAuthorizationOrganizationRolesListItem = (
  response: AuthorizationOrganizationRolesListItemResponse,
): AuthorizationOrganizationRolesListItem => ({
  slug: response.slug,
  object: response.object,
  id: response.id,
  name: response.name,
  description: response.description ?? null,
  type: response.type,
  resourceTypeSlug: response.resource_type_slug,
  permissions: response.permissions,
  createdAt: response.created_at,
  updatedAt: response.updated_at,
});

export const serializeAuthorizationOrganizationRolesListItem = (
  model: AuthorizationOrganizationRolesListItem,
): AuthorizationOrganizationRolesListItemResponse => ({
  slug: model.slug,
  object: model.object,
  id: model.id,
  name: model.name,
  description: model.description,
  type: model.type,
  resource_type_slug: model.resourceTypeSlug,
  permissions: model.permissions,
  created_at: model.createdAt,
  updated_at: model.updatedAt,
});
