// This file is auto-generated by oagen. Do not edit.

export {
  deserializeCreateAuthorizationPermission as deserializeCreateRole,
  serializeCreateAuthorizationPermission as serializeCreateRole,
} from './create-authorization-permission.serializer';
