// This file is auto-generated by oagen. Do not edit.

import type {
  RemoveRole,
  RemoveRoleResponse,
} from '../interfaces/remove-role.interface';

export const serializeRemoveRole = (model: RemoveRole): RemoveRoleResponse => ({
  role_slug: model.roleSlug,
  resource_id: model.resourceId,
  resource_external_id: model.resourceExternalId,
  resource_type_slug: model.resourceTypeSlug,
});
