// This file is auto-generated by oagen. Do not edit.

import type {
  UpdateOrganizationRolePriorityOrder,
  UpdateOrganizationRolePriorityOrderResponse,
} from '../interfaces/update-organization-role-priority-order.interface';

export const deserializeUpdateOrganizationRolePriorityOrder = (
  response: UpdateOrganizationRolePriorityOrderResponse,
): UpdateOrganizationRolePriorityOrder => ({
  rolePriorityOrder: response.role_priority_order,
});

export const serializeUpdateOrganizationRolePriorityOrder = (
  model: UpdateOrganizationRolePriorityOrder,
): UpdateOrganizationRolePriorityOrderResponse => ({
  role_priority_order: model.rolePriorityOrder,
});
