// This file is auto-generated by oagen. Do not edit.

import type {
  UpdateOrganizationRole,
  UpdateOrganizationRoleResponse,
} from '../interfaces/update-organization-role.interface';

export const deserializeUpdateOrganizationRole = (
  response: UpdateOrganizationRoleResponse,
): UpdateOrganizationRole => ({
  name: response.name,
  description: response.description ?? null,
});

export const serializeUpdateOrganizationRole = (
  model: UpdateOrganizationRole,
): UpdateOrganizationRoleResponse => ({
  name: model.name,
  description: model.description ?? null,
});
