// This file is auto-generated by oagen. Do not edit.

import type {
  UserRoleAssignmentResource,
  UserRoleAssignmentResourceResponse,
} from '../interfaces/user-role-assignment-resource.interface';

export const deserializeUserRoleAssignmentResource = (
  response: UserRoleAssignmentResourceResponse,
): UserRoleAssignmentResource => ({
  id: response.id,
  externalId: response.external_id,
  resourceTypeSlug: response.resource_type_slug,
});
