// This file is auto-generated by oagen. Do not edit.

import fetch from 'jest-fetch-mock';
import {
  fetchOnce,
  fetchURL,
  fetchMethod,
  fetchSearchParams,
  fetchBody,
} from '../common/utils/test-utils';
import { WorkOS } from '../workos';

import listFlagTargetTypeFixture from './fixtures/list-flag-target-type.json';
import flagTargetTypeFixture from './fixtures/flag-target-type.json';

const workos = new WorkOS('sk_test_Sz3IQjepeSWaI4cMS4ms4sMuU');

function expectFlagTargetType(result: any) {
  expect(result.object).toBe('flag_target_type');
  expect(result.id).toBe('flag_target_type_01EHZNVPK3SFK441A1RGBFSHRT');
  expect(result.slug).toBe('workspace');
  expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
  expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
}

describe('FlagTargetTypes', () => {
  beforeEach(() => fetch.resetMocks());

  describe('listFlagTargetTypes', () => {
    it('returns paginated results', async () => {
      fetchOnce(listFlagTargetTypeFixture);

      const { data, listMetadata } =
        await workos.flagTargetTypes.listFlagTargetTypes({ order: 'desc' });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe('/flag_target_types');
      expect(fetchSearchParams()).toHaveProperty('order');
      expect(Array.isArray(data)).toBe(true);
      expect(listMetadata).toBeDefined();
      expect(data.length).toBeGreaterThan(0);
      expectFlagTargetType(data[0]);
    });
  });

  describe('createFlagTargetType', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(flagTargetTypeFixture);

      const result = await workos.flagTargetTypes.createFlagTargetType({
        slug: 'test_slug',
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe('/flag_target_types');
      expect(fetchBody()).toEqual(
        expect.objectContaining({ slug: 'test_slug' }),
      );
      expectFlagTargetType(result);
    });
  });

  describe('getFlagTargetType', () => {
    it('returns the expected result', async () => {
      fetchOnce(flagTargetTypeFixture);

      const result = await workos.flagTargetTypes.getFlagTargetType({
        id: 'test_id',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/flag_target_types/test_id',
      );
      expectFlagTargetType(result);
    });
  });
});
