// This file is auto-generated by oagen. Do not edit.

import fetch, { MockParams } from 'jest-fetch-mock';

export function fetchOnce(
  response = {},
  { status = 200, headers, ...rest }: MockParams = {},
) {
  return fetch.once(JSON.stringify(response), {
    status,
    headers: { 'content-type': 'application/json;charset=UTF-8', ...headers },
    ...rest,
  });
}

export function fetchURL() {
  return fetch.mock.calls[0][0];
}

export function fetchSearchParams() {
  return Object.fromEntries(new URL(String(fetchURL())).searchParams);
}

export function fetchHeaders() {
  return fetch.mock.calls[0][1]?.headers;
}

export function fetchMethod() {
  return fetch.mock.calls[0][1]?.method;
}

export function fetchBody({ raw = false } = {}) {
  const body = fetch.mock.calls[0][1]?.body;
  if (body instanceof URLSearchParams) {
    return body.toString();
  }
  if (raw) {
    return body;
  }
  return JSON.parse(String(body));
}

/**
 * Shared test helper: asserts that the given async function throws when the
 * server responds with 401 Unauthorized.
 */
export function testUnauthorized(fn: () => Promise<any>) {
  it('throws on unauthorized', async () => {
    fetchOnce({ message: 'Unauthorized' }, { status: 401 });
    await expect(fn()).rejects.toThrow('Could not authorize the request');
  });
}

/**
 * Shared test helper: asserts that a paginated list call returns the expected
 * shape (data array + listMetadata) and hits the correct endpoint.
 */
export function testPaginatedList(
  fn: () => Promise<any>,
  pathContains: string,
) {
  it('returns paginated results', async () => {
    // Caller must have called fetchOnce with the list fixture before invoking fn
    const { data, listMetadata } = await fn();
    expect(fetchURL()).toContain(pathContains);
    expect(fetchSearchParams()).toHaveProperty('order');
    expect(Array.isArray(data)).toBe(true);
    expect(listMetadata).toBeDefined();
  });
}

/**
 * Shared test helper: asserts that a paginated list call returns empty data
 * when the server responds with an empty list.
 */
export function testEmptyResults(fn: () => Promise<any>) {
  it('handles empty results', async () => {
    fetchOnce({ data: [], list_metadata: { before: null, after: null } });
    const { data } = await fn();
    expect(data).toEqual([]);
  });
}

/**
 * Shared test helper: asserts that pagination params are forwarded correctly.
 */
export function testPaginationParams(
  fn: (opts: any) => Promise<any>,
  fixture: any,
) {
  it('forwards pagination params', async () => {
    fetchOnce(fixture);
    await fn({ limit: 10, after: 'cursor_abc' });
    expect(fetchSearchParams()['limit']).toBe('10');
    expect(fetchSearchParams()['after']).toBe('cursor_abc');
  });
}
