// This file is auto-generated by oagen. Do not edit.

import fetch from 'jest-fetch-mock';
import {
  fetchOnce,
  fetchURL,
  fetchMethod,
  fetchSearchParams,
  fetchBody,
} from '../common/utils/test-utils';
import { WorkOS } from '../workos';

import auditLogsRetentionFixture from './fixtures/audit-logs-retention.json';
import listAuditLogActionFixture from './fixtures/list-audit-log-action.json';
import listAuditLogSchemaFixture from './fixtures/list-audit-log-schema.json';
import auditLogSchemaFixture from './fixtures/audit-log-schema.json';
import auditLogEventCreateResponseFixture from './fixtures/audit-log-event-create-response.json';
import auditLogExportFixture from './fixtures/audit-log-export.json';

const workos = new WorkOS('sk_test_Sz3IQjepeSWaI4cMS4ms4sMuU');

function expectAuditLogsRetention(result: any) {
  expect(result.retentionPeriodInDays).toBe(30);
}

function expectAuditLogSchema(result: any) {
  expect(result.object).toBe('audit_log_schema');
  expect(result.version).toBe(1);
  expect(result.targets).toEqual([
    {
      type: 'invoice',
      metadata: { type: 'object', properties: { cost: { type: 'number' } } },
    },
  ]);
  expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
}

function expectAuditLogExport(result: any) {
  expect(result.object).toBe('audit_log_export');
  expect(result.id).toBe('audit_log_export_01GBZK5MP7TD1YCFQHFR22180V');
  expect(result.state).toBe('ready');
  expect(result.createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
  expect(result.updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
}

describe('AuditLogs', () => {
  beforeEach(() => fetch.resetMocks());

  describe('getOrganizationAuditLogsRetention', () => {
    it('returns the expected result', async () => {
      fetchOnce(auditLogsRetentionFixture);

      const result = await workos.auditLogs.getOrganizationAuditLogsRetention({
        id: 'test_id',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organizations/test_id/audit_logs_retention',
      );
      expectAuditLogsRetention(result);
    });
  });

  describe('updateOrganizationAuditLogsRetention', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(auditLogsRetentionFixture);

      const result =
        await workos.auditLogs.updateOrganizationAuditLogsRetention({
          id: 'test_id',
          retentionPeriodInDays: 1,
        });

      expect(fetchMethod()).toBe('PUT');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/organizations/test_id/audit_logs_retention',
      );
      expect(fetchBody()).toEqual(
        expect.objectContaining({ retention_period_in_days: 1 }),
      );
      expectAuditLogsRetention(result);
    });
  });

  describe('listActions', () => {
    it('returns paginated results', async () => {
      fetchOnce(listAuditLogActionFixture);

      const { data, listMetadata } = await workos.auditLogs.listActions({
        order: 'desc',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe('/audit_logs/actions');
      expect(fetchSearchParams()).toHaveProperty('order');
      expect(Array.isArray(data)).toBe(true);
      expect(listMetadata).toBeDefined();
      expect(data.length).toBeGreaterThan(0);
      expect(data[0].object).toBe('audit_log_action');
      expect(data[0].name).toBe('user.viewed_invoice');
      expect(data[0].createdAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
      expect(data[0].updatedAt.toISOString()).toBe('2026-01-15T12:00:00.000Z');
    });
  });

  describe('listActionSchemas', () => {
    it('returns paginated results', async () => {
      fetchOnce(listAuditLogSchemaFixture);

      const { data, listMetadata } = await workos.auditLogs.listActionSchemas({
        actionName: 'test_actionName',
        order: 'desc',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/audit_logs/actions/test_actionName/schemas',
      );
      expect(fetchSearchParams()).toHaveProperty('order');
      expect(Array.isArray(data)).toBe(true);
      expect(listMetadata).toBeDefined();
      expect(data.length).toBeGreaterThan(0);
      expectAuditLogSchema(data[0]);
    });
  });

  describe('createSchema', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(auditLogSchemaFixture);

      const result = await workos.auditLogs.createSchema({
        actionName: 'test_actionName',
        targets: [{ type: 'test_type' }],
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/audit_logs/actions/test_actionName/schemas',
      );
      expect(fetchBody()).toEqual(
        expect.objectContaining({ targets: [{ type: 'test_type' }] }),
      );
      expectAuditLogSchema(result);
    });
  });

  describe('createEvent', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(auditLogEventCreateResponseFixture);

      const result = await workos.auditLogs.createEvent({
        organizationId: 'organization_id_01234',
        event: {
          action: 'test_action',
          occurredAt: new Date('2023-01-01T00:00:00.000Z'),
          actor: { id: '01234', type: 'test_type' },
          targets: [{ id: '01234', type: 'test_type' }],
          context: { location: 'test_location' },
        },
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe('/audit_logs/events');
      expect(fetchBody()).toEqual(
        expect.objectContaining({
          organization_id: 'organization_id_01234',
          event: {
            action: 'test_action',
            occurred_at: '2023-01-01T00:00:00.000Z',
            actor: { id: '01234', type: 'test_type' },
            targets: [{ id: '01234', type: 'test_type' }],
            context: { location: 'test_location' },
          },
        }),
      );
      expect(result.success).toBe(true);
    });
  });

  describe('createExport', () => {
    it('sends the correct request and returns result', async () => {
      fetchOnce(auditLogExportFixture);

      const result = await workos.auditLogs.createExport({
        organizationId: 'organization_id_01234',
        rangeStart: 'test_range_start',
        rangeEnd: 'test_range_end',
      });

      expect(fetchMethod()).toBe('POST');
      expect(new URL(String(fetchURL())).pathname).toBe('/audit_logs/exports');
      expect(fetchBody()).toEqual(
        expect.objectContaining({
          organization_id: 'organization_id_01234',
          range_start: 'test_range_start',
          range_end: 'test_range_end',
        }),
      );
      expectAuditLogExport(result);
    });
  });

  describe('getExport', () => {
    it('returns the expected result', async () => {
      fetchOnce(auditLogExportFixture);

      const result = await workos.auditLogs.getExport({
        auditLogExportId: 'test_auditLogExportId',
      });

      expect(fetchMethod()).toBe('GET');
      expect(new URL(String(fetchURL())).pathname).toBe(
        '/audit_logs/exports/test_auditLogExportId',
      );
      expectAuditLogExport(result);
    });
  });
});
