// This file is auto-generated by oagen. Do not edit.

import type { WorkOS } from '../workos';
import type {
  ApplicationCredentialsListItem,
  ApplicationCredentialsListItemResponse,
} from './interfaces/application-credentials-list-item.interface';
import type {
  NewConnectApplicationSecret,
  NewConnectApplicationSecretResponse,
} from './interfaces/new-connect-application-secret.interface';
import type { CreateApplicationSecret } from './interfaces/create-application-secret.interface';
import { deserializeApplicationCredentialsListItem } from './serializers/application-credentials-list-item.serializer';
import { deserializeNewConnectApplicationSecret } from './serializers/new-connect-application-secret.serializer';
import { serializeCreateApplicationSecret } from './serializers/create-application-secret.serializer';

export class ApplicationClientSecrets {
  constructor(private readonly workos: WorkOS) {}

  /**
   * List Client Secrets for a Connect Application
   *
   * List all client secrets associated with a Connect Application.
   * @param id - The application ID or client ID of the Connect Application.
   * @example "conn_app_01HXYZ123456789ABCDEFGHIJ"
   * @returns {Promise<ApplicationCredentialsListItem[]>}
   * @throws {NotFoundException} 404
   */
  async list(id: string): Promise<ApplicationCredentialsListItem[]> {
    const { data } =
      await this.workos.get<ApplicationCredentialsListItemResponse[]>(
        `/connect/applications/${id}/client_secrets`,
      );
    return data.map(deserializeApplicationCredentialsListItem);
  }

  /**
   * Create a new client secret for a Connect Application
   *
   * Create new secrets for a Connect Application.
   * @param id - The application ID or client ID of the Connect Application.
   * @example "conn_app_01HXYZ123456789ABCDEFGHIJ"
   * @param payload - The request body.
   * @returns {NewConnectApplicationSecret}
   * @throws {NotFoundException} 404
   * @throws {UnprocessableEntityException} 422
   */
  async create(
    id: string,
    payload: CreateApplicationSecret,
  ): Promise<NewConnectApplicationSecret> {
    const { data } =
      await this.workos.post<NewConnectApplicationSecretResponse>(
        `/connect/applications/${id}/client_secrets`,
        serializeCreateApplicationSecret(payload),
      );
    return deserializeNewConnectApplicationSecret(data);
  }

  /**
   * Delete a Client Secret
   *
   * Delete (revoke) an existing client secret.
   * @param id - The unique ID of the client secret.
   * @example "secret_01J9Q2Z3X4Y5W6V7U8T9S0R1Q"
   * @returns {void}
   * @throws {NotFoundException} 404
   */
  async delete(id: string): Promise<void> {
    await this.workos.delete(`/connect/client_secrets/${id}`);
  }
}
