name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # 6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: |
          npm install

      - name: Prettier
        run: |
          npm run prettier

      - name: Lint
        run: |
          npm run lint

      - name: Typecheck
        run: |
          npm run typecheck

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test
