name: Coana Vulnerability Analysis

on:
  schedule:
    - cron: '0 3 * * *' # every day at 3 AM
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manually run vulnerability analysis'
      # Required by the return-dispatch action
      distinct_id:

jobs:
  coana-vulnerability-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Coana CLI
        id: coana-cli
        uses: docker://coana/coana:latest@sha256:ba3c99feec27303274a7b0af1715a1b8bca7e027521ecfedab44829e5a80d3e7
        with:
          args: |
            coana run . \
              --api-key ${{ secrets.COANA_API_KEY }} \
              --repo-url https://github.com/${{github.repository}}
