name: Release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # 6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24

      - name: Configure Socket Firewall
        uses: workos/setup-socket-firewall@ca93dd8aa351f54f4729fe3377a9be23c631c25d
        with:
          token: ${{ secrets.PUBLIC_SOCKET_FIREWALL_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Teardown Socket Firewall
        uses: workos/setup-socket-firewall/teardown@ca93dd8aa351f54f4729fe3377a9be23c631c25d

      - name: Publish
        run: npm publish --tag latest --access public --provenance
