// This file is auto-generated by oagen. Do not edit.

import type {
  AuditLogConfiguration,
  AuditLogConfigurationResponse,
} from '../interfaces/audit-log-configuration.interface';
import { deserializeAuditLogConfigurationLogStream } from './audit-log-configuration-log-stream.serializer';

export const deserializeAuditLogConfiguration = (
  response: AuditLogConfigurationResponse,
): AuditLogConfiguration => ({
  organizationId: response.organization_id,
  retentionPeriodInDays: response.retention_period_in_days,
  state: response.state,
  logStream:
    response.log_stream != null
      ? deserializeAuditLogConfigurationLogStream(response.log_stream)
      : undefined,
});
