// This file is auto-generated by oagen. Do not edit.

import type {
  OrganizationDomainData,
  OrganizationDomainDataResponse,
} from '../interfaces/organization-domain-data.interface';

export const deserializeOrganizationDomainData = (
  response: OrganizationDomainDataResponse,
): OrganizationDomainData => ({
  domain: response.domain,
  state: response.state,
});

export const serializeOrganizationDomainData = (
  model: OrganizationDomainData,
): OrganizationDomainDataResponse => ({
  domain: model.domain,
  state: model.state,
});
