// This file is auto-generated by oagen. Do not edit.

import type {
  AuthenticationChallengeVerifyResponse,
  AuthenticationChallengeVerifyResponseWire,
} from '../interfaces/authentication-challenge-verify-response.interface';
import {
  deserializeAuthenticationChallenge,
  serializeAuthenticationChallenge,
} from './authentication-challenge.serializer';

export const deserializeAuthenticationChallengeVerifyResponse = (
  response: AuthenticationChallengeVerifyResponseWire,
): AuthenticationChallengeVerifyResponse => ({
  challenge: deserializeAuthenticationChallenge(response.challenge),
  valid: response.valid,
});

export const serializeAuthenticationChallengeVerifyResponse = (
  model: AuthenticationChallengeVerifyResponse,
): AuthenticationChallengeVerifyResponseWire => ({
  challenge: serializeAuthenticationChallenge(model.challenge),
  valid: model.valid,
});
